workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Create env.json
        script: |
          echo "{\"SUPABASE_URL\": \"$SUPABASE_URL\", \"SUPABASE_ANON_KEY\": \"$SUPABASE_ANON_KEY\", \"STRIPE_PUBLISHABLE_KEY\": \"$STRIPE_PUBLISHABLE_KEY\"}" > env.json
      - name: Build APK
        script: flutter build apk --release --dart-define-from-file=env.json
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      
  web-workflow:
    name: Web Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Create env.json
        script: |
          echo "{\"SUPABASE_URL\": \"$SUPABASE_URL\", \"SUPABASE_ANON_KEY\": \"$SUPABASE_ANON_KEY\", \"STRIPE_PUBLISHABLE_KEY\": \"$STRIPE_PUBLISHABLE_KEY\"}" > env.json
      - name: Build Web
        script: flutter build web --dart-define-from-file=env.json
    artifacts:
      - build/web/**
