/// Spanish translations for the Everywear app
const Map<String, String> appLocalizationsEs = {
  // App info
  'app_name': 'Everywear',
  'app_tagline': 'Entiende Tu Estilo',

  // Common UI
  'continue': 'Continuar',
  'cancel': 'Cancelar',
  'save': 'Guardar',
  'delete': 'Eliminar',
  'edit': 'Editar',
  'settings': 'Configuración',
  'profile': 'Perfil',
  'logout': 'Cerrar sesión',
  'back': 'Atrás',
  'next': 'Siguiente',
  'done': 'Hecho',
  'loading': 'Cargando...',
  'error': 'Error',
  'success': 'Éxito',
  'ok': 'OK',
  'yes': 'Sí',
  'no': 'No',
  'search': 'Buscar',
  'filter': 'Filtrar',
  'sort': 'Ordenar',

  // Auth
  'welcome_back': 'Bienvenido de Nuevo',
  'create_account': 'Crear Cuenta',
  'email': 'Correo electrónico',
  'password': 'Contraseña',
  'full_name': 'Nombre completo',
  'sign_in': 'Iniciar Sesión',
  'sign_up': 'Registrarse',
  'continue_with_google': 'Continuar con Google',
  'continue_with_email': 'Continuar con Correo',
  'already_have_account': '¿Ya tienes una cuenta?',
  'dont_have_account': '¿No tienes una cuenta?',
  'forgot_password': '¿Olvidaste tu contraseña?',
  'or': 'O',
  'sign_in_subtitle': 'Inicia sesión para continuar tu viaje de estilo',
  'sign_up_subtitle': 'Regístrate para comenzar a rastrear tu guardarropa',
  'terms_agreement':
      'Al continuar, aceptas nuestros Términos de Servicio y Política de Privacidad',
  'email_required': 'El correo electrónico es requerido',
  'password_required': 'La contraseña es requerida',
  'name_required': 'El nombre es requerido',
  'invalid_email': 'Ingresa un correo válido',
  'password_too_short': 'La contraseña debe tener al menos 6 caracteres',

  // Settings
  'settings_and_profile': 'Configuración y Perfil',
  'account_settings': 'Configuración de cuenta',
  'app_preferences': 'Preferencias de la aplicación',
  'privacy_settings': 'Configuración de privacidad',
  'data_management': 'Gestión de datos',
  'subscription': 'Suscripción',
  'help_and_support': 'Ayuda y Soporte',
  'language': 'Idioma',
  'select_language': 'Seleccionar idioma',
  'theme': 'Tema',
  'notifications': 'Notificaciones',
  'change_password': 'Cambiar contraseña',
  'update_password': 'Actualiza tu contraseña',
  'two_factor_auth': 'Autenticación de dos factores',
  'email_preferences': 'Preferencias de correo',
  'manage_email_notifications': 'Gestionar notificaciones por correo',
  'enabled': 'Habilitado',
  'disabled': 'Deshabilitado',
  'data_sharing': 'Compartir datos',
  'share_usage_data': 'Compartir datos de uso para mejoras',
  'analytics': 'Analítica',
  'help_improve_app': 'Ayudar a mejorar la aplicación',
  'profile_visibility': 'Visibilidad del perfil',
  'manage_profile_visibility': 'Gestionar quién puede ver tu perfil',
  'export_data': 'Exportar datos',
  'download_wardrobe_data': 'Descargar tus datos de guardarropa',
  'backup_settings': 'Configuración de respaldo',
  'automatic_cloud_backup': 'Respaldo automático en la nube',
  'delete_account': 'Eliminar cuenta',
  'permanently_delete_account': 'Eliminar permanentemente tu cuenta',
  'current_plan': 'Plan actual',
  'billing_history': 'Historial de facturación',
  'view_past_invoices': 'Ver facturas anteriores',
  'upgrade_plan': 'Mejorar plan',
  'unlock_more_features': 'Desbloquear más funciones',
  'help_center': 'Centro de ayuda',
  'faqs_and_guides': 'Preguntas frecuentes y guías',
  'send_feedback': 'Enviar comentarios',
  'share_your_thoughts': 'Comparte tus pensamientos',
  'about': 'Acerca de',
  'version': 'Versión 1.0.0',
  'ai_model_management': 'Gestión del modelo IA',
  'manage_local_ai': 'Gestionar motor IA local',
  'manage_notifications': 'Gestionar preferencias de notificación',
  'light_mode': 'Modo Claro',
  'dark_mode': 'Modo Oscuro',
  'auto_system': 'Auto (Sistema)',

  // Wardrobe
  'wardrobe': 'Guardarropa',
  'add_item': 'Agregar artículo',
  'my_wardrobe': 'Mi guardarropa',
  'outfit': 'Atuendo',
  'outfits': 'Atuendos',
  'daily_log': 'Registro diario',
  'insights': 'Perspectivas',

  // Language names
  'english': 'Inglés',
  'french': 'Francés',
  'spanish': 'Español',

  // Logout confirmation
  'logout_confirmation': '¿Estás seguro de que quieres cerrar sesión?',
  'delete_account_confirmation':
      '¿Estás seguro de que quieres eliminar permanentemente tu cuenta? Esta acción no se puede deshacer.',

  // Export options
  'export_data_format': 'Formato de exportación de datos',
  'pdf_report': 'Informe PDF',
  'comprehensive_wardrobe_report': 'Informe completo de guardarropa',
  'csv_spreadsheet': 'Hoja de cálculo CSV',
  'raw_data_analysis': 'Datos sin procesar para análisis',
  'exporting_data': 'Exportando datos como',

  // About app
  'about_everywear':
      'Everywear te ayuda a tomar decisiones conscientes sobre tu guardarropa a través de análisis y perspectivas.',
  'close': 'Cerrar',

  // AI & Smart Suggestions
  'ai_styling_assistant': 'Asistente de Estilo IA',
  'powered_by_ai': 'Potenciado por IA',
  'dismiss': 'Descartar',
  'smart_suggestions_title': 'Sugerencias Inteligentes',
  'refresh_suggestions': 'Actualizar sugerencias',
  'analyzing_wardrobe': 'La IA está analizando tu guardarropa...',
  'ai_banner_text': '{count} sugerencias potenciadas por IA basadas en tu guardarropa',
  'filter_by_occasion': 'Filtrar por ocasión',
  'outfit_added_to_log': 'Atuendo añadido al registro de hoy',
  'saved_for_later': 'Guardado para después',
  'removed_from_saved': 'Eliminado de guardados',
  'suggestion_dismissed': 'Sugerencia descartada - aprenderemos de esto',
  'undo': 'Deshacer',
  'items_in_this_outfit': 'Artículos en este atuendo',
  'last_worn_label': 'Visto por última vez',
  'styling_tips': 'Consejos de Estilo',

  // Camera
  'camera_flip_error': 'Error al girar la cámara. Por favor, inténtalo de nuevo.',
  'camera_capture_error': 'Error al capturar la foto. Por favor, inténtalo de nuevo.',

  // Filters
  'filter_all': 'Todo',
  'filter_work': 'Trabajo',
  'filter_casual': 'Casual',
  'filter_special': 'Especial',

  // Capture Flow
  'log_outfit': 'Registrar Atuendo',
  'capture_outfit': 'Capturar Atuendo',
  'select_from_wardrobe': 'Seleccionar del Guardarropa',
  'confirm_outfit': 'Confirmar Atuendo',
  'camera_permission_required': 'Se requiere permiso de la cámara para capturar atuendos',
  'camera_init_error': 'Error al inicializar la cámara. Por favor, inténtalo de nuevo.',
  'getting_ai_suggestions': 'Obteniendo sugerencias de IA...',
  'get_ai_tips': 'Obtener Consejos de IA',
  'gallery_pick_error': 'Error al seleccionar la imagen de la galería',
  'how_to_log_outfit': '¿Cómo te gustaría registrar tu atuendo?',
  'capture_method_subtitle': 'Elige tu método preferido para capturar rápidamente tu look de hoy',
  'take_photo': 'Tomar Foto',
  'take_photo_subtitle': 'Captura tu atuendo con la cámara',
  'build_from_wardrobe': 'Armar desde el Guardarropa',
  'build_from_wardrobe_subtitle': 'Selecciona artículos de tu guardarropa',
  'wear_this_today': 'Usar esto hoy',
  'save_for_later_btn': 'Guardar para después',
  'retake': 'Volver a tomar',
  'rate_outfit_error': 'Por favor, califica tu atuendo antes de guardar',
  'outfit_preview': 'Vista Previa del Atuendo',
  'no_image_captured': 'No se capturó ninguna imagen',
  'selected_items_count': 'Artículos Seleccionados ({count})',
  'outfit_name_optional': 'Nombre del Atuendo (Opcional)',
  'outfit_name_hint': 'ej: Viernes Casual, Noche de Cita',
  'feel_in_outfit_question': '¿Cómo te sentiste con este atuendo?',
  'rating_not_great': 'No me sentí bien',
  'rating_ok': 'Bien',
  'rating_loved_it': 'Me encantó',
  'save_outfit': 'Guardar Atuendo',
  'select_at_least_one_item': 'Por favor, selecciona al menos un artículo',
  'search_wardrobe_hint': 'Buscar artículos del guardarropa...',
  'no_items_found': 'No se encontraron artículos',
  'continue_with_item_singular': 'Continuar con {count} artículo',
  'continue_with_items_plural': 'Continuar con {count} artículos',

  // Dynamic AI messages
  'ai_bubble_message_initial':
      '👋 ¡Hola! ¡He analizado tu guardarropa y he encontrado {count} combinaciones de atuendos perfectas para ti hoy! Cada sugerencia está personalizada según tus preferencias de estilo, las condiciones climáticas y tus favoritos anteriores.',
  'ai_bubble_message_found':
      '🎯 ¡He encontrado {count} atuendos potenciados por IA con un {confidence}% de coincidencia con tu estilo! Toca cualquier sugerencia para ver consejos de estilo detallados y completar el look. ¿Quieres probar algo nuevo? ¡También he incluido combinaciones que aún no has usado!',
};
