/// French translations for the Everywear app
const Map<String, String> appLocalizationsFr = {
  // App info
  'app_name': 'Everywear',
  'app_tagline': 'Comprendre Votre Style',

  // Common UI
  'continue': 'Continuer',
  'cancel': 'Annuler',
  'save': 'Enregistrer',
  'delete': 'Supprimer',
  'edit': 'Modifier',
  'settings': 'Paramètres',
  'profile': 'Profil',
  'logout': 'Déconnexion',
  'back': 'Retour',
  'next': 'Suivant',
  'done': 'Terminé',
  'loading': 'Chargement...',
  'error': 'Erreur',
  'success': 'Succès',
  'ok': 'OK',
  'yes': 'Oui',
  'no': 'Non',
  'search': 'Rechercher',
  'filter': 'Filtrer',
  'sort': 'Trier',

  // Auth
  'welcome_back': 'Bon Retour',
  'create_account': 'Créer un Compte',
  'email': 'Email',
  'password': 'Mot de passe',
  'full_name': 'Nom complet',
  'sign_in': 'Se Connecter',
  'sign_up': "S'inscrire",
  'continue_with_google': 'Continuer avec Google',
  'continue_with_email': 'Continuer avec Email',
  'already_have_account': 'Vous avez déjà un compte?',
  'dont_have_account': "Vous n'avez pas de compte?",
  'forgot_password': 'Mot de passe oublié?',
  'or': 'OU',
  'sign_in_subtitle': 'Connectez-vous pour continuer votre parcours style',
  'sign_up_subtitle': 'Inscrivez-vous pour suivre votre garde-robe',
  'terms_agreement':
      "En continuant, vous acceptez nos Conditions d'utilisation et notre Politique de confidentialité",
  'email_required': "L'email est requis",
  'password_required': 'Le mot de passe est requis',
  'name_required': 'Le nom est requis',
  'invalid_email': 'Entrez un email valide',
  'password_too_short': 'Le mot de passe doit contenir au moins 6 caractères',

  // Settings
  'settings_and_profile': 'Paramètres et Profil',
  'account_settings': 'Paramètres du compte',
  'app_preferences': "Préférences de l'application",
  'privacy_settings': 'Paramètres de confidentialité',
  'data_management': 'Gestion des données',
  'subscription': 'Abonnement',
  'help_and_support': 'Aide et Support',
  'language': 'Langue',
  'select_language': 'Sélectionner la langue',
  'theme': 'Thème',
  'notifications': 'Notifications',
  'change_password': 'Changer le mot de passe',
  'update_password': 'Mettez à jour votre mot de passe',
  'two_factor_auth': 'Authentification à deux facteurs',
  'email_preferences': 'Préférences email',
  'manage_email_notifications': 'Gérer les notifications par email',
  'enabled': 'Activé',
  'disabled': 'Désactivé',
  'data_sharing': 'Partage de données',
  'share_usage_data': "Partager les données d'utilisation pour améliorer",
  'analytics': 'Analytique',
  'help_improve_app': "Aider à améliorer l'application",
  'profile_visibility': 'Visibilité du profil',
  'manage_profile_visibility': 'Gérer qui peut voir votre profil',
  'export_data': 'Exporter les données',
  'download_wardrobe_data': 'Télécharger vos données de garde-robe',
  'backup_settings': 'Paramètres de sauvegarde',
  'automatic_cloud_backup': 'Sauvegarde cloud automatique',
  'delete_account': 'Supprimer le compte',
  'permanently_delete_account': 'Supprimer définitivement votre compte',
  'current_plan': 'Plan actuel',
  'billing_history': 'Historique de facturation',
  'view_past_invoices': 'Voir les factures passées',
  'upgrade_plan': 'Améliorer le plan',
  'unlock_more_features': 'Débloquer plus de fonctionnalités',
  'help_center': "Centre d'aide",
  'faqs_and_guides': 'FAQ et guides',
  'send_feedback': 'Envoyer des commentaires',
  'share_your_thoughts': 'Partagez vos pensées',
  'about': 'À propos',
  'version': 'Version 1.0.0',
  'ai_model_management': 'Gestion du modèle IA',
  'manage_local_ai': 'Gérer le moteur IA local',
  'manage_notifications': 'Gérer les préférences de notification',
  'light_mode': 'Mode Clair',
  'dark_mode': 'Mode Sombre',
  'auto_system': 'Auto (Système)',

  // Wardrobe
  'wardrobe': 'Garde-robe',
  'add_item': 'Ajouter un article',
  'my_wardrobe': 'Ma garde-robe',
  'outfit': 'Tenue',
  'outfits': 'Tenues',
  'daily_log': 'Journal quotidien',
  'insights': 'Aperçus',

  // Language names
  'english': 'Anglais',
  'french': 'Français',
  'spanish': 'Espagnol',

  // Logout confirmation
  'logout_confirmation': 'Êtes-vous sûr de vouloir vous déconnecter?',
  'delete_account_confirmation':
      'Êtes-vous sûr de vouloir supprimer définitivement votre compte? Cette action ne peut pas être annulée.',

  // Export options
  'export_data_format': "Format d'export de données",
  'pdf_report': 'Rapport PDF',
  'comprehensive_wardrobe_report': 'Rapport complet de garde-robe',
  'csv_spreadsheet': 'Tableur CSV',
  'raw_data_analysis': "Données brutes pour l'analyse",
  'exporting_data': 'Export des données en',

  // About app
  'about_everywear':
      'Everywear vous aide à prendre des décisions éclairées concernant votre garde-robe grâce aux analyses et aux aperçus.',
  'close': 'Fermer',

  // AI & Smart Suggestions
  'ai_styling_assistant': 'Assistant de Style IA',
  'powered_by_ai': 'Propulsé par l\'IA',
  'dismiss': 'Ignorer',
  'smart_suggestions_title': 'Suggestions Intelligentes',
  'refresh_suggestions': 'Actualiser les suggestions',
  'analyzing_wardrobe': 'L\'IA analyse votre garde-robe...',
  'ai_banner_text': '{count} suggestions propulsées par l\'IA basées sur votre garde-robe',
  'filter_by_occasion': 'Filtrer par occasion',
  'outfit_added_to_log': 'Tenue ajoutée au journal d\'aujourd\'hui',
  'saved_for_later': 'Enregistré pour plus tard',
  'removed_from_saved': 'Retiré des enregistrements',
  'suggestion_dismissed': 'Suggestion ignorée - nous apprendrons de cela',
  'undo': 'Annuler',
  'items_in_this_outfit': 'Articles dans cette tenue',
  'last_worn_label': 'Dernière fois porté',
  'styling_tips': 'Conseils de Style',

  // Camera
  'camera_flip_error': 'Échec du basculement de la caméra. Veuillez réessayer.',
  'camera_capture_error': 'Échec de la capture de la photo. Veuillez réessayer.',

  // Filters
  'filter_all': 'Tout',
  'filter_work': 'Travail',
  'filter_casual': 'Décontracté',
  'filter_special': 'Spécial',

  // Capture Flow
  'log_outfit': 'Enregistrer la Tenue',
  'capture_outfit': 'Capturer la Tenue',
  'select_from_wardrobe': 'Sélectionner dans la Garde-robe',
  'confirm_outfit': 'Confirmer la Tenue',
  'camera_permission_required': 'L\'autorisation de la caméra est requise pour capturer des tenues',
  'camera_init_error': 'Échec de l\'initialisation de la caméra. Veuillez réessayer.',
  'getting_ai_suggestions': 'Obtention de suggestions IA...',
  'get_ai_tips': 'Obtenir des Conseils IA',
  'gallery_pick_error': 'Échec de la sélection de l\'image dans la galerie',
  'how_to_log_outfit': 'Comment souhaitez-vous enregistrer votre tenue ?',
  'capture_method_subtitle': 'Choisissez votre méthode préférée pour capturer rapidement votre look du jour',
  'take_photo': 'Prendre une Photo',
  'take_photo_subtitle': 'Capturez votre tenue avec la caméra',
  'build_from_wardrobe': 'Construire à partir de la Garde-robe',
  'build_from_wardrobe_subtitle': 'Sélectionnez des articles dans votre garde-robe',
  'wear_this_today': 'Porter aujourd\'hui',
  'save_for_later_btn': 'Enregistrer pour plus tard',
  'retake': 'Recommencer',
  'rate_outfit_error': 'Veuillez évaluer votre tenue avant de l\'enregistrer',
  'outfit_preview': 'Aperçu de la Tenue',
  'no_image_captured': 'Aucune image capturée',
  'selected_items_count': 'Articles Sélectionnés ({count})',
  'outfit_name_optional': 'Nom de la Tenue (Optionnel)',
  'outfit_name_hint': 'ex: Vendredi Décontracté, Soirée en amoureux',
  'feel_in_outfit_question': 'Comment vous êtes-vous senti dans cette tenue ?',
  'rating_not_great': 'Pas super',
  'rating_ok': 'Correct',
  'rating_loved_it': 'J\'ai adoré',
  'save_outfit': 'Enregistrer la Tenue',
  'select_at_least_one_item': 'Veuillez sélectionner au moins un article',
  'search_wardrobe_hint': 'Rechercher des articles...',
  'no_items_found': 'Aucun article trouvé',
  'continue_with_item_singular': 'Continuer avec {count} article',
  'continue_with_items_plural': 'Continuer avec {count} articles',

  // Dynamic AI messages
  'ai_bubble_message_initial':
      '👋 Salut ! J\'ai analysé votre garde-robe et trouvé {count} combinaisons de tenues parfaites pour vous aujourd\'hui ! Chaque suggestion est personnalisée en fonction de vos préférences de style, des conditions météorologiques et de vos favoris passés.',
  'ai_bubble_message_found':
      '🎯 J\'ai trouvé {count} tenues propulsées par l\'IA avec une correspondance de {confidence}% avec votre style ! Appuyez sur n\'importe quelle suggestion pour voir des conseils de style détaillés et compléter le look. Envie d\'essayer quelque chose de nouveau ? J\'ai aussi inclus des combinaisons que vous n\'avez pas encore portées !',
};
