/// English translations for the Everywear app
const Map<String, String> appLocalizationsEn = {
  // App info
  'app_name': 'Everywear',
  'app_tagline': 'Understand Your Style',

  // Common UI
  'continue': 'Continue',
  'cancel': 'Cancel',
  'save': 'Save',
  'delete': 'Delete',
  'edit': 'Edit',
  'settings': 'Settings',
  'profile': 'Profile',
  'logout': 'Logout',
  'back': 'Back',
  'next': 'Next',
  'done': 'Done',
  'loading': 'Loading...',
  'error': 'Error',
  'success': 'Success',
  'ok': 'OK',
  'yes': 'Yes',
  'no': 'No',
  'search': 'Search',
  'filter': 'Filter',
  'sort': 'Sort',

  // Auth
  'welcome_back': 'Welcome Back',
  'create_account': 'Create Account',
  'email': 'Email',
  'password': 'Password',
  'full_name': 'Full Name',
  'sign_in': 'Sign In',
  'sign_up': 'Sign Up',
  'continue_with_google': 'Continue with Google',
  'continue_with_email': 'Continue with Email',
  'already_have_account': 'Already have an account?',
  'dont_have_account': "Don't have an account?",
  'forgot_password': 'Forgot Password?',
  'or': 'OR',
  'sign_in_subtitle': 'Sign in to continue your style journey',
  'sign_up_subtitle': 'Sign up to start tracking your wardrobe',
  'terms_agreement':
      'By continuing, you agree to our Terms of Service and Privacy Policy',
  'email_required': 'Email is required',
  'password_required': 'Password is required',
  'name_required': 'Name is required',
  'invalid_email': 'Enter a valid email',
  'password_too_short': 'Password must be at least 6 characters',

  // Settings
  'settings_and_profile': 'Settings & Profile',
  'account_settings': 'Account Settings',
  'app_preferences': 'App Preferences',
  'privacy_settings': 'Privacy Settings',
  'data_management': 'Data Management',
  'subscription': 'Subscription',
  'help_and_support': 'Help & Support',
  'language': 'Language',
  'select_language': 'Select Language',
  'theme': 'Theme',
  'notifications': 'Notifications',
  'change_password': 'Change Password',
  'update_password': 'Update your password',
  'two_factor_auth': 'Two-Factor Authentication',
  'email_preferences': 'Email Preferences',
  'manage_email_notifications': 'Manage email notifications',
  'enabled': 'Enabled',
  'disabled': 'Disabled',
  'data_sharing': 'Data Sharing',
  'share_usage_data': 'Share usage data for improvements',
  'analytics': 'Analytics',
  'help_improve_app': 'Help improve the app',
  'profile_visibility': 'Profile Visibility',
  'manage_profile_visibility': 'Manage who can see your profile',
  'export_data': 'Export Data',
  'download_wardrobe_data': 'Download your wardrobe data',
  'backup_settings': 'Backup Settings',
  'automatic_cloud_backup': 'Automatic cloud backup',
  'delete_account': 'Delete Account',
  'permanently_delete_account': 'Permanently delete your account',
  'current_plan': 'Current Plan',
  'billing_history': 'Billing History',
  'view_past_invoices': 'View past invoices',
  'upgrade_plan': 'Upgrade Plan',
  'unlock_more_features': 'Unlock more features',
  'help_center': 'Help Center',
  'faqs_and_guides': 'FAQs and guides',
  'send_feedback': 'Send Feedback',
  'share_your_thoughts': 'Share your thoughts',
  'privacy_policy': 'Privacy Policy',
  'view_privacy_policy': 'View our privacy policy',
  'terms_of_service': 'Terms of Service',
  'view_terms_of_service': 'View our terms of service',
  'about': 'About',
  'version': 'Version 1.0.0',
  'ai_model_management': 'AI Model Management',
  'manage_local_ai': 'Manage local AI engine',
  'manage_notifications': 'Manage notification preferences',
  'light_mode': 'Light Mode',
  'dark_mode': 'Dark Mode',
  'auto_system': 'Auto (System)',

  // Wardrobe
  'wardrobe': 'Wardrobe',
  'add_item': 'Add Item',
  'my_wardrobe': 'My Wardrobe',
  'outfit': 'Outfit',
  'outfits': 'Outfits',
  'daily_log': 'Daily Log',
  'insights': 'Insights',
  'your_style_profile': 'Your Style Profile',

  // Language names
  'english': 'English',
  'french': 'French',
  'spanish': 'Spanish',

  // Logout confirmation
  'logout_confirmation': 'Are you sure you want to logout?',
  'delete_account_confirmation':
      'Are you sure you want to permanently delete your account? This action cannot be undone.',

  // Export options
  'export_data_format': 'Export Data Format',
  'pdf_report': 'PDF Report',
  'comprehensive_wardrobe_report': 'Comprehensive wardrobe report',
  'csv_spreadsheet': 'CSV Spreadsheet',
  'raw_data_analysis': 'Raw data for analysis',
  'exporting_data': 'Exporting data as',

  // About app
  'about_everywear':
      'Everywear helps you make mindful wardrobe decisions through analytics and insights.',
  'close': 'Close',

  // AI & Smart Suggestions
  'ai_styling_assistant': 'AI Styling Assistant',
  'powered_by_ai': 'Powered by AI',
  'dismiss': 'Dismiss',
  'smart_suggestions_title': 'Smart Suggestions',
  'refresh_suggestions': 'Refresh suggestions',
  'analyzing_wardrobe': 'AI is analyzing your wardrobe...',
  'ai_banner_text': '{count} AI-powered suggestions based on your wardrobe',
  'filter_by_occasion': 'Filter by occasion',
  'outfit_added_to_log': 'Outfit added to today\'s log',
  'saved_for_later': 'Saved for later',
  'removed_from_saved': 'Removed from saved',
  'suggestion_dismissed': 'Suggestion dismissed - we\'ll learn from this',
  'undo': 'Undo',
  'items_in_this_outfit': 'Items in this outfit',
  'last_worn_label': 'Last worn',
  'styling_tips': 'Styling Tips',

  // Camera
  'camera_flip_error': 'Failed to flip camera. Please try again.',
  'camera_capture_error': 'Failed to capture photo. Please try again.',

  // Filters
  'filter_all': 'All',
  'filter_work': 'Work',
  'filter_casual': 'Casual',
  'filter_special': 'Special',

  // Capture Flow
  'log_outfit': 'Log Outfit',
  'capture_outfit': 'Capture Outfit',
  'select_from_wardrobe': 'Select from Wardrobe',
  'confirm_outfit': 'Confirm Outfit',
  'camera_permission_required': 'Camera permission is required to capture outfits',
  'camera_init_error': 'Failed to initialize camera. Please try again.',
  'getting_ai_suggestions': 'Getting AI suggestions...',
  'get_ai_tips': 'Get AI Tips',
  'gallery_pick_error': 'Failed to pick image from gallery',
  'how_to_log_outfit': 'How would you like to log your outfit?',
  'capture_method_subtitle': 'Choose your preferred method to quickly capture today\'s look',
  'take_photo': 'Take Photo',
  'take_photo_subtitle': 'Capture your outfit with camera',
  'build_from_wardrobe': 'Build from Wardrobe',
  'build_from_wardrobe_subtitle': 'Select items from your wardrobe',
  'wear_this_today': 'Wear This Today',
  'save_for_later_btn': 'Save for Later',
  'retake': 'Retake',
  'rate_outfit_error': 'Please rate your outfit before saving',
  'outfit_preview': 'Outfit Preview',
  'outfit_logged_success': 'Outfit logged successfully!',
  'optional_notes_hint': 'Add some notes about this outfit...',
  'no_image_captured': 'No image captured',
  'selected_items_count': 'Selected Items ({count})',
  'outfit_name_optional': 'Outfit Name (Optional)',
  'outfit_name_hint': 'e.g., Casual Friday, Date Night',
  'feel_in_outfit_question': 'How did you feel in this outfit?',
  'rating_not_great': 'Didn\'t feel great',
  'rating_ok': 'OK',
  'rating_loved_it': 'Loved it',
  'save_outfit': 'Save Outfit',
  'select_at_least_one_item': 'Please select at least one item',
  'search_wardrobe_hint': 'Search wardrobe items...',
  'no_items_found': 'No items found',
  'continue_with_item_singular': 'Continue with {count} item',
  'continue_with_items_plural': 'Continue with {count} items',
  'cost_per_wear': 'Cost Per Wear',
  'per_wear': '/wear',

  // Dynamic AI messages
  'ai_bubble_message_initial':
      '👋 Hi! I\'ve analyzed your wardrobe and found {count} perfect outfit combinations for you today! Each suggestion is personalized based on your style preferences, weather conditions, and past favorites.',
  'ai_bubble_message_found':
      '🎯 I found {count} AI-powered outfits with a {confidence}% match to your style! Tap any suggestion to see detailed styling tips and complete the look. Want to try something new? I\'ve also included combinations you haven\'t worn yet!',
  
  // New Wardrobe & Item Management
  'retry': 'Retry',
  'items': 'items',
  'selected_items': 'selected items',
  'items_limit_reached': 'Item limit reached',
  'live_sync': 'Live',
  'wardrobe_search_hint': 'Search by name or brand',
  'loading_wardrobe': 'Loading wardrobe...',
  'failed_to_load_wardrobe': 'Failed to load wardrobe',
  'delete_item': 'Delete Item',
  'delete_items': 'Delete Items',
  'delete_item_confirmation': 'Are you sure you want to delete this item from your wardrobe?',
  'item_deleted_success': 'Item deleted successfully',
  'item_delete_error': 'Failed to delete item',
  'items_deleted_success': 'Items deleted successfully',
  'items_delete_error': 'Failed to delete items',
  'item_added_to_wardrobe': 'added to wardrobe',
  'item_save_error': 'Failed to save item. Please try again.',
  'unsaved_changes': 'You have unsaved changes. Are you sure you want to leave?',
  'discard': 'Discard',
  'edit_item': 'Edit Item',
  'changes': 'Changes',

  // Daily Log
  'good_morning': 'Good morning',
  'good_afternoon': 'Good afternoon',
  'good_evening': 'Good evening',
  'log_outfit_btn': 'Log outfit',
  'repeat_outfit': 'Repeat Outfit',
  'repeat_outfit_question': 'Log this outfit again for today?',
  'outfit_repeated': 'Outfit repeated for today!',
  'edit_outfit': 'Edit Outfit',
  'delete_outfit': 'Delete Outfit',
  'delete_outfit_confirmation': 'Are you sure you want to delete this outfit?',
  'outfit_deleted': 'Outfit deleted',
  'outfit_updated': 'Outfit updated!',
  'this_month': 'This Month',
  'rating': 'Rating: ',
  'weather_fallback_label': 'Style, your way',
  'daily_log_welcome_subtitle': 'A calm space to choose what feels right today — guided by your wardrobe, your plans, and your mood.',
  'set_todays_direction': 'Set today’s direction',
  'set_direction_subtitle': 'Choose the occasion and vibe you want. Your suggestion updates around that.',
  'dressing_for': 'Dressing for',
  'todays_vibe': 'Today’s vibe',
  'occasion_work': 'Work',
  'occasion_casual': 'Casual',
  'occasion_dinner': 'Dinner',
  'occasion_event': 'Event',
  'occasion_travel': 'Travel',
  'mood_casual': 'Casual',
  'mood_polished': 'Polished',
  'mood_comfort': 'Comfort',
  'mood_bold': 'Bold',
  'mood_surprise': 'Surprise',
  'weather_tip_rain': 'Bring a waterproof layer today',
  'weather_tip_snow': 'Layer up and keep the outfit warm',
  'weather_tip_sun': 'Perfect for lighter layers',
  'weather_tip_cloud': 'A light jacket would work well',
  'weather_tip_wind': 'A fitted layer will help on a windy day',
  'weather_tip_default': 'Dress for your day ahead',
  'todays_style_idea': 'Today\'s Style Idea',
  'simple_daily_suggestion': 'A simple daily outfit suggestion.',
  'anchor_piece_tap_to_swap': 'Anchor piece · Tap to swap',
  'tap_to_swap': 'Tap to swap',
  'refresh': 'Refresh',
  'unknown': 'Unknown',
  'outfit_label': 'Outfit',
  'style_tip': 'Style Tip',
  'style_tip_no_logs': 'Start logging your outfits regularly to unlock more personal style patterns and smarter daily guidance.',
  'style_tip_few_logs': 'You are still building your outfit history. A few more logs will make your suggestions more personal and more varied.',
  'style_tip_bold': 'Since you want a bolder look today, keep one standout piece and let the rest of the outfit stay more balanced.',
  'style_tip_comfort': 'Comfort works best when the outfit still feels intentional. Try keeping the base soft and the outer layer more structured.',
  'style_tip_favorite_occasion': 'Your most common occasion this month is {occasion}. Keeping one reliable version of that look ready can save time on busy days.',
  'upcoming_event': 'Upcoming Event',
  'in_days_left': 'In {days} days',
  'dress_code_format': 'Dress code: {dressCode}',
  'item_denim_jacket': 'Denim Jacket',
  'item_white_tee': 'White Tee',
  'item_black_jeans': 'Black Jeans',
  'item_sneakers': 'Sneakers',
  'item_navy_blazer': 'Navy Blazer',
  'item_white_shirt': 'White Shirt',
  'item_tailored_trousers': 'Tailored Trousers',
  'item_leather_shoes': 'Leather Shoes',
  'item_statement_jacket': 'Statement Jacket',
  'item_silk_top': 'Silk Top',
  'item_dark_trousers': 'Dark Trousers',
  'item_low_heels': 'Low Heels',
  'item_chelsea_boots': 'Chelsea Boots',
  'item_light_overshirt': 'Light Overshirt',
  'item_breathable_tee': 'Breathable Tee',
  'item_relaxed_pants': 'Relaxed Pants',
  'item_comfort_sneakers': 'Comfort Sneakers',
  'item_structured_blazer': 'Structured Blazer',
  'item_refined_top': 'Refined Top',
  'item_tailored_bottoms': 'Tailored Bottoms',
  'item_dress_shoes': 'Dress Shoes',
  'item_waterproof_jacket': 'Waterproof Jacket',
  'item_soft_tee': 'Soft Tee',
  'item_dark_jeans': 'Dark Jeans',
  'item_weatherproof_sneakers': 'Weatherproof Sneakers',
  'item_light_cardigan': 'Light Cardigan',
  'item_cotton_tee': 'Cotton Tee',
  'item_relaxed_trousers': 'Relaxed Trousers',
  'item_white_sneakers': 'White Sneakers',
  'item_tailored_overshirt': 'Tailored Overshirt',
  'item_clean_neutral_top': 'Clean Neutral Top',
  'item_straight_trousers': 'Straight Trousers',
  'item_minimal_loafers': 'Minimal Loafers',
  'item_chunky_sneakers': 'Chunky Sneakers',
  'item_black_tee': 'Black Tee',
  'item_soft_blouse': 'Soft Blouse',
  'item_straight_jeans': 'Straight Jeans',
  'item_tailored_shorts': 'Tailored Shorts',
  'item_leather_loafers': 'Leather Loafers',
  'item_minimal_trainers': 'Minimal Trainers',
  'occasion_everyday': 'Everyday',
  'event_type_other': 'Other',
  'item_statement_layer': 'Statement Layer',
  'item_contrast_top': 'Contrast Top',
  'item_dark_denim': 'Dark Denim',
  'item_bold_sneakers': 'Bold Sneakers',
  'item_underused_jacket': 'Underused Jacket',
  'item_neutral_base_top': 'Neutral Base Top',
  'item_wide_leg_pants': 'Wide-Leg Pants',
  'cat_shoes': 'Shoes',
  'cat_footwear': 'Footwear',
  'cat_anchor': 'Anchor',
  'cat_clothing': 'Clothing',
  'unknown_item': 'Unknown Item',
  'todays_log_section': 'Today\'s Log',
  'nothing_logged_today': 'Nothing logged yet today',
  'quick_log_prompt': 'Use the quick log button to save today’s outfit and build your style history.',
  'swap_item_title': 'Swap {item}',
  'choose_different_piece': 'Choose a different piece for this outfit idea',
  'quick_log_options': 'Quick Log Options',
  'quick_log_take_photo_title': 'Take Photo',
  'quick_log_take_photo_subtitle': 'Capture your outfit now',
  'quick_log_previous_title': 'Log Previous Outfit',
  'quick_log_previous_subtitle': 'Add outfit from earlier today',
  'quick_log_repeat_title': 'Repeat Last Outfit',
  'quick_log_repeat_subtitle': 'Log your most recent outfit again',
  'quick_log_save_displayed_title': 'Save Displayed Outfit',
  'quick_log_save_displayed_subtitle': 'Log the outfit shown above',
  'total_outfits': 'Total Outfits',
  'unique_items': 'Unique Items',
  'favorite_occasion': 'Favorite Occasion',
  'tip_of_the_week': 'Tip of the Week',
  'personalized_coaching': 'Personalized coaching',
  'complete_quiz_for_coaching': 'Complete your quiz for better coaching',
  'coach_is_thinking': 'Your coach is thinking...',
  'coach_is_preparing_tip': 'Your coach is preparing a tip for you...',
  'discover_your_style': 'Discover Your Style',
  'retake_quiz': 'Retake',
  'take_quiz_to_personalise': 'Take the quiz to personalise your AI suggestions',
  'quick_questions': 'Quick questions',
  'get_help_styling_pieces': 'Get help styling pieces you own',
  'event_coaching': 'Event coaching',
  'suggestions_for': 'Suggestions for {title}',
  'add_event_to_unlock': 'Add an event to unlock this',
  'coach_limit_reached': 'Coach limit reached',
  'premium_coach_limit_msg': 'You have used all 50 coaching sessions this month. Your quota resets next month.',
  'free_coach_limit_msg': 'Essential plan includes 1 coaching session per week. Upgrade to Signature for 50 sessions per month.',
  'ask_your_coach_new': 'Ask your coach',
  'type_question_or_pick_topic': 'Type your own question or pick a topic.',
  'coach_hint_text': 'e.g. How do I look more confident?',
  'topic_outfit_ideas': '👔 Outfit ideas',
  'topic_shopping_advice': '🛍 Shopping advice',
  'topic_my_wardrobe': '👗 My wardrobe',
  'topic_for_an_event': '📅 For an event',
  'topic_more_variety': '🔄 More variety',
  'topic_style_upgrade': '✨ Style upgrade',
  'q_outfit_ideas': 'Give me outfit ideas based on my wardrobe and style profile.',
  'q_shopping_advice': 'What piece should I buy next to complete more outfits in my wardrobe?',
  'q_my_wardrobe': 'Give me an honest assessment of my wardrobe based on my data.',
  'q_for_an_event': 'How should I dress for a special occasion based on my style?',
  'q_more_variety': 'How can I create more outfit variety with what I already own?',
  'q_style_upgrade': 'What is one thing I can change to elevate my everyday style?',
  'notes': 'Notes',
  'no_outfit_displayed_error': 'No outfit displayed to save',
  'no_valid_wardrobe_items_error': 'No valid wardrobe items in the displayed outfit',
  'slot_anchor': 'anchor piece',
  'slot_top': 'top',
  'slot_bottom': 'bottom',
  'slot_shoes': 'shoes',
  'slot_item': 'item',
  'fallback_suggestion_desc': 'A versatile everyday outfit idea built around one easy anchor piece.',
  'work_suggestion_desc': 'A polished work-ready outfit that keeps things structured without feeling too rigid.',
  'dinner_suggestion_desc': 'A slightly elevated evening look that feels intentional but still wearable.',
  'travel_suggestion_desc': 'A practical travel outfit that keeps movement and layering in mind.',
  'event_suggestion_desc': 'A more occasion-ready combination designed to look sharp and put together.',
  'rain_suggestion_desc': 'A practical weather-aware outfit that stays comfortable in wet conditions.',
  'sun_suggestion_desc': 'A lighter outfit idea that works well for a brighter day and easy movement.',
  'polished_suggestion_desc': 'A clean, polished outfit idea that sharpens the overall look without overdoing it.',
  'bold_suggestion_desc': 'A more expressive combination that keeps the silhouette simple while letting one piece stand out.',
  'surprise_suggestion_desc': 'A fresher combination designed to help you wear something a little less expected today.',
  'outfit_image_label': 'Outfit image',
  'repeat_outfit_tooltip': 'Repeat outfit today',
  'edit_outfit_tooltip': 'Edit outfit',
  'delete_outfit_tooltip': 'Delete outfit',
  'outfits_label': 'Outfits',
  'items_label': 'Items',
  'top_label': 'Top',

  // Smart Suggestions
  'style_title': 'Style',
  'ask_your_coach': 'Ask your coach',
  'add_event': 'Add Event',
  'delete_event': 'Delete Event',
  'remove_event_question': 'Remove this event?',
  'style_coach': 'Style Coach',
  'or_pick_a_topic': 'Or pick a topic',
  'event_name': 'Event Name',
  'hint_wedding': 'e.g. Sarah\'s Wedding',
  'date_label': 'Date',
  'dress_code_optional': 'Dress Code (optional)',
  'finish': 'Finish',
  'style_quiz': 'Style Quiz',
  'profile_classic': 'Classic Elegance',
  'profile_bold': 'Bold & Trendy',
  'profile_active': 'Active & Sporty',
  'profile_minimalist': 'Minimalist',

  // Purchase Tracking
  'monthly_budget': 'Monthly Budget',
  'add_to_wishlist': 'Add to Style Wishlist',
  'update_price': 'Update price',
  'mark_as_purchased': 'Mark as Purchased',
  'remove_from_wishlist': 'Remove from Wishlist',
  'delete_purchase': 'Delete Purchase',
  'bought_it': 'Bought it!',
  'confirm_purchase': 'Confirm',
  'how_much_did_you_pay': 'How much did you pay for',
  'added_to_wardrobe_log': 'added to your wardrobe log',

  // Quiz — questions 1, 2, 3 & 5
  'q_feel_like_yourself': 'Which outfits make you feel most like yourself?',
  'q_feel_relaxed': 'Relaxed and effortless',
  'q_feel_polished': 'Polished and timeless',
  'q_feel_creative': 'Creative and expressive',
  'q_feel_practical': 'Practical and sporty',
  'q_colors_dominate': 'What colors dominate your wardrobe today?',
  'q_colors_neutrals': 'Mostly neutrals',
  'q_colors_earth': 'Earth tones and warm shades',
  'q_colors_bold': 'Bold colors and contrast',
  'q_colors_soft': 'Soft tones and light shades',
  'q_help_most': 'What do you want help with most right now?',
  'q_help_together': 'Looking more put together',
  'q_help_variety': 'Creating more outfit variety',
  'q_help_shopping': 'Shopping more intentionally',
  'q_help_confident': 'Feeling more confident in what I wear',
  'q_matters_most': 'When choosing clothes, what matters most to you?',
  'q_matters_comfort': 'Comfort',
  'q_matters_elegance': 'Elegance',
  'q_matters_originality': 'Originality',
  'q_matters_versatility': 'Versatility',

  // Wardrobe
  'your_personal_collection': 'Your personal collection, ready to style anywhere.',
  'updated_everywhere': 'Updated everywhere',
  'item_updated': 'Item updated',

  'check_back_soon': 'Check back soon for new style challenges',
  'no_insights_yet': 'No insights yet',
  'add_items_for_insights': 'Add items to your wardrobe to see your style insights',
  'outfits_logged': 'Outfits Logged',
  'top_category': 'Top Category',
  'top_occasion': 'Top Occasion',
  'q_style_adventures': 'How adventurous are you with styling?',
  'q_style_adv_works': 'I stay with what I know works',
  'q_style_adv_small': 'I like small changes',
  'q_style_adv_often': 'I enjoy experimenting often',
  'q_style_adv_depends': 'It depends on the occasion',
  'profile_style': 'Style',
  'final_price': 'Final price',
  'current_price': 'Current price',

  'overall_rating': 'Overall Rating',
  'how_did_you_feel': 'How did you feel in this outfit?',
  'detailed_ratings': 'Detailed Ratings',
  'comfort': 'Comfort',
  'style': 'Style',
  'versatility': 'Versatility',
  'occasion': 'Occasion',
  'would_wear_again': 'Would wear again?',
  'help_us_learn': 'Help us learn your preferences',
  'save_rating': 'Save Rating',

  'skip_photo': 'Skip Photo',
  'failed_to_capture_photo': 'Failed to capture photo. Please try again.',

  'save_error': 'Save error',
  'filter_by_category': 'Filter by Category',
  'custom_date_range': 'Custom Date Range',

  // Category names
  'tops': 'Tops',
  'bottoms': 'Bottoms',
  'shoes': 'Shoes',
  'outerwear': 'Outerwear',
  'accessories': 'Accessories',
  'dresses': 'Dresses',
  'activewear': 'Activewear',

  // Common UI Labels
  'confirm': 'Confirm',
  'remove': 'Remove',
  'update': 'Update',
  'create': 'Create',
  'apply': 'Apply',
  'clear': 'Clear',
  'view': 'View',
  'details': 'Details',
  'options': 'Options',
  'more': 'More',
  'less': 'Less',
  'show': 'Show',
  'hide': 'Hide',
  'info': 'Info',
  'description': 'Description',
  'summary': 'Summary',
  'total': 'Total',
  'subtotal': 'Subtotal',
  'count': 'Count',
  'amount': 'Amount',
  'price': 'Price',
  'cost': 'Cost',
  'value': 'Value',
  'date': 'Date',
  'time': 'Time',
  'day': 'Day',
  'week': 'Week',
  'month': 'Month',
  'year': 'Year',
  'today': 'Today',
  'yesterday': 'Yesterday',
  'tomorrow': 'Tomorrow',
  'now': 'Now',
  'soon': 'Soon',
  'later': 'Later',
  'never': 'Never',
  'always': 'Always',
  'optional': 'Optional',
  'required': 'Required',
  'recommended': 'Recommended',
  'popular': 'Popular',
  'trending': 'Trending',
  'new': 'New',
  'featured': 'Featured',
  'premium': 'Premium',
  'free': 'Free',
  'pro': 'Pro',
  'upgrade': 'Upgrade',
  'downgrade': 'Downgrade',
  'subscribe': 'Subscribe',
  'unsubscribe': 'Unsubscribe',
  'renew': 'Renew',
  'expire': 'Expire',
  'active': 'Active',
  'inactive': 'Inactive',
  'pending': 'Pending',
  'completed': 'Completed',
  'in_progress': 'In Progress',
  'not_started': 'Not Started',
  'archived': 'Archived',
  'deleted': 'Deleted',
  'restored': 'Restored',
  'copied': 'Copied',
  'pasted': 'Pasted',
  'moved': 'Moved',
  'renamed': 'Renamed',
  'uploaded': 'Uploaded',
  'downloaded': 'Downloaded',
  'synced': 'Synced',
  'connected': 'Connected',
  'disconnected': 'Disconnected',
  'online': 'Online',
  'offline': 'Offline',
  'available': 'Available',
  'unavailable': 'Unavailable',
  'visible': 'Visible',
  'hidden': 'Hidden',
  'public': 'Public',
  'private': 'Private',
  'shared': 'Shared',
  'locked': 'Locked',
  'unlocked': 'Unlocked',
  'on': 'On',
  'off': 'Off',
  'auto': 'Auto',
  'manual': 'Manual',
  'custom': 'Custom',
  'default_': 'Default',
  'standard': 'Standard',
  'advanced': 'Advanced',
  'basic': 'Basic',
  'simple': 'Simple',
  'complex': 'Complex',
  'easy': 'Easy',
  'hard': 'Hard',
  'difficult': 'Difficult',
  'challenging': 'Challenging',
  'quick': 'Quick',
  'fast': 'Fast',
  'slow': 'Slow',
  'instant': 'Instant',
  'immediate': 'Immediate',
  'scheduled': 'Scheduled',
  'recurring': 'Recurring',
  'one_time': 'One Time',
  'daily': 'Daily',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
  'yearly': 'Yearly',
  'hourly': 'Hourly',
  'minutes': 'Minutes',
  'hours': 'Hours',
  'days': 'Days',
  'weeks': 'Weeks',
  'months': 'Months',
  'years': 'Years',
  'per_minute': 'Per Minute',
  'per_hour': 'Per Hour',
  'per_day': 'Per Day',
  'per_week': 'Per Week',
  'per_month': 'Per Month',
  'per_year': 'Per Year',
  'unlimited': 'Unlimited',
  'limited': 'Limited',
  'restricted': 'Restricted',
  'allowed': 'Allowed',
  'blocked': 'Blocked',
  'banned': 'Banned',
  'suspended': 'Suspended',
  'verified': 'Verified',
  'unverified': 'Unverified',
  'confirmed': 'Confirmed',
  'unconfirmed': 'Unconfirmed',
  'approved': 'Approved',
  'rejected': 'Rejected',
  'accepted': 'Accepted',
  'declined': 'Declined',
  'invited': 'Invited',
  'joined': 'Joined',
  'left': 'Left',
  'removed': 'Removed',
  'added': 'Added',
  'included': 'Included',
  'excluded': 'Excluded',
  'missing': 'Missing',
  'found': 'Found',
  'lost': 'Lost',
  'won': 'Won',
  'lost_game': 'Lost',
  'draw': 'Draw',
  'tie': 'Tie',
  'winner': 'Winner',
  'loser': 'Loser',
  'player': 'Player',
  'team': 'Team',
  'member': 'Member',
  'members': 'Members',
  'group': 'Group',
  'groups': 'Groups',
  'community': 'Community',
  'organization': 'Organization',
  'company': 'Company',
  'business': 'Business',
  'personal': 'Personal',
  'professional': 'Professional',
  'work': 'Work',
  'home': 'Home',
  'office': 'Office',
  'school': 'School',
  'university': 'University',
  'college': 'College',
  'class': 'Class',
  'course': 'Course',
  'lesson': 'Lesson',
  'lecture': 'Lecture',
  'tutorial': 'Tutorial',
  'guide': 'Guide',
  'documentation': 'Documentation',
  'reference': 'Reference',
  'example': 'Example',
  'sample': 'Sample',
  'template': 'Template',
  'draft': 'Draft',
  'final': 'Final',
  'published': 'Published',
  'unpublished': 'Unpublished',
  'scheduled_post': 'Scheduled',
  'pending_approval': 'Pending Approval',
  'under_review': 'Under Review',
  'approved_for': 'Approved',
  'rejected_for': 'Rejected',
  'needs_changes': 'Needs Changes',
  'incomplete': 'Incomplete',
  'complete': 'Complete',
  'finished': 'Finished',
  'done_status': 'Done',
  'started': 'Started',
  'stopped': 'Stopped',
  'paused': 'Paused',
  'resumed': 'Resumed',
  'restarted': 'Restarted',
  'reset': 'Reset',
  'cleared': 'Cleared',
  'cleaned': 'Cleaned',
  'optimized': 'Optimized',
  'improved': 'Improved',
  'enhanced': 'Enhanced',
  'upgraded': 'Upgraded',
  'updated_status': 'Updated',
  'modified': 'Modified',
  'changed': 'Changed',
  'adjusted': 'Adjusted',
  'configured': 'Configured',
  'customized': 'Customized',
  'personalized': 'Personalized',
  'tailored': 'Tailored',
  'adapted': 'Adapted',
  'converted': 'Converted',
  'transformed': 'Transformed',
  'evolved': 'Evolved',
  'developed': 'Developed',
  'built': 'Built',
  'created_status': 'Created',
  'generated': 'Generated',
  'produced': 'Produced',
  'made': 'Made',
  'crafted': 'Crafted',
  'designed': 'Designed',
  'engineered': 'Engineered',
  'architected': 'Architected',
  'constructed': 'Constructed',
  'assembled': 'Assembled',
  'compiled': 'Compiled',
  'processed': 'Processed',
  'handled': 'Handled',
  'managed': 'Managed',
  'administered': 'Administered',
  'moderated': 'Moderated',
  'governed': 'Governed',
  'controlled': 'Controlled',
  'regulated': 'Regulated',
  'monitored': 'Monitored',
  'tracked': 'Tracked',
  'followed': 'Followed',
  'watched': 'Watched',
  'observed': 'Observed',
  'witnessed': 'Witnessed',
  'seen': 'Seen',
  'viewed': 'Viewed',
  'visited': 'Visited',
  'accessed': 'Accessed',
  'entered': 'Entered',
  'exited': 'Exited',
  'left_place': 'Left',
  'arrived': 'Arrived',
  'departed': 'Departed',
  'traveled': 'Traveled',
  'moved_to': 'Moved',
  'transferred': 'Transferred',
  'shifted': 'Shifted',
  'switched': 'Switched',
  'toggled': 'Toggled',
  'selected_status': 'Selected',
  'deselected': 'Deselected',
  'checked': 'Checked',
  'unchecked': 'Unchecked',
  'marked': 'Marked',
  'unmarked': 'Unmarked',
  'flagged': 'Flagged',
  'unflagged': 'Unflagged',
  'starred': 'Starred',
  'unstarred': 'Unstarred',
  'favorited': 'Favorited',
  'unfavorited': 'Unfavorited',
  'liked': 'Liked',
  'unliked': 'Unliked',
  'loved': 'Loved',
  'unloved': 'Unloved',
  'followed_user': 'Followed',
  'unfollowed': 'Unfollowed',
  'subscribed_to': 'Subscribed',
  'unsubscribed_from': 'Unsubscribed',
  'bookmarked': 'Bookmarked',
  'unbookmarked': 'Unbookmarked',
  'saved_for_later_status': 'Saved',
  'pinned': 'Pinned',
  'unpinned': 'Unpinned',
  'archived_status': 'Archived',
  'unarchived': 'Unarchived',
  'trashed': 'Trashed',
  'untrashed': 'Untrashed',
  'recycled': 'Recycled',
  'unrecycled': 'Unrecycled',
  'deleted_status': 'Deleted',
  'undone': 'Undone',
  'redone': 'Redone',
  'reverted': 'Reverted',
  'restored_status': 'Restored',
  'recovered': 'Recovered',
  'backed_up': 'Backed Up',
  'restored_from_backup': 'Restored',
  'exported_status': 'Exported',
  'imported': 'Imported',
  'migrated': 'Migrated',
  'cloned': 'Cloned',
  'duplicated': 'Duplicated',
  'copied_status': 'Copied',
  'pasted_status': 'Pasted',
  'cut': 'Cut',
  'linked': 'Linked',
  'unlinked': 'Unlinked',
  'attached': 'Attached',
  'detached': 'Detached',
  'connected_status': 'Connected',
  'disconnected_status': 'Disconnected',
  'merged': 'Merged',
  'split': 'Split',
  'separated': 'Separated',
  'combined': 'Combined',
  'joined_status': 'Joined',
  'united': 'United',
  'divided': 'Divided',
  'partitioned': 'Partitioned',
  'segmented': 'Segmented',
  'categorized': 'Categorized',
  'classified': 'Classified',
  'organized': 'Organized',
  'arranged': 'Arranged',
  'sorted_status': 'Sorted',
  'ordered': 'Ordered',
  'sequenced': 'Sequenced',
  'prioritized': 'Prioritized',
  'ranked': 'Ranked',
  'rated_status': 'Rated',
  'reviewed': 'Reviewed',
  'evaluated': 'Evaluated',
  'assessed': 'Assessed',
  'analyzed': 'Analyzed',
  'examined': 'Examined',
  'inspected': 'Inspected',
  'scanned': 'Scanned',
  'searched_status': 'Searched',
  'queried': 'Queried',
  'filtered_status': 'Filtered',
  'refined': 'Refined',
  'narrowed': 'Narrowed',
  'broadened': 'Broadened',
  'expanded': 'Expanded',
  'extended': 'Extended',
  'enlarged': 'Enlarged',
  'shrunk': 'Shrunk',
  'reduced': 'Reduced',
  'minimized': 'Minimized',
  'maximized': 'Maximized',
  'optimized_performance': 'Optimized',
  'tuned': 'Tuned',
  'calibrated': 'Calibrated',
  'balanced': 'Balanced',
  'equalized': 'Equalized',
  'normalized': 'Normalized',
  'standardized': 'Standardized',
  'formatted': 'Formatted',
  'styled': 'Styled',
  'themed': 'Themed',
  'branded': 'Branded',
  'colored': 'Colored',
  'sized': 'Sized',
  'shaped': 'Shaped',
  'positioned': 'Positioned',
  'aligned': 'Aligned',
  'centered': 'Centered',
  'justified': 'Justified',
  'distributed': 'Distributed',
  'spaced': 'Spaced',
  'padded': 'Padded',
  'margined': 'Margined',
  'bordered': 'Bordered',
  'outlined': 'Outlined',
  'shadowed': 'Shadowed',
  'highlighted': 'Highlighted',
  'emphasized': 'Emphasized',
  'accented': 'Accented',
  'underlined': 'Underlined',
  'strikethrough': 'Strikethrough',
  'bolded': 'Bolded',
  'italicized': 'Italicized',
  'capitalized': 'Capitalized',
  'uppercase': 'Uppercase',
  'lowercase': 'Lowercase',
  'title_case': 'Title Case',
  'sentence_case': 'Sentence Case',
  'camel_case': 'CamelCase',
  'snake_case': 'snake_case',
  'kebab_case': 'kebab-case',
  'pascal_case': 'PascalCase',
  'constant_case': 'CONSTANT_CASE',
  'dot_notation': 'Dot.Notation',
  'path_notation': 'Path/Notation',
  'namespace_notation': 'Namespace::Notation',
  'fully_qualified': 'Fully.Qualified.Name',
  'relative': 'Relative',
  'absolute': 'Absolute',
  'normalized_path': 'Normalized',
  'resolved': 'Resolved',
  'unresolved': 'Unresolved',
  'pending_resolution': 'Pending',
  'cached': 'Cached',
  'uncached': 'Uncached',
  'stale': 'Stale',
  'fresh': 'Fresh',
  'expired': 'Expired',
  'valid': 'Valid',
  'invalid': 'Invalid',
  'correct': 'Correct',
  'incorrect': 'Incorrect',
  'accurate': 'Accurate',
  'inaccurate': 'Inaccurate',
  'precise': 'Precise',
  'imprecise': 'Imprecise',
  'exact': 'Exact',
  'approximate': 'Approximate',
  'rough': 'Rough',
  'smooth': 'Smooth',
  'coarse': 'Coarse',
  'fine': 'Fine',
  'detailed': 'Detailed',
  'summary_level': 'Summary',
  'overview': 'Overview',
  'introduction': 'Introduction',
  'conclusion': 'Conclusion',
  'preface': 'Preface',
  'foreword': 'Foreword',
  'afterword': 'Afterword',
  'appendix': 'Appendix',
  'glossary': 'Glossary',
  'index': 'Index',
  'bibliography': 'Bibliography',
  'references_section': 'References',
  'citations': 'Citations',
  'footnotes': 'Footnotes',
  'endnotes': 'Endnotes',
  'annotations': 'Annotations',
  'comments_section': 'Comments',
  'notes_section': 'Notes',
  'remarks': 'Remarks',
  'observations_section': 'Observations',
  'findings': 'Findings',
  'results_section': 'Results',
  'outcomes': 'Outcomes',
  'outputs': 'Outputs',
  'deliverables': 'Deliverables',
  'milestones': 'Milestones',
  'achievements_section': 'Achievements',
  'accomplishments': 'Accomplishments',
  'successes': 'Successes',
  'failures': 'Failures',
  'errors_section': 'Errors',
  'issues_section': 'Issues',
  'problems_section': 'Problems',
  'concerns': 'Concerns',
  'risks': 'Risks',
  'threats': 'Threats',
  'opportunities': 'Opportunities',
  'strengths': 'Strengths',
  'weaknesses': 'Weaknesses',
  'advantages': 'Advantages',
  'disadvantages': 'Disadvantages',
  'benefits_section': 'Benefits',
  'drawbacks': 'Drawbacks',
  'pros': 'Pros',
  'cons': 'Cons',
  'features_section': 'Features',
  'functions_section': 'Functions',
  'capabilities': 'Capabilities',
  'limitations': 'Limitations',
  'restrictions_section': 'Restrictions',
  'constraints': 'Constraints',
  'requirements_section': 'Requirements',
  'prerequisites': 'Prerequisites',
  'dependencies': 'Dependencies',
  'dependents': 'Dependents',
  'children': 'Children',
  'parents': 'Parents',
  'siblings': 'Siblings',
  'ancestors': 'Ancestors',
  'descendants': 'Descendants',
  'roots': 'Roots',
  'leaves': 'Leaves',
  'branches': 'Branches',
  'nodes': 'Nodes',
  'edges': 'Edges',
  'vertices': 'Vertices',
  'faces': 'Faces',
  'surfaces': 'Surfaces',
  'volumes': 'Volumes',
  'dimensions': 'Dimensions',
  'measurements': 'Measurements',
  'metrics': 'Metrics',
  'indicators': 'Indicators',
  'statistics': 'Statistics',
  'analytics_section': 'Analytics',
  'insights_section': 'Insights',
  'intelligence_section': 'Intelligence',
  'knowledge': 'Knowledge',
  'wisdom': 'Wisdom',
  'understanding': 'Understanding',
  'comprehension': 'Comprehension',
  'awareness': 'Awareness',
  'consciousness': 'Consciousness',
  'perception': 'Perception',
  'perspective': 'Perspective',
  'viewpoint': 'Viewpoint',
  'standpoint': 'Standpoint',
  'angle': 'Angle',
  'aspect': 'Aspect',
  'facet': 'Facet',
  'dimension_facet': 'Dimension',
  'layer': 'Layer',
  'level': 'Level',
  'tier': 'Tier',
  'grade': 'Grade',
  'class_category': 'Class',
  'category_label': 'Category',
  'type': 'Type',
  'sort_label': 'Sort',
  'variety': 'Variety',
  'species': 'Species',
  'genus': 'Genus',
  'family': 'Family',
  'order_category': 'Order',
  'phylum': 'Phylum',
  'kingdom': 'Kingdom',
  'domain': 'Domain',
  'realm': 'Realm',
  'universe': 'Universe',
  'world': 'World',
  'globe': 'Globe',
  'planet': 'Planet',
  'earth': 'Earth',
  'nature': 'Nature',
  'environment': 'Environment',
  'ecosystem': 'Ecosystem',
  'habitat': 'Habitat',
  'biosphere': 'Biosphere',
  'atmosphere': 'Atmosphere',
  'climate': 'Climate',
  'weather': 'Weather',
  'season': 'Season',
  'spring': 'Spring',
  'summer': 'Summer',
  'autumn': 'Autumn',
  'fall': 'Fall',
  'winter': 'Winter',
  'morning': 'Morning',
  'afternoon': 'Afternoon',
  'evening': 'Evening',
  'night': 'Night',
  'midnight': 'Midnight',
  'noon': 'Noon',
  'dawn': 'Dawn',
  'dusk': 'Dusk',
  'sunrise': 'Sunrise',
  'sunset': 'Sunset',
  'daytime': 'Daytime',
  'nighttime': 'Nighttime',
  'daylight': 'Daylight',
  'moonlight': 'Moonlight',
  'sunlight': 'Sunlight',
  'starlight': 'Starlight',
  'firelight': 'Firelight',
  'candlelight': 'Candlelight',
  'lamplight': 'Lamplight',
  'electricity': 'Electricity',
  'power': 'Power',
  'energy': 'Energy',
  'force': 'Force',
  'strength_power': 'Strength',
  'might': 'Might',
  'ability': 'Ability',
  'skill': 'Skill',
  'talent': 'Talent',
  'gift': 'Gift',
  'potential': 'Potential',
  'capacity': 'Capacity',
  'capability_ability': 'Capability',
  'competence': 'Competence',
  'proficiency': 'Proficiency',
  'expertise': 'Expertise',
  'mastery': 'Mastery',
  'command': 'Command',
  'control_power': 'Control',
  'dominance': 'Dominance',
  'superiority': 'Superiority',
  'inferiority': 'Inferiority',
  'equality': 'Equality',
  'equivalence': 'Equivalence',
  'parity': 'Parity',
  'imbalance': 'Imbalance',
  'balance_power': 'Balance',
  'stability': 'Stability',
  'instability': 'Instability',
  'security': 'Security',
  'insecurity': 'Insecurity',
  'safety': 'Safety',
  'danger': 'Danger',
  'risk_hazard': 'Risk',
  'hazard': 'Hazard',
  'threat_danger': 'Threat',
  'menace': 'Menace',
  'peril': 'Peril',
  'jeopardy': 'Jeopardy',
  'exposure': 'Exposure',
  'vulnerability': 'Vulnerability',
  'weakness_vuln': 'Weakness',
  'fragility': 'Fragility',
  'brittleness': 'Brittleness',
  'flexibility': 'Flexibility',
  'adaptability': 'Adaptability',
  'utility': 'Utility',
  'usefulness': 'Usefulness',
  'purpose': 'Purpose',
  'meaning': 'Meaning',
  'significance': 'Significance',
  'importance': 'Importance',
  'relevance': 'Relevance',
  'priority_level': 'Priority',
  'urgency': 'Urgency',
  'emergency': 'Emergency',
  'crisis': 'Crisis',
  'critical': 'Critical',
  'serious': 'Serious',
  'severe': 'Severe',
  'mild': 'Mild',
  'moderate': 'Moderate',
  'extreme': 'Extreme',
  'intense': 'Intense',
  'faint': 'Faint',
  'strong': 'Strong',
  'weak_strength': 'Weak',
  'powerful': 'Powerful',
  'powerless': 'Powerless',
  'potent': 'Potent',
  'impotent': 'Impotent',
  'effective': 'Effective',
  'ineffective': 'Ineffective',
  'efficient': 'Efficient',
  'inefficient': 'Inefficient',
  'productive': 'Productive',
  'unproductive': 'Unproductive',
  'fruitful': 'Fruitful',
  'fruitless': 'Fruitless',
  'successful_outcome': 'Successful',
  'unsuccessful': 'Unsuccessful',
  'victorious': 'Victorious',
  'defeated': 'Defeated',
  'triumphant': 'Triumphant',
  'conquered': 'Conquered',
  'liberated': 'Liberated',
  'freed': 'Freed',
  'emancipated': 'Emancipated',
  'enslaved': 'Enslaved',
  'oppressed': 'Oppressed',
  'repressed': 'Repressed',
  'suppressed': 'Suppressed',
  'compressed': 'Compressed',
  'decompressed': 'Decompressed',
  'expanded_volume': 'Expanded',
  'contracted': 'Contracted',
  'stretched': 'Stretched',
  'compressed_size': 'Compressed',
  'deflated': 'Deflated',
  'inflated': 'Inflated',
  'swollen': 'Swollen',
  'shrunken': 'Shrunken',
  'grown': 'Grown',
  'developed_growth': 'Developed',
  'matured': 'Matured',
  'ripened': 'Ripened',
  'aged': 'Aged',
  'young': 'Young',
  'old': 'Old',
  'new_condition': 'New',
  'ancient': 'Ancient',
  'modern': 'Modern',
  'contemporary': 'Contemporary',
  'current': 'Current',
  'present': 'Present',
  'past': 'Past',
  'future': 'Future',
  'upcoming': 'Upcoming',
  'ongoing': 'Ongoing',
  'previous': 'Previous',
  'next_item': 'Next',
  'following': 'Following',
  'preceding': 'Preceding',
  'prior': 'Prior',
  'subsequent': 'Subsequent',
  'consequent': 'Consequent',
  'resulting': 'Resulting',
  'ensuing': 'Ensuing',
  'result': 'Result',
  'outcome_result': 'Outcome',
  'consequence': 'Consequence',
  'effect': 'Effect',
  'aftereffect': 'Aftereffect',
  'aftermath': 'Aftermath',
  'repercussion': 'Repercussion',
  'ramification': 'Ramification',
  'implication': 'Implication',
  'inference': 'Inference',
  'deduction': 'Deduction',
  'conclusion_thought': 'Conclusion',
  'determination': 'Determination',
  'decision': 'Decision',
  'resolution': 'Resolution',
  'solution': 'Solution',
  'answer': 'Answer',
  'response': 'Response',
  'reply': 'Reply',
  'reaction': 'Reaction',
  'feedback': 'Feedback',
  'criticism': 'Criticism',
  'praise': 'Praise',
  'compliment': 'Compliment',
  'insult': 'Insult',
  'offense': 'Offense',
  'defense': 'Defense',
  'protection': 'Protection',
  'guard': 'Guard',
  'shield': 'Shield',
  'shelter': 'Shelter',
  'refuge': 'Refuge',
  'haven': 'Haven',
  'sanctuary': 'Sanctuary',
  'asylum': 'Asylum',
  'retreat': 'Retreat',
  'resort': 'Resort',
  'destination': 'Destination',
  'target_goal': 'Target',
  'goal': 'Goal',
  'aim': 'Aim',
  'objective': 'Objective',
  'mission': 'Mission',
  'vision': 'Vision',
  'ambition': 'Ambition',
  'aspiration': 'Aspiration',
  'dream': 'Dream',
  'hope': 'Hope',
  'wish': 'Wish',
  'desire': 'Desire',
  'want': 'Want',
  'need': 'Need',
  'necessity': 'Necessity',
  'requirement_need': 'Requirement',
  'demand': 'Demand',
  'supply': 'Supply',
  'provision': 'Provision',
  'resource': 'Resource',
  'asset': 'Asset',
  'property': 'Property',
  'possession': 'Possession',
  'belonging': 'Belonging',
  'ownership': 'Ownership',
  'title': 'Title',
  'right': 'Right',
  'privilege': 'Privilege',
  'permission': 'Permission',
  'authorization': 'Authorization',
  'consent': 'Consent',
  'approval_consent': 'Approval',
  'agreement': 'Agreement',
  'contract': 'Contract',
  'deal': 'Deal',
  'bargain': 'Bargain',
  'negotiation': 'Negotiation',
  'settlement': 'Settlement',
  'arrangement_agreement': 'Arrangement',
  'understanding_agreement': 'Understanding',
  'pact': 'Pact',
  'treaty': 'Treaty',
  'alliance': 'Alliance',
  'coalition': 'Coalition',
  'partnership': 'Partnership',
  'collaboration': 'Collaboration',
  'cooperation': 'Cooperation',
  'coordination': 'Coordination',
  'communication': 'Communication',
  'connection_communication': 'Connection',
  'relation': 'Relation',
  'relationship': 'Relationship',
  'association': 'Association',
  'affiliation': 'Affiliation',
  'membership': 'Membership',
  'belonging_membership': 'Belonging',
  'inclusion': 'Inclusion',
  'exclusion_membership': 'Exclusion',
  'isolation': 'Isolation',
  'separation': 'Separation',
  'division': 'Division',
  'union': 'Union',
  'unity': 'Unity',
  'harmony': 'Harmony',
  'peace': 'Peace',
  'conflict': 'Conflict',
  'war': 'War',
  'battle': 'Battle',
  'fight': 'Fight',
  'struggle': 'Struggle',
  'effort': 'Effort',
  'attempt': 'Attempt',
  'endeavor': 'Endeavor',
  'venture': 'Venture',
  'enterprise': 'Enterprise',
  'undertaking': 'Undertaking',
  'project': 'Project',
  'program': 'Program',
  'initiative': 'Initiative',
  'campaign': 'Campaign',
  'movement': 'Movement',
  'cause': 'Cause',
  'crusade': 'Crusade',
  'struggle_cause': 'Struggle',
  'fight_cause': 'Fight',
  'advocacy': 'Advocacy',
  'support_help': 'Support',
  'assistance': 'Assistance',
  'aid': 'Aid',
  'help': 'Help',
  'service': 'Service',
  'assistance_service': 'Assistance',
  'care': 'Care',
  'maintenance': 'Maintenance',
  'repair': 'Repair',
  'fix': 'Fix',
  'mend': 'Mend',
  'patch': 'Patch',
  'restore_repair': 'Restore',
  'refresh_btn': 'Refresh',
  'revive': 'Revive',
  'resurrect': 'Resurrect',
  'rebirth': 'Rebirth',
  'regeneration': 'Regeneration',
  'rejuvenation': 'Rejuvenation',
  'renewal': 'Renewal',
  'restoration': 'Restoration',
  'conservation': 'Conservation',
  'preservation': 'Preservation',
  'protection_conservation': 'Protection',
  'safeguarding': 'Safeguarding',
  'security_safeguarding': 'Security',
  'defense_security': 'Defense',
  'safety_security': 'Safety',
  'welfare': 'Welfare',
  'wellbeing': 'Wellbeing',
  'health': 'Health',
  'fitness': 'Fitness',
  'wellness': 'Wellness',
  'illness': 'Illness',
  'disease': 'Disease',
  'sickness': 'Sickness',
  'ailment': 'Ailment',
  'condition_health': 'Condition',
  'state': 'State',
  'status_state': 'Status',
  'situation': 'Situation',
  'circumstance': 'Circumstance',
  'context': 'Context',
  'background': 'Background',
  'environment_context': 'Environment',
  'setting': 'Setting',
  'scene': 'Scene',
  'stage': 'Stage',
  'platform': 'Platform',
  'foundation': 'Foundation',
  'ground': 'Ground',
  'earth_ground': 'Earth',
  'soil': 'Soil',
  'land': 'Land',
  'territory': 'Territory',
  'area': 'Area',
  'region': 'Region',
  'zone': 'Zone',
  'sector': 'Sector',
  'district': 'District',
  'neighborhood': 'Neighborhood',
  'community_area': 'Community',
  'locality': 'Locality',
  'location': 'Location',
  'place': 'Place',
  'spot': 'Spot',
  'site': 'Site',
  'position_location': 'Position',
  'point': 'Point',
  'spot_point': 'Spot',
  'mark': 'Mark',
  'sign': 'Sign',
  'signal': 'Signal',
  'symbol': 'Symbol',
  'icon': 'Icon',
  'image': 'Image',
  'picture': 'Picture',
  'photo': 'Photo',
  'photograph': 'Photograph',
  'snapshot': 'Snapshot',
  'screenshot': 'Screenshot',
  'capture': 'Capture',
  'recording': 'Recording',
  'video': 'Video',
  'film': 'Film',
  'movie': 'Movie',
  'clip': 'Clip',
  'segment': 'Segment',
  'scene_film': 'Scene',
  'shot': 'Shot',
  'take': 'Take',
  'frame': 'Frame',
  'border': 'Border',
  'edge': 'Edge',
  'limit': 'Limit',
  'boundary': 'Boundary',
  'frontier': 'Frontier',
  'perimeter': 'Perimeter',
  'circumference': 'Circumference',
  'diameter': 'Diameter',
  'radius': 'Radius',
  'arc': 'Arc',
  'curve': 'Curve',
  'line': 'Line',
  'straight': 'Straight',
  'crooked': 'Crooked',
  'bent': 'Bent',
  'twisted': 'Twisted',
  'curved': 'Curved',
  'wavy': 'Wavy',
  'jagged': 'Jagged',
  'serrated': 'Serrated',
  'smooth_edge': 'Smooth',
  'rough_edge': 'Rough',
  'even': 'Even',
  'uneven': 'Uneven',
  'flat': 'Flat',
  'level_flat': 'Level',
  'horizontal': 'Horizontal',
  'vertical': 'Vertical',
  'diagonal': 'Diagonal',
  'parallel': 'Parallel',
  'perpendicular': 'Perpendicular',
  'intersecting': 'Intersecting',
  'crossing': 'Crossing',
  'overlapping': 'Overlapping',
  'adjacent': 'Adjacent',
  'neighboring': 'Neighboring',
  'nearby': 'Nearby',
  'distant': 'Distant',
  'far': 'Far',
  'remote': 'Remote',
  'isolated_place': 'Isolated',
  'secluded': 'Secluded',
  'hidden_place': 'Hidden',
  'concealed': 'Concealed',
  'secret': 'Secret',
  'private_place': 'Private',
  'personal_place': 'Personal',
  'public_place': 'Public',
  'open': 'Open',
  'closed_place': 'Closed',
  'shut': 'Shut',
  'covered': 'Covered',
  'uncovered': 'Uncovered',
  'exposed': 'Exposed',
  'protected_place': 'Protected',
  'shielded': 'Shielded',
  'guarded_place': 'Guarded',
  'defended': 'Defended',
  'fortified': 'Fortified',
  'secured': 'Secured',
  'safe_place': 'Safe',
  'dangerous': 'Dangerous',
  'hazardous': 'Hazardous',
  'risky': 'Risky',
  'perilous': 'Perilous',
  'treacherous': 'Treacherous',
  'unstable': 'Unstable',
  'precarious': 'Precarious',
  'uncertain': 'Uncertain',
  'doubtful': 'Doubtful',
  'questionable': 'Questionable',
  'suspicious': 'Suspicious',
  'dubious': 'Dubious',
  'skeptical': 'Skeptical',
  'doubt': 'Doubt',
  'belief': 'Belief',
  'faith': 'Faith',
  'trust': 'Trust',
  'confidence': 'Confidence',
  'assurance': 'Assurance',
  'guarantee': 'Guarantee',
  'warranty': 'Warranty',
  'promise': 'Promise',
  'commitment': 'Commitment',
  'pledge': 'Pledge',
  'oath': 'Oath',
  'vow': 'Vow',
  'sworn': 'Sworn',
  'affirmed': 'Affirmed',
  'declared': 'Declared',
  'stated': 'Stated',
  'claimed': 'Claimed',
  'asserted': 'Asserted',
  'maintained': 'Maintained',
  'contended': 'Contended',
  'argued': 'Argued',
  'debated': 'Debated',
  'discussed': 'Discussed',
  'talked': 'Talked',
  'spoke': 'Spoke',
  'spoken': 'Spoken',
  'said': 'Said',
  'told': 'Told',
  'mentioned': 'Mentioned',
  'noted': 'Noted',
  'observed_statement': 'Observed',
  'remarked': 'Remarked',
  'commented': 'Commented',
  'added_statement': 'Added',
  'continued': 'Continued',
  'proceeded': 'Proceeded',
  'went_on': 'Went On',
  'carried_on': 'Carried On',
  'moved_on': 'Moved On',
  'progressed': 'Progressed',
  'developed_progressed': 'Developed',
  'evolved_progressed': 'Evolved',
  'improved_progressed': 'Improved',
  'enhanced_progressed': 'Enhanced',
  'upgraded_progressed': 'Upgraded',
  'refined_progressed': 'Refined',
  'polished': 'Polished',
  'perfected': 'Perfected',
  'completed_progressed': 'Completed',
  'finished_progressed': 'Finished',
  'concluded': 'Concluded',
  'ended': 'Ended',
  'terminated': 'Terminated',
  'ceased': 'Ceased',
  'stopped_progressed': 'Stopped',
  'halted': 'Halted',
  'paused_progressed': 'Paused',
  'interrupted': 'Interrupted',
  'disrupted': 'Disrupted',
  'disturbed': 'Disturbed',
  'bothered': 'Bothered',
  'annoyed': 'Annoyed',
  'irritated': 'Irritated',
  'frustrated': 'Frustrated',
  'aggravated': 'Aggravated',
  'exasperated': 'Exasperated',
  'infuriated': 'Infuriated',
  'enraged': 'Enraged',
  'angered': 'Angered',
  'mad': 'Mad',
  'crazy': 'Crazy',
  'insane': 'Insane',
  'lunatic': 'Lunatic',
  'psychotic': 'Psychotic',
  'deranged': 'Deranged',
  'unhinged': 'Unhinged',
  'unbalanced': 'Unbalanced',
  'stable': 'Stable',
  'steady': 'Steady',
  'consistent': 'Consistent',
  'reliable': 'Reliable',
  'dependable': 'Dependable',
  'trustworthy': 'Trustworthy',
  'honest': 'Honest',
  'truthful': 'Truthful',
  'sincere': 'Sincere',
  'genuine': 'Genuine',
  'authentic': 'Authentic',
  'real': 'Real',
  'actual': 'Actual',
  'true': 'True',
  'correct_true': 'Correct',
  'wrong': 'Wrong',
  'false': 'False',
  'fake': 'Fake',
  'fictitious': 'Fictitious',
  'fictional': 'Fictional',
  'imaginary': 'Imaginary',
  'imagined': 'Imagined',
  'fantasy': 'Fantasy',
  'dream_fantasy': 'Dream',
  'illusion': 'Illusion',
  'delusion': 'Delusion',
  'hallucination': 'Hallucination',
  'mirage': 'Mirage',
  'phantom': 'Phantom',
  'ghost': 'Ghost',
  'spirit': 'Spirit',
  'soul': 'Soul',
  'mind': 'Mind',
  'brain': 'Brain',
  'heart': 'Heart',
  'body': 'Body',
  'physical': 'Physical',
  'mental': 'Mental',
  'emotional': 'Emotional',
  'spiritual': 'Spiritual',
  'intellectual': 'Intellectual',
  'cognitive': 'Cognitive',
  'psychological': 'Psychological',
  'behavioral': 'Behavioral',
  'social': 'Social',
  'cultural': 'Cultural',
  'societal': 'Societal',
  'communal': 'Communal',
  'collective': 'Collective',
  'individual': 'Individual',
  'personal_individual': 'Personal',
  'subjective': 'Subjective',
  'neutral': 'Neutral',
  'impartial': 'Impartial',
  'unbiased': 'Unbiased',
  'biased': 'Biased',
  'prejudiced': 'Prejudiced',
  'opinionated': 'Opinionated',
  'judgmental': 'Judgmental',
  'critical_judgment': 'Critical',
  'analytical': 'Analytical',
  'logical': 'Logical',
  'rational': 'Rational',
  'reasonable': 'Reasonable',
  'sensible': 'Sensible',
  'practical': 'Practical',
  'pragmatic': 'Pragmatic',
  'realistic': 'Realistic',
  'idealistic': 'Idealistic',
  'optimistic': 'Optimistic',
  'pessimistic': 'Pessimistic',
  'cynical': 'Cynical',
  'skeptical_attitude': 'Skeptical',
  'doubtful_attitude': 'Doubtful',
  'uncertain_attitude': 'Uncertain',
  'confident_attitude': 'Confident',
  'assured': 'Assured',
  'positive': 'Positive',
  'negative': 'Negative',
  'optimistic_attitude': 'Optimistic',
  'hopeful': 'Hopeful',
  'encouraging': 'Encouraging',
  'discouraging': 'Discouraging',
  'disheartening': 'Disheartening',
  'depressing': 'Depressing',
  'uplifting': 'Uplifting',
  'inspiring': 'Inspiring',
  'motivating': 'Motivating',
  'demotivating': 'Demotivating',
  'frustrating': 'Frustrating',
  'satisfying': 'Satisfying',
  'fulfilling': 'Fulfilling',
  'rewarding': 'Rewarding',
  'worthwhile': 'Worthwhile',
  'valuable': 'Valuable',
  'precious': 'Precious',
  'priceless': 'Priceless',
  'irreplaceable': 'Irreplaceable',
  'unique': 'Unique',
  'special': 'Special',
  'exceptional': 'Exceptional',
  'extraordinary': 'Extraordinary',
  'remarkable': 'Remarkable',
  'outstanding': 'Outstanding',
  'excellent': 'Excellent',
  'superb': 'Superb',
  'magnificent': 'Magnificent',
  'wonderful': 'Wonderful',
  'marvelous': 'Marvelous',
  'fantastic': 'Fantastic',
  'incredible': 'Incredible',
  'amazing': 'Amazing',
  'astonishing': 'Astonishing',
  'astounding': 'Astounding',
  'stunning': 'Stunning',
  'impressive': 'Impressive',
  'inspiring_awe': 'Inspiring',
  'breathtaking': 'Breathtaking',
  'spectacular': 'Spectacular',
  'phenomenal': 'Phenomenal',
  'sensational': 'Sensational',
  'phenomenal_sensational': 'Phenomenal',
  'extraordinary_phenomenal': 'Extraordinary',
  'unbelievable': 'Unbelievable',
  'unthinkable': 'Unthinkable',
  'unimaginable': 'Unimaginable',
  'inconceivable': 'Inconceivable',
  'impossible': 'Impossible',
  'possible': 'Possible',
  'feasible': 'Feasible',
  'viable': 'Viable',
  'workable': 'Workable',
  'achievable': 'Achievable',
  'attainable': 'Attainable',
  'reachable': 'Reachable',
  'accessible': 'Accessible',
  'obtainable': 'Obtainable',
  'free_available': 'Free',
  'busy': 'Busy',
  'occupied': 'Occupied',
  'vacant': 'Vacant',
  'empty': 'Empty',
  'full': 'Full',
  'complete_full': 'Complete',
  'incomplete_full': 'Incomplete',
  'partial': 'Partial',
  'whole': 'Whole',
  'entire': 'Entire',
  'total_full': 'Total',
  'complete_whole': 'Complete',
  'intact': 'Intact',
  'broken': 'Broken',
  'damaged': 'Damaged',
  'destroyed': 'Destroyed',
  'ruined': 'Ruined',
  'wrecked': 'Wrecked',
  'demolished': 'Demolished',
  'shattered': 'Shattered',
  'crushed': 'Crushed',
  'smashed': 'Smashed',
  'cracked': 'Cracked',
  'chipped': 'Chipped',
  'scratched': 'Scratched',
  'marked_damage': 'Marked',
  'scarred': 'Scarred',
  'blemished': 'Blemished',
  'flawed': 'Flawed',
  'imperfect': 'Imperfect',
  'perfect': 'Perfect',
  'ideal': 'Ideal',
  'optimal': 'Optimal',
  'best': 'Best',
  'worst': 'Worst',
  'better': 'Better',
  'worse': 'Worse',
  'good': 'Good',
  'bad': 'Bad',
  'evil': 'Evil',
  'wicked': 'Wicked',
  'sinister': 'Sinister',
  'malevolent': 'Malevolent',
  'benevolent': 'Benevolent',
  'kind': 'Kind',
  'cruel': 'Cruel',
  'harsh': 'Harsh',
  'gentle': 'Gentle',
  'soft': 'Soft',
  'hard_texture': 'Hard',
  'firm': 'Firm',
  'solid': 'Solid',
  'liquid': 'Liquid',
  'gas': 'Gas',
  'plasma': 'Plasma',
  'matter': 'Matter',
  'material': 'Material',
  'substance': 'Substance',
  'stuff': 'Stuff',
  'mass': 'Mass',
  'weight': 'Weight',
  'light': 'Light',
  'heavy': 'Heavy',
  'dense': 'Dense',
  'sparse': 'Sparse',
  'thin': 'Thin',
  'thick': 'Thick',
  'narrow_width': 'Narrow',
  'wide': 'Wide',
  'broad': 'Broad',
  'expansive': 'Expansive',
  'extensive': 'Extensive',
  'comprehensive': 'Comprehensive',
  'inclusive': 'Inclusive',
  'exclusive': 'Exclusive',
  'selective': 'Selective',
  'discriminatory': 'Discriminatory',
  'fair': 'Fair',
  'unfair': 'Unfair',
  'just': 'Just',
  'unjust': 'Unjust',
  'equitable': 'Equitable',
  'inequitable': 'Inequitable',
  'biased_fairness': 'Biased',
  'prejudiced_fairness': 'Prejudiced',
  'discriminating': 'Discriminating',
  'judgmental_fairness': 'Judgmental',
  'opinionated_fairness': 'Opinionated',
  'open_minded': 'Open-Minded',
  'closed_minded': 'Closed-Minded',
  'narrow_minded': 'Narrow-Minded',
  'broad_minded': 'Broad-Minded',
  'liberal': 'Liberal',
  'conservative': 'Conservative',
  'progressive': 'Progressive',
  'traditional': 'Traditional',
  'conventional': 'Conventional',
  'unconventional': 'Unconventional',
  'orthodox': 'Orthodox',
  'unorthodox': 'Unorthodox',
  'standard_conventional': 'Standard',
  'nonstandard': 'Nonstandard',
  'normal': 'Normal',
  'abnormal': 'Abnormal',
  'typical': 'Typical',
  'atypical': 'Atypical',
  'regular': 'Regular',
  'irregular': 'Irregular',
  'usual': 'Usual',
  'unusual': 'Unusual',
  'common': 'Common',
  'uncommon': 'Uncommon',
  'rare': 'Rare',
  'scarce': 'Scarce',
  'plentiful': 'Plentiful',
  'abundant': 'Abundant',
  'ample': 'Ample',
  'sufficient': 'Sufficient',
  'insufficient': 'Insufficient',
  'adequate': 'Adequate',
  'inadequate': 'Inadequate',
  'enough': 'Enough',
  'plenty': 'Plenty',
  'lack': 'Lack',
  'shortage': 'Shortage',
  'deficit': 'Deficit',
  'excess': 'Excess',
  'surplus': 'Surplus',
  'overflow': 'Overflow',
  'flood': 'Flood',
  'deluge': 'Deluge',
  'torrent': 'Torrent',
  'stream': 'Stream',
  'flow': 'Flow',
  'current_flow': 'Current',
  'tide': 'Tide',
  'wave': 'Wave',
  'surge': 'Surge',
  'ripple': 'Ripple',
  'splash': 'Splash',
  'spray': 'Spray',
  'mist': 'Mist',
  'fog': 'Fog',
  'cloud': 'Cloud',
  'haze': 'Haze',
  'smog': 'Smog',
  'smoke': 'Smoke',
  'steam': 'Steam',
  'vapor': 'Vapor',
  'gas_state': 'Gas',
  'air': 'Air',
  'wind': 'Wind',
  'breeze': 'Breeze',
  'gale': 'Gale',
  'storm': 'Storm',
  'hurricane': 'Hurricane',
  'tornado': 'Tornado',
  'typhoon': 'Typhoon',
  'cyclone': 'Cyclone',
  'monsoon': 'Monsoon',
  'tempest': 'Tempest',
  'squall': 'Squall',
  'thunderstorm': 'Thunderstorm',
  'lightning': 'Lightning',
  'thunder': 'Thunder',
  'rain': 'Rain',
  'snow': 'Snow',
  'sleet': 'Sleet',
  'hail': 'Hail',
  'ice': 'Ice',
  'frost': 'Frost',
  'freeze': 'Freeze',
  'cold': 'Cold',
  'cool': 'Cool',
  'warm': 'Warm',
  'hot': 'Hot',
  'heat': 'Heat',
  'temperature': 'Temperature',
  'humidity': 'Humidity',
  'moisture': 'Moisture',
  'dryness': 'Dryness',
  'aridity': 'Aridity',
  'drought': 'Drought',
  'wetness': 'Wetness',
  'dampness': 'Dampness',
  'sogginess': 'Sogginess',
  'muddiness': 'Muddiness',
  'dirtiness': 'Dirtiness',
  'cleanliness': 'Cleanliness',
  'purity': 'Purity',
  'impurity': 'Impurity',
  'pollution': 'Pollution',
  'contamination': 'Contamination',
  'infection': 'Infection',
  'disease_condition': 'Disease',
  'illness_condition': 'Illness',
  'sickness_condition': 'Sickness',
  'ailment_condition': 'Ailment',
  'malady': 'Malady',
  'affliction': 'Affliction',
  'suffering': 'Suffering',
  'pain': 'Pain',
  'agony': 'Agony',
  'anguish': 'Anguish',
  'torment': 'Torment',
  'torture': 'Torture',
  'distress': 'Distress',
  'misery': 'Misery',
  'woe': 'Woe',
  'grief': 'Grief',
  'sorrow': 'Sorrow',
  'sadness': 'Sadness',
  'unhappiness': 'Unhappiness',
  'melancholy': 'Melancholy',
  'depression': 'Depression',
  'despair': 'Despair',
  'hopelessness': 'Hopelessness',
  'desperation': 'Desperation',
  'anxiety': 'Anxiety',
  'worry': 'Worry',
  'concern_emotion': 'Concern',
  'fear': 'Fear',
  'terror': 'Terror',
  'horror': 'Horror',
  'panic': 'Panic',
  'dread': 'Dread',
  'fright': 'Fright',
  'alarm': 'Alarm',
  'shock': 'Shock',
  'surprise': 'Surprise',
  'amazement': 'Amazement',
  'astonishment': 'Astonishment',
  'wonder': 'Wonder',
  'awe': 'Awe',
  'reverence': 'Reverence',
  'respect': 'Respect',
  'admiration': 'Admiration',
  'esteem': 'Esteem',
  'regard': 'Regard',
  'appreciation': 'Appreciation',
  'gratitude': 'Gratitude',
  'thankfulness': 'Thankfulness',
  'indebtedness': 'Indebtedness',
  'obligation': 'Obligation',
  'duty': 'Duty',
  'responsibility': 'Responsibility',
  'accountability': 'Accountability',
  'liability': 'Liability',
  'culpability': 'Culpability',
  'guilt': 'Guilt',
  'innocence': 'Innocence',
  'blame': 'Blame',
  'fault': 'Fault',
  'error_mistake': 'Error',
  'mistake': 'Mistake',
  'oversight': 'Oversight',
  'omission': 'Omission',
  'neglect': 'Neglect',
  'failure': 'Failure',
  'shortcoming': 'Shortcoming',
  'deficiency': 'Deficiency',
  'defect': 'Defect',
  'blemish_defect': 'Blemish',
  'imperfection_defect': 'Imperfection',
  'fault_defect': 'Fault',
  'flaw_defect': 'Flaw',
  'drawback_defect': 'Drawback',
  'disadvantage_defect': 'Disadvantage',
  'problem_defect': 'Problem',
  'issue_defect': 'Issue',
  'difficulty': 'Difficulty',
  'trouble': 'Trouble',
  'hardship': 'Hardship',
  'adversity': 'Adversity',
  'misfortune': 'Misfortune',
  'bad_luck': 'Bad Luck',
  'good_luck': 'Good Luck',
  'fortune': 'Fortune',
  'luck': 'Luck',
  'chance': 'Chance',
  'opportunity_luck': 'Opportunity',
  'possibility': 'Possibility',
  'probability': 'Probability',
  'likelihood': 'Likelihood',
  'odds': 'Odds',
  'risk_probability': 'Risk',
  'gamble': 'Gamble',
  'bet': 'Bet',
  'wager': 'Wager',
  'stake': 'Stake',
  'investment': 'Investment',
  'expenditure': 'Expenditure',
  'expense': 'Expense',
  'cost_price': 'Cost',
  'spending': 'Spending',
  'saving': 'Saving',
  'income': 'Income',
  'earnings': 'Earnings',
  'revenue': 'Revenue',
  'profit': 'Profit',
  'loss': 'Loss',
  'gain': 'Gain',
  'win': 'Win',
  'benefit_gain': 'Benefit',
  'advantage_gain': 'Advantage',
  'upper_hand': 'Upper Hand',
  'leverage': 'Leverage',
  'influence': 'Influence',
  'impact': 'Impact',
  'effect_impact': 'Effect',
  'consequence_impact': 'Consequence',
  'result_impact': 'Result',
  'outcome_impact': 'Outcome',
  'aftermath_impact': 'Aftermath',
  'repercussion_impact': 'Repercussion',
  'ramification_impact': 'Ramification',
  'implication_impact': 'Implication',
  'inference_impact': 'Inference',
  'deduction_impact': 'Deduction',
  'conclusion_impact': 'Conclusion',
  'determination_impact': 'Determination',
  'decision_impact': 'Decision',
  'resolution_impact': 'Resolution',
  'solution_impact': 'Solution',
  'answer_impact': 'Answer',
  'response_impact': 'Response',
  'reply_impact': 'Reply',
  'reaction_impact': 'Reaction',
  'feedback_impact': 'Feedback',
  'criticism_impact': 'Criticism',
  'praise_impact': 'Praise',
  'compliment_impact': 'Compliment',
  'insult_impact': 'Insult',
  'offense_impact': 'Offense',
  'defense_impact': 'Defense',
  'protection_impact': 'Protection',
  'guard_impact': 'Guard',
  'shield_impact': 'Shield',
  'shelter_impact': 'Shelter',
  'refuge_impact': 'Refuge',
  'haven_impact': 'Haven',
  'sanctuary_impact': 'Sanctuary',
  'asylum_impact': 'Asylum',
  'retreat_impact': 'Retreat',
  'resort_impact': 'Resort',
  'destination_impact': 'Destination',
  'target_impact': 'Target',
  'goal_impact': 'Goal',
  'aim_impact': 'Aim',
  'objective_impact': 'Objective',
  'mission_impact': 'Mission',
  'vision_impact': 'Vision',
  'ambition_impact': 'Ambition',
  'aspiration_impact': 'Aspiration',
  'dream_impact': 'Dream',
  'hope_impact': 'Hope',
  'wish_impact': 'Wish',
  'desire_impact': 'Desire',
  'want_impact': 'Want',
  'need_impact': 'Need',
  'necessity_impact': 'Necessity',
  'requirement_impact': 'Requirement',
  'demand_impact': 'Demand',
  'supply_impact': 'Supply',
  'provision_impact': 'Provision',
  'resource_impact': 'Resource',
  'asset_impact': 'Asset',
  'property_impact': 'Property',
  'possession_impact': 'Possession',
  'belonging_impact': 'Belonging',
  'ownership_impact': 'Ownership',
  'title_impact': 'Title',
  'right_impact': 'Right',
  'privilege_impact': 'Privilege',
  'permission_impact': 'Permission',
  'authorization_impact': 'Authorization',
  'consent_impact': 'Consent',
  'approval_impact': 'Approval',
  'agreement_impact': 'Agreement',
  'contract_impact': 'Contract',
  'deal_impact': 'Deal',
  'bargain_impact': 'Bargain',
  'negotiation_impact': 'Negotiation',
  'settlement_impact': 'Settlement',
  'arrangement_impact': 'Arrangement',
  'understanding_impact': 'Understanding',
  'pact_impact': 'Pact',
  'treaty_impact': 'Treaty',
  'alliance_impact': 'Alliance',
  'coalition_impact': 'Coalition',
  'partnership_impact': 'Partnership',
  'collaboration_impact': 'Collaboration',
  'cooperation_impact': 'Cooperation',
  'coordination_impact': 'Coordination',
  'communication_impact': 'Communication',
  'connection_impact': 'Connection',
  'relation_impact': 'Relation',
  'relationship_impact': 'Relationship',
  'association_impact': 'Association',
  'affiliation_impact': 'Affiliation',
  'membership_impact': 'Membership',
  'inclusion_impact': 'Inclusion',
  'exclusion_impact': 'Exclusion',
  'isolation_impact': 'Isolation',
  'separation_impact': 'Separation',
  'division_impact': 'Division',
  'union_impact': 'Union',
  'unity_impact': 'Unity',
  'harmony_impact': 'Harmony',
  'peace_impact': 'Peace',
  'conflict_impact': 'Conflict',
  'war_impact': 'War',
  'battle_impact': 'Battle',
  'fight_impact': 'Fight',
  'struggle_impact': 'Struggle',
  'effort_impact': 'Effort',
  'attempt_impact': 'Attempt',
  'endeavor_impact': 'Endeavor',
  'venture_impact': 'Venture',
  'enterprise_impact': 'Enterprise',
  'undertaking_impact': 'Undertaking',
  'project_impact': 'Project',
  'program_impact': 'Program',
  'initiative_impact': 'Initiative',
  'campaign_impact': 'Campaign',
  'movement_impact': 'Movement',
  'cause_impact': 'Cause',
  'crusade_impact': 'Crusade',
  'struggle_cause_impact': 'Struggle',
  'fight_cause_impact': 'Fight',
  'advocacy_impact': 'Advocacy',
  'support_impact': 'Support',
  'assistance_impact': 'Assistance',
  'aid_impact': 'Aid',
  'help_impact': 'Help',
  'service_impact': 'Service',
  'assistance_service_impact': 'Assistance',
  'care_impact': 'Care',
  'maintenance_impact': 'Maintenance',
  'repair_impact': 'Repair',
  'fix_impact': 'Fix',
  'mend_impact': 'Mend',
  'patch_impact': 'Patch',
  'restore_impact': 'Restore',
  'renew_impact': 'Renew',
  'refresh_impact': 'Refresh',
  'revive_impact': 'Revive',
  'resurrect_impact': 'Resurrect',
  'rebirth_impact': 'Rebirth',
  'regeneration_impact': 'Regeneration',
  'rejuvenation_impact': 'Rejuvenation',
  'renewal_impact': 'Renewal',
  'restoration_impact': 'Restoration',
  'conservation_impact': 'Conservation',
  'preservation_impact': 'Preservation',
  'protection_conservation_impact': 'Protection',
  'safeguarding_impact': 'Safeguarding',
  'security_safeguarding_impact': 'Security',
  'defense_security_impact': 'Defense',
  'safety_security_impact': 'Safety',
  'welfare_impact': 'Welfare',
  'wellbeing_impact': 'Wellbeing',
  'health_impact': 'Health',
  'fitness_impact': 'Fitness',
  'wellness_impact': 'Wellness',
  'illness_impact': 'Illness',
  'disease_impact': 'Disease',
  'sickness_impact': 'Sickness',
  'ailment_impact': 'Ailment',
  'condition_health_impact': 'Condition',
  'state_impact': 'State',
  'status_state_impact': 'Status',
  'situation_impact': 'Situation',
  'circumstance_impact': 'Circumstance',
  'context_impact': 'Context',
  'background_impact': 'Background',
  'environment_context_impact': 'Environment',
  'setting_impact': 'Setting',
  'scene_impact': 'Scene',
  'stage_impact': 'Stage',
  'platform_impact': 'Platform',
  'foundation_impact': 'Foundation',
  'ground_impact': 'Ground',
  'earth_ground_impact': 'Earth',
  'soil_impact': 'Soil',
  'land_impact': 'Land',
  'territory_impact': 'Territory',
  'area_impact': 'Area',
  'region_impact': 'Region',
  'zone_impact': 'Zone',
  'sector_impact': 'Sector',
  'district_impact': 'District',
  'neighborhood_impact': 'Neighborhood',
  'community_area_impact': 'Community',
  'locality_impact': 'Locality',
  'location_impact': 'Location',
  'place_impact': 'Place',
  'spot_impact': 'Spot',
  'site_impact': 'Site',
  'position_location_impact': 'Position',
  'point_impact': 'Point',
  'spot_point_impact': 'Spot',
  'mark_impact': 'Mark',
  'sign_impact': 'Sign',
  'signal_impact': 'Signal',
  'symbol_impact': 'Symbol',
  'icon_impact': 'Icon',
  'image_impact': 'Image',
  'picture_impact': 'Picture',
  'photo_impact': 'Photo',
  'photograph_impact': 'Photograph',
  'snapshot_impact': 'Snapshot',
  'screenshot_impact': 'Screenshot',
  'capture_impact': 'Capture',
  'recording_impact': 'Recording',
  'video_impact': 'Video',
  'film_impact': 'Film',
  'movie_impact': 'Movie',
  'clip_impact': 'Clip',
  'segment_impact': 'Segment',
  'scene_film_impact': 'Scene',
  'shot_impact': 'Shot',
  'take_impact': 'Take',
  'frame_impact': 'Frame',
  'border_impact': 'Border',
  'edge_impact': 'Edge',
  'limit_impact': 'Limit',
  'boundary_impact': 'Boundary',
  'frontier_impact': 'Frontier',
  'perimeter_impact': 'Perimeter',
  'circumference_impact': 'Circumference',
  'diameter_impact': 'Diameter',
  'radius_impact': 'Radius',
  'arc_impact': 'Arc',
  'curve_impact': 'Curve',
  'line_impact': 'Line',
  'straight_impact': 'Straight',
  'crooked_impact': 'Crooked',
  'bent_impact': 'Bent',
  'twisted_impact': 'Twisted',
  'curved_impact': 'Curved',
  'wavy_impact': 'Wavy',
  'jagged_impact': 'Jagged',
  'serrated_impact': 'Serrated',
  'smooth_edge_impact': 'Smooth',
  'rough_edge_impact': 'Rough',
  'even_impact': 'Even',
  'uneven_impact': 'Uneven',
  'flat_impact': 'Flat',
  'level_flat_impact': 'Level',
  'horizontal_impact': 'Horizontal',
  'vertical_impact': 'Vertical',
  'diagonal_impact': 'Diagonal',
  'parallel_impact': 'Parallel',
  'perpendicular_impact': 'Perpendicular',
  'intersecting_impact': 'Intersecting',
  'crossing_impact': 'Crossing',
  'overlapping_impact': 'Overlapping',
  'adjacent_impact': 'Adjacent',
  'neighboring_impact': 'Neighboring',
  'nearby_impact': 'Nearby',
  'close_impact': 'Close',
  'distant_impact': 'Distant',
  'far_impact': 'Far',
  'remote_impact': 'Remote',
  'isolated_place_impact': 'Isolated',
  'secluded_impact': 'Secluded',
  'hidden_place_impact': 'Hidden',
  'concealed_impact': 'Concealed',
  'secret_impact': 'Secret',
  'private_place_impact': 'Private',
  'personal_place_impact': 'Personal',
  'public_place_impact': 'Public',
  'open_impact': 'Open',
  'closed_place_impact': 'Closed',
  'shut_impact': 'Shut',
  'covered_impact': 'Covered',
  'uncovered_impact': 'Uncovered',
  'exposed_impact': 'Exposed',
  'protected_place_impact': 'Protected',
  'shielded_impact': 'Shielded',
  'guarded_place_impact': 'Guarded',
  'defended_impact': 'Defended',
  'fortified_impact': 'Fortified',
  'secured_impact': 'Secured',
  'safe_place_impact': 'Safe',
  'dangerous_impact': 'Dangerous',
  'hazardous_impact': 'Hazardous',
  'risky_impact': 'Risky',
  'perilous_impact': 'Perilous',
  'treacherous_impact': 'Treacherous',
  'unstable_impact': 'Unstable',
  'precarious_impact': 'Precarious',
  'uncertain_impact': 'Uncertain',
  'doubtful_impact': 'Doubtful',
  'questionable_impact': 'Questionable',
  'suspicious_impact': 'Suspicious',
  'dubious_impact': 'Dubious',
  'skeptical_impact': 'Skeptical',
  'doubt_impact': 'Doubt',
  'belief_impact': 'Belief',
  'faith_impact': 'Faith',
  'trust_impact': 'Trust',
  'confidence_impact': 'Confidence',
  'assurance_impact': 'Assurance',
  'guarantee_impact': 'Guarantee',
  'warranty_impact': 'Warranty',
  'promise_impact': 'Promise',
  'commitment_impact': 'Commitment',
  'pledge_impact': 'Pledge',
  'oath_impact': 'Oath',
  'vow_impact': 'Vow',
  'sworn_impact': 'Sworn',
  'affirmed_impact': 'Affirmed',
  'declared_impact': 'Declared',
  'stated_impact': 'Stated',
  'claimed_impact': 'Claimed',
  'asserted_impact': 'Asserted',
  'maintained_impact': 'Maintained',
  'contended_impact': 'Contended',
  'argued_impact': 'Argued',
  'debated_impact': 'Debated',
  'discussed_impact': 'Discussed',
  'talked_impact': 'Talked',
  'spoke_impact': 'Spoke',
  'spoken_impact': 'Spoken',
  'said_impact': 'Said',
  'told_impact': 'Told',
  'mentioned_impact': 'Mentioned',
  'noted_impact': 'Noted',
  'observed_statement_impact': 'Observed',
  'remarked_impact': 'Remarked',
  'commented_impact': 'Commented',
  'added_statement_impact': 'Added',
  'continued_impact': 'Continued',
  'proceeded_impact': 'Proceeded',
  'went_on_impact': 'Went On',
  'carried_on_impact': 'Carried On',
  'moved_on_impact': 'Moved On',
  'advanced_impact': 'Advanced',
  'progressed_impact': 'Progressed',
  'developed_progressed_impact': 'Developed',
  'evolved_progressed_impact': 'Evolved',
  'improved_progressed_impact': 'Improved',
  'enhanced_progressed_impact': 'Enhanced',
  'upgraded_progressed_impact': 'Upgraded',
  'refined_progressed_impact': 'Refined',
  'polished_impact': 'Polished',
  'perfected_impact': 'Perfected',
  'completed_progressed_impact': 'Completed',
  'finished_progressed_impact': 'Finished',
  'concluded_impact': 'Concluded',
  'ended_impact': 'Ended',
  'terminated_impact': 'Terminated',
  'ceased_impact': 'Ceased',
  'stopped_progressed_impact': 'Stopped',
  'halted_impact': 'Halted',
  'paused_progressed_impact': 'Paused',
  'interrupted_impact': 'Interrupted',
  'disrupted_impact': 'Disrupted',
  'disturbed_impact': 'Disturbed',
  'bothered_impact': 'Bothered',
  'annoyed_impact': 'Annoyed',
  'irritated_impact': 'Irritated',
  'frustrated_impact': 'Frustrated',
  'aggravated_impact': 'Aggravated',
  'exasperated_impact': 'Exasperated',
  'infuriated_impact': 'Infuriated',
  'enraged_impact': 'Enraged',
  'angered_impact': 'Angered',
  'mad_impact': 'Mad',
  'crazy_impact': 'Crazy',
  'insane_impact': 'Insane',
  'lunatic_impact': 'Lunatic',
  'psychotic_impact': 'Psychotic',
  'deranged_impact': 'Deranged',
  'unhinged_impact': 'Unhinged',
  'unbalanced_impact': 'Unbalanced',
  'stable_impact': 'Stable',
  'steady_impact': 'Steady',
  'consistent_impact': 'Consistent',
  'reliable_impact': 'Reliable',
  'dependable_impact': 'Dependable',
  'trustworthy_impact': 'Trustworthy',
  'honest_impact': 'Honest',
  'truthful_impact': 'Truthful',
  'sincere_impact': 'Sincere',
  'genuine_impact': 'Genuine',
  'authentic_impact': 'Authentic',
  'real_impact': 'Real',
  'actual_impact': 'Actual',
  'true_impact': 'True',
  'correct_true_impact': 'Correct',
  'wrong_impact': 'Wrong',
  'false_impact': 'False',
  'fake_impact': 'Fake',
  'fictitious_impact': 'Fictitious',
  'fictional_impact': 'Fictional',
  'imaginary_impact': 'Imaginary',
  'imagined_impact': 'Imagined',
  'fantasy_impact': 'Fantasy',
  'dream_fantasy_impact': 'Dream',
  'illusion_impact': 'Illusion',
  'delusion_impact': 'Delusion',
  'hallucination_impact': 'Hallucination',
  'mirage_impact': 'Mirage',
  'phantom_impact': 'Phantom',
  'ghost_impact': 'Ghost',
  'spirit_impact': 'Spirit',
  'soul_impact': 'Soul',
  'mind_impact': 'Mind',
  'brain_impact': 'Brain',
  'heart_impact': 'Heart',
  'body_impact': 'Body',
  'physical_impact': 'Physical',
  'mental_impact': 'Mental',
  'emotional_impact': 'Emotional',
  'spiritual_impact': 'Spiritual',
  'intellectual_impact': 'Intellectual',
  'cognitive_impact': 'Cognitive',
  'psychological_impact': 'Psychological',
  'behavioral_impact': 'Behavioral',
  'social_impact': 'Social',
  'cultural_impact': 'Cultural',
  'societal_impact': 'Societal',
  'communal_impact': 'Communal',
  'collective_impact': 'Collective',
  'individual_impact': 'Individual',
  'personal_individual_impact': 'Personal',
  'subjective_impact': 'Subjective',
  'neutral_impact': 'Neutral',
  'impartial_impact': 'Impartial',
  'unbiased_impact': 'Unbiased',
  'biased_impact': 'Biased',
  'prejudiced_impact': 'Prejudiced',
  'opinionated_impact': 'Opinionated',
  'judgmental_impact': 'Judgmental',
  'critical_judgment_impact': 'Critical',
  'analytical_impact': 'Analytical',
  'logical_impact': 'Logical',
  'rational_impact': 'Rational',
  'reasonable_impact': 'Reasonable',
  'sensible_impact': 'Sensible',
  'practical_impact': 'Practical',
  'pragmatic_impact': 'Pragmatic',
  'realistic_impact': 'Realistic',
  'idealistic_impact': 'Idealistic',
  'optimistic_impact': 'Optimistic',
  'pessimistic_impact': 'Pessimistic',
  'cynical_impact': 'Cynical',
  'skeptical_attitude_impact': 'Skeptical',
  'doubtful_attitude_impact': 'Doubtful',
  'uncertain_attitude_impact': 'Uncertain',
  'confident_attitude_impact': 'Confident',
  'assured_impact': 'Assured',
  'positive_impact': 'Positive',
  'negative_impact': 'Negative',
  'optimistic_attitude_impact': 'Optimistic',
  'hopeful_impact': 'Hopeful',
  'encouraging_impact': 'Encouraging',
  'discouraging_impact': 'Discouraging',
  'disheartening_impact': 'Disheartening',
  'depressing_impact': 'Depressing',
  'uplifting_impact': 'Uplifting',
  'inspiring_impact': 'Inspiring',
  'motivating_impact': 'Motivating',
  'demotivating_impact': 'Demotivating',
  'frustrating_impact': 'Frustrating',
  'satisfying_impact': 'Satisfying',
  'fulfilling_impact': 'Fulfilling',
  'rewarding_impact': 'Rewarding',
  'worthwhile_impact': 'Worthwhile',
  'valuable_impact': 'Valuable',
  'precious_impact': 'Precious',
  'priceless_impact': 'Priceless',
  'irreplaceable_impact': 'Irreplaceable',
  'unique_impact': 'Unique',
  'special_impact': 'Special',
  'exceptional_impact': 'Exceptional',
  'extraordinary_impact': 'Extraordinary',
  'remarkable_impact': 'Remarkable',
  'outstanding_impact': 'Outstanding',
  'excellent_impact': 'Excellent',
  'superb_impact': 'Superb',
  'magnificent_impact': 'Magnificent',
  'wonderful_impact': 'Wonderful',
  'marvelous_impact': 'Marvelous',
  'fantastic_impact': 'Fantastic',
  'incredible_impact': 'Incredible',
  'amazing_impact': 'Amazing',
  'astonishing_impact': 'Astonishing',
  'astounding_impact': 'Astounding',
  'stunning_impact': 'Stunning',
  'impressive_impact': 'Impressive',
  'inspiring_awe_impact': 'Inspiring',
  'breathtaking_impact': 'Breathtaking',
  'spectacular_impact': 'Spectacular',
  'phenomenal_impact': 'Phenomenal',
  'sensational_impact': 'Sensational',
  'phenomenal_sensational_impact': 'Phenomenal',
  'extraordinary_phenomenal_impact': 'Extraordinary',
  'unbelievable_impact': 'Unbelievable',
  'unthinkable_impact': 'Unthinkable',
  'unimaginable_impact': 'Unimaginable',
  'inconceivable_impact': 'Inconceivable',
  'impossible_impact': 'Impossible',
  'possible_impact': 'Possible',
  'feasible_impact': 'Feasible',
  'viable_impact': 'Viable',
  'workable_impact': 'Workable',
  'achievable_impact': 'Achievable',
  'attainable_impact': 'Attainable',
  'reachable_impact': 'Reachable',
  'accessible_impact': 'Accessible',
  'obtainable_impact': 'Obtainable',
  'available_impact': 'Available',
  'unavailable_impact': 'Unavailable',
  'free_available_impact': 'Free',
  'busy_impact': 'Busy',
  'occupied_impact': 'Occupied',
  'vacant_impact': 'Vacant',
  'empty_impact': 'Empty',
  'full_impact': 'Full',
  'complete_full_impact': 'Complete',
  'incomplete_full_impact': 'Incomplete',
  'partial_impact': 'Partial',
  'whole_impact': 'Whole',
  'entire_impact': 'Entire',
  'total_full_impact': 'Total',
  'complete_whole_impact': 'Complete',
  'intact_impact': 'Intact',
  'broken_impact': 'Broken',
  'damaged_impact': 'Damaged',
  'destroyed_impact': 'Destroyed',
  'ruined_impact': 'Ruined',
  'wrecked_impact': 'Wrecked',
  'demolished_impact': 'Demolished',
  'shattered_impact': 'Shattered',
  'crushed_impact': 'Crushed',
  'smashed_impact': 'Smashed',
  'cracked_impact': 'Cracked',
  'chipped_impact': 'Chipped',
  'scratched_impact': 'Scratched',
  'marked_damage_impact': 'Marked',
  'scarred_impact': 'Scarred',
  'blemished_impact': 'Blemished',
  'flawed_impact': 'Flawed',
  'imperfect_impact': 'Imperfect',
  'perfect_impact': 'Perfect',
  'ideal_impact': 'Ideal',
  'optimal_impact': 'Optimal',
  'best_impact': 'Best',
  'worst_impact': 'Worst',
  'better_impact': 'Better',
  'worse_impact': 'Worse',
  'good_impact': 'Good',
  'bad_impact': 'Bad',
  'evil_impact': 'Evil',
  'wicked_impact': 'Wicked',
  'sinister_impact': 'Sinister',
  'malevolent_impact': 'Malevolent',
  'benevolent_impact': 'Benevolent',
  'kind_impact': 'Kind',
  'cruel_impact': 'Cruel',
  'harsh_impact': 'Harsh',
  'gentle_impact': 'Gentle',
  'soft_impact': 'Soft',
  'hard_texture_impact': 'Hard',
  'firm_impact': 'Firm',
  'solid_impact': 'Solid',
  'liquid_impact': 'Liquid',
  'gas_impact': 'Gas',
  'plasma_impact': 'Plasma',
  'matter_impact': 'Matter',
  'material_impact': 'Material',
  'substance_impact': 'Substance',
  'stuff_impact': 'Stuff',
  'mass_impact': 'Mass',
  'weight_impact': 'Weight',
  'light_impact': 'Light',
  'heavy_impact': 'Heavy',
  'dense_impact': 'Dense',
  'sparse_impact': 'Sparse',
  'thin_impact': 'Thin',
  'thick_impact': 'Thick',
  'narrow_width_impact': 'Narrow',
  'wide_impact': 'Wide',
  'broad_impact': 'Broad',
  'expansive_impact': 'Expansive',
  'extensive_impact': 'Extensive',
  'comprehensive_impact': 'Comprehensive',
  'inclusive_impact': 'Inclusive',
  'exclusive_impact': 'Exclusive',
  'selective_impact': 'Selective',
  'discriminatory_impact': 'Discriminatory',
  'fair_impact': 'Fair',
  'unfair_impact': 'Unfair',
  'just_impact': 'Just',
  'unjust_impact': 'Unjust',
  'equitable_impact': 'Equitable',
  'inequitable_impact': 'Inequitable',
  'biased_fairness_impact': 'Biased',
  'prejudiced_fairness_impact': 'Prejudiced',
  'discriminating_impact': 'Discriminating',
  'judgmental_fairness_impact': 'Judgmental',
  'opinionated_fairness_impact': 'Opinionated',
  'open_minded_impact': 'Open-Minded',
  'closed_minded_impact': 'Closed-Minded',
  'narrow_minded_impact': 'Narrow-Minded',
  'broad_minded_impact': 'Broad-Minded',
  'liberal_impact': 'Liberal',
  'conservative_impact': 'Conservative',
  'progressive_impact': 'Progressive',
  'traditional_impact': 'Traditional',
  'conventional_impact': 'Conventional',
  'unconventional_impact': 'Unconventional',
  'orthodox_impact': 'Orthodox',
  'unorthodox_impact': 'Unorthodox',
  'standard_conventional_impact': 'Standard',
  'nonstandard_impact': 'Nonstandard',
  'normal_impact': 'Normal',
  'abnormal_impact': 'Abnormal',
  'typical_impact': 'Typical',
  'atypical_impact': 'Atypical',
  'regular_impact': 'Regular',
  'irregular_impact': 'Irregular',
  'usual_impact': 'Usual',
  'unusual_impact': 'Unusual',
  'common_impact': 'Common',
  'uncommon_impact': 'Uncommon',
  'rare_impact': 'Rare',
  'scarce_impact': 'Scarce',
  'plentiful_impact': 'Plentiful',
  'abundant_impact': 'Abundant',
  'ample_impact': 'Ample',
  'sufficient_impact': 'Sufficient',
  'insufficient_impact': 'Insufficient',
  'adequate_impact': 'Adequate',
  'inadequate_impact': 'Inadequate',
  'enough_impact': 'Enough',
  'plenty_impact': 'Plenty',
  'lack_impact': 'Lack',
  'shortage_impact': 'Shortage',
  'deficit_impact': 'Deficit',
  'excess_impact': 'Excess',
  'surplus_impact': 'Surplus',
  'overflow_impact': 'Overflow',
  'flood_impact': 'Flood',
  'deluge_impact': 'Deluge',
  'torrent_impact': 'Torrent',
  'stream_impact': 'Stream',
  'flow_impact': 'Flow',
  'current_flow_impact': 'Current',
  'tide_impact': 'Tide',
  'wave_impact': 'Wave',
  'surge_impact': 'Surge',
  'ripple_impact': 'Ripple',
  'splash_impact': 'Splash',
  'spray_impact': 'Spray',
  'mist_impact': 'Mist',
  'fog_impact': 'Fog',
  'cloud_impact': 'Cloud',
  'haze_impact': 'Haze',
  'smog_impact': 'Smog',
  'smoke_impact': 'Smoke',
  'steam_impact': 'Steam',
  'vapor_impact': 'Vapor',
  'gas_state_impact': 'Gas',
  'air_impact': 'Air',
  'wind_impact': 'Wind',
  'breeze_impact': 'Breeze',
  'gale_impact': 'Gale',
  'storm_impact': 'Storm',
  'hurricane_impact': 'Hurricane',
  'tornado_impact': 'Tornado',
  'typhoon_impact': 'Typhoon',
  'cyclone_impact': 'Cyclone',
  'monsoon_impact': 'Monsoon',
  'tempest_impact': 'Tempest',
  'squall_impact': 'Squall',
  'thunderstorm_impact': 'Thunderstorm',
  'lightning_impact': 'Lightning',
  'thunder_impact': 'Thunder',
  'rain_impact': 'Rain',
  'snow_impact': 'Snow',
  'sleet_impact': 'Sleet',
  'hail_impact': 'Hail',
  'ice_impact': 'Ice',
  'frost_impact': 'Frost',
  'freeze_impact': 'Freeze',
  'cold_impact': 'Cold',
  'cool_impact': 'Cool',
  'warm_impact': 'Warm',
  'hot_impact': 'Hot',
  'heat_impact': 'Heat',
  'temperature_impact': 'Temperature',
  'humidity_impact': 'Humidity',
  'moisture_impact': 'Moisture',
  'dryness_impact': 'Dryness',
  'aridity_impact': 'Aridity',
  'drought_impact': 'Drought',
  'wetness_impact': 'Wetness',
  'dampness_impact': 'Dampness',
  'sogginess_impact': 'Sogginess',
  'muddiness_impact': 'Muddiness',
  'dirtiness_impact': 'Dirtiness',
  'cleanliness_impact': 'Cleanliness',
  'purity_impact': 'Purity',
  'impurity_impact': 'Impurity',
  'pollution_impact': 'Pollution',
  'contamination_impact': 'Contamination',
  'infection_impact': 'Infection',
  'disease_condition_impact': 'Disease',
  'illness_condition_impact': 'Illness',
  'sickness_condition_impact': 'Sickness',
  'ailment_condition_impact': 'Ailment',
  'malady_impact': 'Malady',
  'affliction_impact': 'Affliction',
  'suffering_impact': 'Suffering',
  'pain_impact': 'Pain',
  'agony_impact': 'Agony',
  'anguish_impact': 'Anguish',
  'torment_impact': 'Torment',
  'torture_impact': 'Torture',
  'distress_impact': 'Distress',
  'misery_impact': 'Misery',
  'woe_impact': 'Woe',
  'grief_impact': 'Grief',
  'sorrow_impact': 'Sorrow',
  'sadness_impact': 'Sadness',
  'unhappiness_impact': 'Unhappiness',
  'melancholy_impact': 'Melancholy',
  'depression_impact': 'Depression',
  'despair_impact': 'Despair',
  'hopelessness_impact': 'Hopelessness',
  'desperation_impact': 'Desperation',
  'anxiety_impact': 'Anxiety',
  'worry_impact': 'Worry',
  'concern_emotion_impact': 'Concern',
  'fear_impact': 'Fear',
  'terror_impact': 'Terror',
  'horror_impact': 'Horror',
  'panic_impact': 'Panic',
  'dread_impact': 'Dread',
  'fright_impact': 'Fright',
  'alarm_impact': 'Alarm',
  'shock_impact': 'Shock',
  'surprise_impact': 'Surprise',
  'amazement_impact': 'Amazement',
  'astonishment_impact': 'Astonishment',
  'wonder_impact': 'Wonder',
  'awe_impact': 'Awe',
  'reverence_impact': 'Reverence',
  'respect_impact': 'Respect',
  'admiration_impact': 'Admiration',
  'esteem_impact': 'Esteem',
  'regard_impact': 'Regard',
  'appreciation_impact': 'Appreciation',
  'gratitude_impact': 'Gratitude',
  'thankfulness_impact': 'Thankfulness',
  'indebtedness_impact': 'Indebtedness',
  'obligation_impact': 'Obligation',
  'duty_impact': 'Duty',
  'responsibility_impact': 'Responsibility',
  'accountability_impact': 'Accountability',
  'liability_impact': 'Liability',
  'culpability_impact': 'Culpability',
  'guilt_impact': 'Guilt',
  'innocence_impact': 'Innocence',
  'blame_impact': 'Blame',
  'fault_impact': 'Fault',
  'error_mistake_impact': 'Error',
  'mistake_impact': 'Mistake',
  'oversight_impact': 'Oversight',
  'omission_impact': 'Omission',
  'neglect_impact': 'Neglect',
  'failure_impact': 'Failure',
  'shortcoming_impact': 'Shortcoming',
  'deficiency_impact': 'Deficiency',
  'defect_impact': 'Defect',
  'blemish_defect_impact': 'Blemish',
  'imperfection_defect_impact': 'Imperfection',
  'fault_defect_impact': 'Fault',
  'flaw_defect_impact': 'Flaw',
  'drawback_defect_impact': 'Drawback',
  'disadvantage_defect_impact': 'Disadvantage',
  'problem_defect_impact': 'Problem',
  'issue_defect_impact': 'Issue',
  'difficulty_impact': 'Difficulty',
  'trouble_impact': 'Trouble',
  'hardship_impact': 'Hardship',
  'adversity_impact': 'Adversity',
  'misfortune_impact': 'Misfortune',
  'bad_luck_impact': 'Bad Luck',
  'good_luck_impact': 'Good Luck',
  'fortune_impact': 'Fortune',
  'luck_impact': 'Luck',
  'chance_impact': 'Chance',
  'opportunity_luck_impact': 'Opportunity',
  'possibility_impact': 'Possibility',
  'probability_impact': 'Probability',
  'likelihood_impact': 'Likelihood',
  'odds_impact': 'Odds',
  'risk_probability_impact': 'Risk',
  'gamble_impact': 'Gamble',
  'bet_impact': 'Bet',
  'wager_impact': 'Wager',
  'stake_impact': 'Stake',
  'investment_impact': 'Investment',
  'expenditure_impact': 'Expenditure',
  'expense_impact': 'Expense',
  'cost_price_impact': 'Cost',
  'spending_impact': 'Spending',
  'saving_impact': 'Saving',
  'income_impact': 'Income',
  'earnings_impact': 'Earnings',
  'revenue_impact': 'Revenue',
  'profit_impact': 'Profit',
  'loss_impact': 'Loss',
  'gain_impact': 'Gain',
  'win_impact': 'Win',
  'benefit_gain_impact': 'Benefit',
  'advantage_gain_impact': 'Advantage',
  'upper_hand_impact': 'Upper Hand',
  'leverage_impact': 'Leverage',
  'influence_impact': 'Influence',
  'impact_impact': 'Impact',
  'maximum_photos_allowed': 'Maximum photos allowed',
'failed_to_select_photo': 'Failed to select photo. Please try again.',
'ai_detected': 'AI detected',
'share_achievement': 'Share Achievement',
'search_achievements': 'Search Achievements',
'add_first_item': 'Add first item',
'could_not_generate_export': 'Could not generate export',
'export_error': 'Export error',
'take_a_photo': 'Take a photo',
'failed_to_save_preferences': 'Failed to save preferences. Please try again.',
'please_provide_rating': 'Please provide an overall rating',
'rating_saved_successfully': 'Rating saved successfully!',
'failed_to_save_rating': 'Failed to save rating',
'saving_your_rating': 'Saving your rating...',
'welcome_to_signature': 'Welcome to Signature!',
'purchases_restored': 'Purchases restored successfully!',
'key_learnings': 'Key Learnings',
'module_locked': 'Module Locked',
'about_learning_paths': 'About Learning Paths',
'how_it_works': 'How it works:',
'new_ai_insights_generated': 'New AI insights generated successfully!',
'send_message': 'Send message',
'feedback_sent': 'Thank you — your feedback has been sent',
'could_not_send_feedback': 'Could not send feedback',
'change_photo': 'Change Photo',
'profile_photo_updated': 'Profile photo updated',
'could_not_upload_photo': 'Could not upload photo. Check debug console for details.',
'profile_updated_successfully': 'Profile updated successfully',
'could_not_update_profile': 'Could not update profile',
'wear_this': 'Wear This',
'log_first_outfit': 'Log Your First Outfit',
'challenge_accepted': 'Challenge accepted! Good luck!',
'no_challenges_found': 'No challenges found',
'password_updated': 'Password updated successfully',
'could_not_update_password': 'Could not update password',
'update_password_btn': 'Update Password',
'morning_ai_suggestions': 'Morning AI suggestions',
'daily_outfit_ideas': 'Daily outfit ideas every morning',
'events': 'Events',
};
