/// Spanish translations for the Everywear app
const Map<String, String> appLocalizationsEs = {
  // App info
  'app_name': 'Everywear',
  'app_tagline': 'Entiende Tu Estilo',

  // Common UI
  'continue': 'Continuar',
  'cancel': 'Cancelar',
  'save': 'Guardar',
  'delete': 'Eliminar',
  'edit': 'Editar',
  'settings': 'Configuración',
  'profile': 'Perfil',
  'logout': 'Cerrar sesión',
  'back': 'Atrás',
  'next': 'Siguiente',
  'done': 'Hecho',
  'loading': 'Cargando...',
  'error': 'Error',
  'success': 'Éxito',
  'ok': 'OK',
  'yes': 'Sí',
  'no': 'No',
  'search': 'Buscar',
  'filter': 'Filtrar',
  'sort': 'Ordenar',
  'general': 'General',

  // Outfit History
  'outfit_history': 'Historial de atuendos',
  'view_history': 'Ver historial',
  'outfits_logged_tap_to_view': 'atuendos registrados — toca para ver',
  'no_outfits_logged_yet': 'No hay atuendos registrados',
  'start_logging_outfits': 'Comienza a registrar tus atuendos diarios para construir tu historial.',
  'sort_newest': 'Más reciente primero',
  'sort_oldest': 'Más antiguo primero',
  'sort_by_rating': 'Por calificación',
  'sort_by': 'Ordenar por',

  // Auth
  'welcome_back': 'Bienvenido de Nuevo',
  'create_account': 'Crear Cuenta',
  'email': 'Correo electrónico',
  'password': 'Contraseña',
  'full_name': 'Nombre completo',
  'sign_in': 'Iniciar Sesión',
  'sign_up': 'Registrarse',
  'continue_with_google': 'Continuar con Google',
  'continue_with_email': 'Continuar con Correo',
  'already_have_account': '¿Ya tienes una cuenta?',
  'dont_have_account': '¿No tienes una cuenta?',
  'forgot_password': '¿Olvidaste tu contraseña?',
  'or': 'O',
  'sign_in_subtitle': 'Inicia sesión para continuar tu viaje de estilo',
  'sign_up_subtitle': 'Regístrate para comenzar a rastrear tu guardarropa',
  'terms_agreement':
      'Al continuar, aceptas nuestros Términos de Servicio y Política de Privacidad',
  'email_required': 'El correo electrónico es requerido',
  'password_required': 'La contraseña es requerida',
  'name_required': 'El nombre es requerido',
  'invalid_email': 'Ingresa un correo válido',
  'password_too_short': 'La contraseña debe tener al menos 6 caracteres',

  // Settings
  'settings_and_profile': 'Configuración y Perfil',
  'account_settings': 'Configuración de cuenta',
  'app_preferences': 'Preferencias de la aplicación',
  'privacy_settings': 'Configuración de privacidad',
  'data_management': 'Gestión de datos',
  'subscription': 'Suscripción',
  'help_and_support': 'Ayuda y Soporte',
  'language': 'Idioma',
  'select_language': 'Seleccionar idioma',
  'theme': 'Tema',
  'notifications': 'Notificaciones',
  'change_password': 'Cambiar contraseña',
  'update_password': 'Actualiza tu contraseña',
  'two_factor_auth': 'Autenticación de dos factores',
  'email_preferences': 'Preferencias de correo',
  'manage_email_notifications': 'Gestionar notificaciones por correo',
  'enabled': 'Habilitado',
  'disabled': 'Deshabilitado',
  'data_sharing': 'Compartir datos',
  'share_usage_data': 'Compartir datos de uso para mejoras',
  'analytics': 'Analítica',
  'help_improve_app': 'Ayudar a mejorar la aplicación',
  'profile_visibility': 'Visibilidad del perfil',
  'manage_profile_visibility': 'Gestionar quién puede ver tu perfil',
  'export_data': 'Exportar datos',
  'download_wardrobe_data': 'Descargar tus datos de guardarropa',
  'backup_settings': 'Configuración de respaldo',
  'automatic_cloud_backup': 'Respaldo automático en la nube',
  'delete_account': 'Eliminar cuenta',
  'permanently_delete_account': 'Eliminar permanentemente tu cuenta',
  'current_plan': 'Plan actual',
  'billing_history': 'Historial de facturación',
  'view_past_invoices': 'Ver facturas anteriores',
  'upgrade_plan': 'Mejorar plan',
  'unlock_more_features': 'Desbloquear más funciones',
  'help_center': 'Centro de ayuda',
  'faqs_and_guides': 'Preguntas frecuentes y guías',
  'send_feedback': 'Enviar comentarios',
  'share_your_thoughts': 'Comparte tus pensamientos',
  'privacy_policy': 'Política de Privacidad',
  'view_privacy_policy': 'Ver nuestra política de privacidad',
  'terms_of_service': 'Términos de Servicio',
  'view_terms_of_service': 'Ver nuestros términos de servicio',
  'about': 'Acerca de',
  'version': 'Versión 1.0.0',
  'ai_model_management': 'Gestión del modelo IA',
  'manage_local_ai': 'Gestionar motor IA local',
  'manage_notifications': 'Gestionar preferencias de notificación',
  'light_mode': 'Modo Claro',
  'dark_mode': 'Modo Oscuro',
  'auto_system': 'Auto (Sistema)',

  // Wardrobe
  'wardrobe': 'Guardarropa',
  'add_item': 'Agregar artículo',
  'my_wardrobe': 'Mi guardarropa',
  'outfit': 'Atuendo',
  'outfits': 'Atuendos',
  'daily_log': 'Registro diario',
  'insights': 'Perspectivas',
  'your_style_profile': 'Tu Perfil de Estilo',
  'coachFallbackTip': 'Prueba combinar una prenda familiar con algo que uses con menos frecuencia esta semana.',

  // Language names
  'english': 'Inglés',
  'french': 'Francés',
  'spanish': 'Español',

  // Logout confirmation
  'logout_confirmation': '¿Estás seguro de que quieres cerrar sesión?',
  'delete_account_confirmation':
      '¿Estás seguro de que quieres eliminar permanentemente tu cuenta? Esta acción no se puede deshacer.',

  // Export options
  'export_data_format': 'Formato de exportación de datos',
  'pdf_report': 'Informe PDF',
  'comprehensive_wardrobe_report': 'Informe completo de guardarropa',
  'csv_spreadsheet': 'Hoja de cálculo CSV',
  'raw_data_analysis': 'Datos sin procesar para análisis',
  'exporting_data': 'Exportando datos como',

  // About app
  'about_everywear':
      'Everywear te ayuda a tomar decisiones conscientes sobre tu guardarropa a través de análisis y perspectivas.',
  'close': 'Cerrar',

  // AI & Smart Suggestions
  'ai_styling_assistant': 'Asistente de Estilo IA',
  'powered_by_ai': 'Potenciado por IA',
  'dismiss': 'Descartar',
  'smart_suggestions_title': 'Sugerencias Inteligentes',
  'refresh_suggestions': 'Actualizar sugerencias',
  'analyzing_wardrobe': 'La IA está analizando tu guardarropa...',
  'ai_banner_text': '{count} sugerencias potenciadas por IA basadas en tu guardarropa',
  'filter_by_occasion': 'Filtrar por ocasión',
  'outfit_added_to_log': 'Atuendo añadido al registro de hoy',
  'saved_for_later': 'Guardado para después',
  'removed_from_saved': 'Eliminado de guardados',
  'suggestion_dismissed': 'Sugerencia descartada - aprenderemos de esto',
  'undo': 'Deshacer',
  'items_in_this_outfit': 'Artículos en este atuendo',
  'last_worn_label': 'Visto por última vez',
  'styling_tips': 'Consejos de Estilo',

  // Camera
  'camera_flip_error': 'Error al girar la cámara. Por favor, inténtalo de nuevo.',
  'camera_capture_error': 'Error al capturar la foto. Por favor, inténtalo de nuevo.',

  // Filters
  'filter_all': 'Todo',
  'filter_work': 'Trabajo',
  'filter_casual': 'Casual',
  'filter_special': 'Especial',

  // Capture Flow
  'log_outfit': 'Registrar atuendo',
  'capture_outfit': 'Capturar',
  'select_from_wardrobe': 'Seleccionar del Guardarropa',
  'confirm_outfit': 'Confirmar Atuendo',
  'camera_permission_required': 'Se requiere permiso de la cámara para capturar atuendos',
  'camera_init_error': 'Error al inicializar la cámara. Por favor, inténtalo de nuevo.',
  'getting_ai_suggestions': 'Obteniendo sugerencias de IA...',
  'get_ai_tips': 'Obtener Consejos de IA',
  'gallery_pick_error': 'Error al seleccionar la imagen de la galería',
  'how_to_log_outfit': '¿Cómo te gustaría registrar tu atuendo?',
  'capture_method_subtitle': 'Elige tu método preferido para capturar rápidamente tu look de hoy',
  'take_photo': 'Tomar Foto',
  'take_photo_subtitle': 'Captura tu atuendo con la cámara',
  'build_from_wardrobe': 'Armar desde el Guardarropa',
  'build_from_wardrobe_subtitle': 'Selecciona artículos de tu guardarropa',
  'wear_this_today': 'Usar esto hoy',
  'save_for_later_btn': 'Guardar para después',
  'retake': 'Volver a tomar',
  'rate_outfit_error': 'Por favor, califica tu atuendo antes de guardar',
  'outfit_preview': 'Vista Previa del Atuendo',
  'outfit_logged_success': '¡Atuendo registrado con éxito!',
  'optional_notes_hint': 'Agrega algunas notas sobre este atuendo...',
  'no_image_captured': 'No se capturó ninguna imagen',
  'selected_items_count': 'Artículos Seleccionados ({count})',
  'outfit_name_optional': 'Nombre del Atuendo (Opcional)',
  'outfit_name_hint': 'ej: Viernes Casual, Noche de Cita',
  'feel_in_outfit_question': '¿Cómo te sentiste con este atuendo?',
  'rating_not_great': 'No me sentí bien',
  'rating_ok': 'Bien',
  'rating_loved_it': 'Me encantó',
  'save_outfit': 'Guardar Atuendo',
  'select_at_least_one_item': 'Por favor, selecciona al menos un artículo',
  'search_wardrobe_hint': 'Buscar artículos del guardarropa...',
  'no_items_found': 'No se encontraron artículos',
  'continue_with_item_singular': 'Continuar con {count} artículo',
  'continue_with_items_plural': 'Continuar con {count} artículos',
  'cost_per_wear': 'Costo por uso',
  'per_wear': '/uso',

  // Progress Dashborad
  'my_progress': 'Mi Progreso',
  'challenge_center': 'Centro de Desafíos',
  'challenge_center_subtitle': 'Explora y únete a nuevos desafíos de estilo.',
  'active_challenges': 'Desafíos Activos',
  'your_statistics': 'Tus Estadísticas',
  'view_all': 'Ver Todo',
  'day_streak': 'días seguidos',
  'progress_hero_title': 'Tu progreso está ganando impulso',
  'progress_hero_no_logs': 'Empieza a registrar atuendos para seguir tu camino.',
  'progress_hero_start': 'Registra tu primer atuendo para comenzar.',
  'progress_hero_default': 'Sigue construyendo tu historial de estilo.',
  'outfits_logged_so_far': 'atuendos registrados',
  'challenges_active': 'desafíos activos.',
  'motivation_start': 'Comienza tu racha hoy — registra tu primer atuendo.',
  'motivation_building': 'Buen comienzo — ¡sigue así!',
  'motivation_going': 'Estás construyendo buenos hábitos de estilo.',
  'motivation_strong': '¡Racha impresionante — estás en racha!',
  'no_active_challenges': 'No hay desafíos activos ahora',
  'no_active_challenges_hint': 'Visita el Centro de Desafíos para unirte a un objetivo.',
  'browse_challenges': 'Ver Desafíos',
  'wardrobe_items': 'Artículos Guardarropa',
  'total_spent': 'Total Gastado',
  'wardrobe_utilization': 'Artículos Usados',
  'purchases_this_month': 'Compras este Mes',

  // HELP CENTER
  'help_center_hero_title': 'Bienvenido al Centro de Ayuda de Everywear',
  'help_center_hero_subtitle': 'Una guía tranquila sobre cómo funciona la aplicación, para qué sirve cada espacio y cómo aprovechar al máximo tu viaje de armario.',
  'help_center_studio_intro': 'Everywear está diseñado como un estudio tranquilo para tu armario. Este espacio te ayuda a entender cómo funciona la aplicación, cómo hacer crecer tu estilo y cómo aprovechar al máximo tu ropa.',
  'help_center_philosophy_title': 'Nuestra Filosofía',
  'help_center_philosophy_heading': 'Everywear está diseñado como un espacio de armario personal y tranquilo.',
  'help_center_philosophy_body': 'El objetivo no es presionarte para comprar más o vestirte de cierta manera. El objetivo es ayudarte a ver tu armario más claramente, usarlo más intencionalmente y construir un estilo que se sienta tuyo.',
  'help_center_how_it_works_title': 'Cómo Funciona Everywear',
  'help_center_step1_title': 'Añade tu armario',
  'help_center_step1_desc': 'Comienza con algunas piezas que uses frecuentemente. No necesitas añadir todo de una vez.',
  'help_center_step2_title': 'Registra tus atuendos',
  'help_center_step2_desc': 'Sigue lo que realmente usas. Esto ayuda a la aplicación a entender tus hábitos y mejorar tus sugerencias.',
  'help_center_step3_title': 'Explora tus sugerencias diarias',
  'help_center_step3_desc': 'Usa la página Hoy para obtener ideas de atuendos basadas en tu estado de ánimo, planes y contexto de tu armario.',
  'help_center_step4_title': 'Haz crecer tu estilo con coaching',
  'help_center_step4_desc': 'Usa la página Estilo para descubrir desafíos, responder cuestionarios y obtener orientación más reflexiva con el tiempo.',
  'help_center_pro_tip': 'Consejo: Cuantos más atuendos registres, más personales se volverán tus sugerencias diarias e insights.',
  'help_center_pages_title': 'Qué hace cada página',
  'help_center_page_today_title': 'Hoy',
  'help_center_page_today_desc': 'Tu espacio diario para ideas de atuendos, registros rápidos y orientación matutina.',
  'help_center_page_wardrobe_title': 'Armario',
  'help_center_page_wardrobe_desc': 'Tu colección personal de ropa, organizada y lista para estilizar.',
  'help_center_page_style_title': 'Estilo',
  'help_center_page_style_desc': 'Tu área de coaching para cuestionarios, desafíos, eventos y crecimiento personal.',
  'help_center_page_purchases_title': 'Compras',
  'help_center_page_purchases_desc': 'Sigue tus gastos de armario, lista de deseos y el valor a largo plazo de lo que compras.',
  'help_center_page_profile_title': 'Perfil',
  'help_center_page_profile_desc': 'Consulta tus insights, logros, progreso, membresía y configuración.',
  'help_center_membership_title': 'Membresía',
  'help_center_essential_title': 'Esencial',
  'help_center_essential_desc': 'Una experiencia principal refinada con gestión de armario, uso diario y orientación IA seleccionada.',
  'help_center_signature_title': 'Signature',
  'help_center_signature_desc': 'Una experiencia más profunda con más sugerencias, más coaching, más posibilidades de atuendos y un viaje premium más fluido.',
  'help_center_faq_title': 'Preguntas Frecuentes',
  'help_center_need_help_title': '¿Necesitas más ayuda?',
  'help_center_need_help_body1': 'Si algo no funciona como esperabas, o si quieres compartir comentarios, usa la opción de retroalimentación en Configuración.',
  'help_center_need_help_body2': 'Everywear está diseñado para evolucionar de manera reflexiva, y tus comentarios ayudan a dar forma a ese proceso.',
  
  // FAQ Questions & Answers
  'faq_q1': '¿Qué es Everywear?',
  'faq_a1': 'Everywear es tu estudio de armario personal. Te ayuda a organizar tu ropa, obtener ideas de atuendos diarios, seguir tus hábitos de estilo y tomar decisiones de compra más reflexivas.',
  'faq_q2': '¿Cómo debería empezar a usar la aplicación?',
  'faq_a2': 'Comienza añadiendo algunas piezas clave de tu armario, luego registra atuendos a medida que los uses. Cuanto más uses la aplicación, más personales y precisos se volverán tus sugerencias, insights y coaching.',
  'faq_q3': '¿Qué hace la página Hoy?',
  'faq_a3': 'La página Hoy es tu espacio de estilismo diario. Te da una idea de atuendo basada en tu armario, tu estado de ánimo seleccionado, tus planes y detalles contextuales como el clima o eventos próximos.',
  'faq_q4': '¿Para qué sirve la página Estilo?',
  'faq_a4': 'La página Estilo es tu espacio de coaching. Está diseñada para la reflexión, desafíos, cuestionarios, crecimiento de estilo y orientación más personal más allá de la sugerencia diaria.',
  'faq_q5': '¿Qué son los Insights de Estilo?',
  'faq_a5': 'Los Insights de Estilo muestran patrones en cómo usas tu armario — como tus categorías más usadas, historial de atuendos, utilización del armario y valor a lo largo del tiempo. Te ayudan a entender tu estilo más claramente.',
  'faq_q6': '¿Cuál es la diferencia entre Esencial y Signature?',
  'faq_a6': 'Esencial te da acceso a la experiencia principal de Everywear. Signature desbloquea más sugerencias, más coaching, más opciones de atuendos y una experiencia premium más fluida con menos limitaciones.',
  'faq_q7': '¿La aplicación eliminará mi armario si cancelo Signature?',
  'faq_a7': 'No. Los datos de tu armario permanecen con tu cuenta. Si vuelves a Esencial, mantienes tus datos guardados, pero algunas funciones premium y límites de uso adicionales pueden no estar disponibles.',
  'faq_q8': '¿Cómo funcionan el seguimiento de compras y la lista de deseos?',
  'faq_a8': 'La página Compras te ayuda a registrar lo que entra en tu armario, monitorear gastos por categoría, seguir el costo por uso y guardar artículos en una lista de deseos antes de comprarlos.',
  'faq_q9': '¿Everywear vende mis datos personales?',
  'faq_a9': 'No. Los datos de tu armario y cuenta se usan para potenciar tu experiencia dentro de la aplicación. La configuración de analíticas te permite controlar si los datos de uso anónimos ayudan a mejorar la aplicación.',
  'faq_q10': '¿Cómo puedo obtener mejores sugerencias?',
  'faq_a10': 'Añade más artículos a tu armario, completa tu cuestionario de estilo, registra atuendos regularmente y usa las opciones de ocasión y ambiente. Esto da a la aplicación más contexto para producir sugerencias que se sientan más personales.',

  // SEND FEEDBACK
  'feedback_hero_title': 'Nos encantaría escucharte',
  'feedback_hero_subtitle': 'Tus ideas, reportes de errores y reflexiones ayudan a formar Everywear en un estudio de armario más reflexivo.',
  'feedback_type_section_title': '¿Qué te gustaría compartir?',
  'feedback_message_section_title': 'Tu mensaje',
  'feedback_experience_section_title': '¿Cómo va tu experiencia hasta ahora?',
  'feedback_email_section_title': 'Email de contacto',
  'feedback_note_section_title': 'Una nota rápida',
  
  // Feedback types
  'feedback_type_suggestion': 'Sugerencia',
  'feedback_type_bug': 'Error',
  'feedback_type_design': 'Diseño',
  'feedback_type_ai_suggestions': 'Sugerencias IA',
  'feedback_type_other': 'Otro',

  // RESET
  'reset_app': 'Restablecer la aplicación',
  'reset_app_subtitle': 'Borrar todos tus datos y empezar de nuevo',
  'reset_title': 'Restablecer datos',
  'reset_warning': 'Esto eliminará permanentemente todos tus datos. Esta acción no se puede deshacer.',
  'reset_keeps_account': 'Tu cuenta (correo y contraseña) se conservará. Solo se eliminan tus datos.',
  'reset_continue_btn': 'Continuar',
  'reset_confirm_title': '¿Estás seguro?',
  'reset_type_instruction': 'Escribe RESET abajo para confirmar que deseas borrar todo.',
  'reset_confirm_btn': 'Eliminar todo',
  'reset_in_progress': 'Restableciendo tus datos...',
  'reset_error': 'Error al restablecer',
  'reset_item_wardrobe': 'Todos los artículos del guardarropa',
  'reset_item_logs': 'Todos los registros de atuendos',
  'reset_item_purchases': 'Todas las compras y lista de deseos',
  'reset_item_challenges': 'Todos los desafíos y progreso',
  'reset_item_quiz': 'Resultados del quiz de estilo',
  'reset_item_events': 'Todos los eventos de estilo',
  
  // Form fields
  'feedback_message_hint': 'Cuéntanos qué pasó, qué mejorarías o qué te gustaría ver a continuación...',
  'feedback_message_required': 'Por favor escribe un mensaje',
  'feedback_message_too_short': 'Por favor añade un poco más de detalle',
  'feedback_rating_optional': 'Opcional, pero útil',
  'feedback_email_hint': 'tu@email.com',
  'feedback_email_invalid': 'Por favor ingresa un email válido',
  'feedback_note_text': 'Si reportas un error, algunos detalles como dónde ocurrió, qué esperabas y qué pasó en su lugar ayudarán mucho.',
  
  // Button states
  'feedback_sending': 'Enviando...',
  'feedback_success_message': 'Gracias — tu feedback ha sido enviado',
  'feedback_error_message': 'No se pudo enviar el feedback. Por favor intenta de nuevo.',

  // PRIVACY POLICY
  'privacy_title': 'Política de Privacidad de Everywear',
  'privacy_last_updated': 'Última actualización: 2026',
  'privacy_philosophy_title': 'Nuestra filosofía',
  'privacy_philosophy_content': 'Everywear fue diseñado como un estudio de armario tranquilo. Nuestro objetivo es ayudarte a redescubrir la ropa que ya posees y desarrollar tu estilo personal de manera intencional. Los datos de tu armario te pertenecen.',
  'privacy_collect_title': 'Información que recopilamos',
  'privacy_collect_content': 'Cuando creas una cuenta podemos recopilar:\n\n• Dirección de correo electrónico\n• Datos de autenticación\n• Información básica del dispositivo\n\nEsto nos permite proporcionar el servicio de forma segura.',
  'privacy_wardrobe_title': 'Datos del armario',
  'privacy_wardrobe_content': 'Everywear almacena la información que eliges añadir, como:\n\n• Artículos de ropa\n• Registro de atuendos\n• Imágenes del armario\n• Preferencias de estilo\n\nEstos datos se utilizan únicamente para proporcionar las funciones del armario.',
  'privacy_analytics_title': 'Análisis',
  'privacy_analytics_content': 'Se pueden recopilar datos de uso anónimos para entender cómo se utilizan las funciones y mejorar la aplicación.',
  'privacy_subscriptions_title': 'Suscripciones',
  'privacy_subscriptions_content': 'Las suscripciones Signature se procesan a través de Apple App Store o Google Play. Everywear nunca almacena información de pago.',
  'privacy_rights_title': 'Tus derechos',
  'privacy_rights_content': 'Puedes solicitar:\n\n• Eliminación de cuenta\n• Exportación de datos\n• Soporte respecto a tus datos',
  'privacy_contact_title': 'Contacto',
  'privacy_contact_content': 'Si tienes preguntas sobre privacidad, contacta:\n\nsupport@everywear.studio',
  
  // TERMS OF USE
  'terms_title': 'Términos de Everywear',
  'terms_use_title': 'Uso de la aplicación',
  'terms_use_content': 'Everywear proporciona herramientas para organizar armarios y seguir atuendos. Al usar la aplicación, aceptas usar el servicio de manera responsable.',
  'terms_accounts_title': 'Cuentas',
  'terms_accounts_content': 'Eres responsable de mantener la confidencialidad de tus credenciales de cuenta.',
  'terms_tiers_title': 'Esencial & Signature',
  'terms_tiers_content': 'Everywear ofrece dos niveles:\n\nEsencial — acceso gratuito a las herramientas básicas del armario.\n\nSignature — acceso premium a insights avanzados, análisis y sugerencias de atuendos mejoradas.',
  'terms_subscriptions_title': 'Suscripciones',
  'terms_subscriptions_content': 'Las suscripciones se renuevan automáticamente a menos que se cancelen a través de tu cuenta de App Store o Google Play.',
  'terms_cancellation_title': 'Cancelación',
  'terms_cancellation_content': 'Puedes cancelar tu suscripción en cualquier momento a través de la configuración de tu cuenta de store.',
  'terms_user_content_title': 'Contenido del usuario',
  'terms_user_content_content': 'Mantienes la propiedad de las fotos y datos del armario que subes. Everywear almacena estos datos solo para proporcionar el servicio.',
  'terms_contact_title': 'Contacto',
  'terms_contact_content': 'Preguntas sobre estos términos:\n\nsupport@everywear.studio',

    // Profile Screen
  'profile_title': 'Perfil',
  'insights_analytics': 'Información y análisis',
  'style_insights': 'Información de estilo',
  'style_insights_subtitle': 'Análisis de armario y recomendaciones de IA',
  'achievements': 'Logros',
  'achievements_subtitle': 'Ver insignias y hitos ganados',
  'progress_dashboard': 'Panel de progreso',
  'progress_dashboard_subtitle': 'Sigue la evolución de tu estilo',
  'membership': 'Membresía',
  'essential_plan_unlock': 'Plan Essential · Desbloquea más funciones',
  'signature_plan': 'Plan Signature',
  'settings_subtitle': 'Preferencias, seguridad, privacidad',
  'plan': 'plan',

  // Premium Upgrade Screen
  'premium_upgrade': 'Actualizar a Premium',
  'choose_your_plan': 'Elige tu plan',
  'upgrade_more_features': 'Actualiza cuando quieras más sugerencias, más coaching, más variaciones de conjuntos y sin anuncios.',
  'monthly': 'Mensual',
  'per_month': '/mes',
  'yearly': 'Anual',
  'per_year': '/año',
  'save_percent': '-22%',
  'more_ai_outfit_suggestions': 'Más sugerencias de conjuntos con IA',
  'more_coach_interactions': 'Más interacciones con el coach',
  'more_event_outfit_generations': 'Más generaciones de conjuntos para eventos',
  'ad_free_experience': 'Experiencia sin anuncios',
  'access_premium_while_subscribed': 'Acceso a funciones Premium mientras estás suscrito',
  'everything_in_monthly': 'Todo lo del plan Mensual',
  'better_yearly_value': 'Mejor valor anual',
  'fewer_renewals': 'Menos renovaciones que gestionar',
  'full_premium_all_year': 'Acceso Premium completo todo el año',
  'best_plan_regular_users': 'Mejor plan para usuarios regulares',
  'how_billing_works': 'Cómo funciona la facturación',
  'billing_managed_by_store': 'Tu suscripción será gestionada por Google Play o App Store. No se requiere formulario de tarjeta aquí — la facturación continúa a través de tu cuenta de store.',
  'what_users_say': 'Lo que dicen nuestros usuarios',
  'frequently_asked_questions': 'Preguntas frecuentes',
  'secure_store_billing': 'Facturación segura',
  'subscriptions_handled_securely': 'Las suscripciones se gestionan de forma segura a través de Google Play o App Store en tu dispositivo.',
  'restore_purchases': 'Restaurar compras',
  'welcome_to_signature': '¡Bienvenido a Signature!',
  'purchases_restored_success': '¡Compras restauradas con éxito!',
  'no_active_subscription_restore': 'No se encontró ninguna suscripción activa para restaurar.',
  'purchase_failed': 'Error en la compra',
  'restore_failed': 'Error al restaurar',
  'no_offerings_available': 'No hay ofertas disponibles. Por favor, inténtalo más tarde.',
  'please_login_continue': 'Por favor, inicia sesión para continuar',

  // FAQ
  'faq_cancel_anytime': '¿Puedo cancelar en cualquier momento?',
  'faq_cancel_anytime_answer': 'Sí. Tu suscripción se renueva automáticamente y puedes cancelarla en cualquier momento desde la configuración de suscripciones de Play Store o App Store.',
  'faq_what_happens_cancel': '¿Qué pasa si cancelo?',
  'faq_what_happens_cancel_answer': 'Mantendrás el acceso Premium hasta el final del período de facturación actual, luego tu cuenta volverá al plan gratuito.',
  'faq_restore_subscription': '¿Puedo restaurar mi suscripción?',
  'faq_restore_subscription_answer': 'Sí. Si ya compraste Premium en esta cuenta, puedes restaurar tus compras en cualquier momento.',
  'faq_discount_codes': '¿Ofrecen códigos de descuento?',
  'faq_discount_codes_answer': 'Ocasionalmente, sí. Los códigos de descuento especiales pueden compartirse a través de campañas, asociaciones o creadores seleccionados.',

  // Testimonials
  'testimonial_sarah_text': 'Los análisis Premium me ayudaron a reducir las compras impulsivas y obtener más valor de la ropa que ya tengo.',
  'testimonial_marcus_text': 'Las sugerencias de IA y las variaciones de conjuntos hicieron que la aplicación pareciera un verdadero estilista personal.',
  'testimonial_emma_text': 'Premium hizo la aplicación mucho más útil día a día. Más ideas, más orientación, sin anuncios.',

  // Dynamic AI messages
  'ai_bubble_message_initial':
      '👋 ¡Hola! ¡He analizado tu guardarropa y he encontrado {count} combinaciones de atuendos perfectas para ti hoy! Cada sugerencia está personalizada según tus preferencias de estilo, las condiciones climáticas y tus favoritos anteriores.',
  'ai_bubble_message_found':
      '🎯 ¡He encontrado {count} atuendos potenciados por IA con un {confidence}% de coincidencia con tu estilo! Toca cualquier sugerencia para ver consejos de estilo detallados y completar el look. ¿Quieres probar algo nuevo? ¡También he incluido combinaciones que aún no has usado!',
  
  // New Wardrobe & Item Management
  'retry': 'Reintentar',
  'items': 'artículos',
  'selected_items': 'artículos seleccionados',
  'items_limit_reached': 'Límite de artículos alcanzado',
  'live_sync': 'En vivo',
  'wardrobe_search_hint': 'Buscar por nombre o marca',
  'loading_wardrobe': 'Cargando guardarropa...',
  'failed_to_load_wardrobe': 'Error al cargar el guardarropa',
  'delete_item': 'Eliminar Artículo',
  'delete_items': 'Eliminar Artículos',
  'delete_item_confirmation': '¿Estás seguro de que deseas eliminar este artículo de tu guardarropa?',
  'item_deleted_success': 'Artículo eliminado con éxito',
  'item_delete_error': 'Error al eliminar el artículo',
  'items_deleted_success': 'Artículos eliminados con éxito',
  'items_delete_error': 'Error al eliminar los artículos',
  'item_added_to_wardrobe': 'añadido al guardarropa',
  'item_save_error': 'Error al guardar el artículo. Por favor, inténtalo de nuevo.',

  // Daily Log
  'good_morning': 'Buenos días',
  'good_afternoon': 'Buenas tardes',
  'good_evening': 'Buenas noches',
  'log_outfit_btn': 'Registrar',
  'repeat_outfit': 'Repetir atuendo',
  'repeat_outfit_question': '¿Registrar este atuendo de nuevo para hoy?',
  'outfit_repeated': '¡Atuendo repetido para hoy!',
  'edit_outfit': 'Editar atuendo',
  'delete_outfit': 'Eliminar atuendo',
  'delete_outfit_confirmation': '¿Estás seguro de que quieres eliminar este atuendo?',
  'outfit_deleted': 'Atuendo eliminado',
  'outfit_updated': '¡Atuendo actualizado!',
  'this_month': 'Este mes',
  'rating': 'Calificación: ',
  'weather_fallback_label': 'Estilo, a tu manera',
  'enter_city_manually': 'Ingresa tu ciudad',
  'enter_city_title': 'Ingresa ciudad',
  'city_hint': 'ej. Madrid, ES',
  'daily_log_welcome_subtitle': 'Un espacio tranquilo para elegir lo que se siente bien hoy — guiado por tu guardarropa, tus planes y tu estado de ánimo.',
  'set_todays_direction': 'Elige la dirección de hoy',
  'set_direction_subtitle': 'Elige la ocasión y el ambiente que deseas. Tu sugerencia se actualizará en base a ello.',
  'dressing_for': 'Vistiéndose para',
  'todays_vibe': 'Vibra de hoy',
  'occasion_work': 'Trabajo',
  'occasion_casual': 'Casual',
  'occasion_dinner': 'Cena',
  'occasion_event': 'Evento',
  'occasion_travel': 'Viaje',
  'occasion_formal': 'Formal',
  'occasion_social_event': 'Evento social',
  'occasion_date_night': 'Cita',
  'occasion_athletic': 'Deportivo',
  'mood_casual': 'Casual',
  'mood_polished': 'Pulido',
  'mood_comfort': 'Comodidad',
  'mood_bold': 'Audaz',
  'mood_surprise': 'Sorpresa',
  'weather_tip_rain': 'Lleva una capa impermeable hoy',
  'weather_tip_snow': 'Añade capas y mantén el atuendo cálido',
  'weather_tip_sun': 'Perfecto para capas más ligeras',
  'weather_tip_cloud': 'Una chaqueta ligera funcionaría bien',
  'weather_tip_wind': 'Una capa ajustada ayudará en un día ventoso',
  'weather_tip_default': 'Vístete para tu día',
  'todays_style_idea': 'Idea de estilo de hoy',
  'simple_daily_suggestion': 'Una sugerencia de conjunto diario simple.',
  'anchor_piece_tap_to_swap': 'Pieza ancla · Toque para cambiar',
  'tap_to_swap': 'Toque para cambiar',
  'refresh': 'Actualizar',
  'unknown': 'Desconocido',
  'outfit_label': 'Atuendo',
  'style_tip': 'Consejo de Estilo',
  'style_tip_no_logs': 'Comienza a registrar tus atuendos regularmente para desbloquear más patrones de estilo personal y orientación diaria más inteligente.',
  'style_tip_few_logs': 'Todavía estás construyendo tu historial de atuendos. Unos pocos registros más harán que tus sugerencias sean más personales y variadas.',
  'style_tip_bold': 'Dado que quieres un look más audaz hoy, mantén una pieza destacada y deja que el resto del atuendo se mantenga más equilibrado.',
  'style_tip_comfort': 'La comodidad funciona mejor cuando el atuendo todavía se siente intencional. Intenta mantener la base suave y la capa exterior más estructurada.',
  'style_tip_favorite_occasion': 'Tu ocasión más común este mes es {occasion}. Mantener una versión confiable de ese look lista puede ahorrar tiempo en días ocupados.',
  'upcoming_event': 'Próximo Evento',
  'in_days_left': 'En {days} días',
  'dress_code_format': 'Código de vestimenta: {dressCode}',
  'item_denim_jacket': 'Chaqueta de mezclilla',
  'item_white_tee': 'Camiseta blanca',
  'item_black_jeans': 'Vaqueros negros',
  'item_sneakers': 'Zapatillas',
  'item_navy_blazer': 'Blazer azul marino',
  'item_white_shirt': 'Camisa blanca',
  'item_tailored_trousers': 'Pantalones de vestir',
  'item_leather_shoes': 'Zapatos de cuero',
  'item_statement_jacket': 'Chaqueta llamativa',
  'item_silk_top': 'Top de seda',
  'item_dark_trousers': 'Pantalones oscuros',
  'item_low_heels': 'Tacones bajos',
  'item_chelsea_boots': 'Botas Chelsea',
  'item_light_overshirt': 'Sobrecamisa ligera',
  'item_breathable_tee': 'Camiseta transpirable',
  'item_relaxed_pants': 'Pantalones relajados',
  'item_comfort_sneakers': 'Zapatillas cómodas',
  'item_structured_blazer': 'Blazer estructurado',
  'item_refined_top': 'Top refinado',
  'item_tailored_bottoms': 'Partes inferiores a medida',
  'item_dress_shoes': 'Zapatos de vestir',
  'item_waterproof_jacket': 'Chaqueta impermeable',
  'item_soft_tee': 'Camiseta suave',
  'item_dark_jeans': 'Vaqueros oscuros',
  'item_weatherproof_sneakers': 'Zapatillas resistentes a la intemperie',
  'item_light_cardigan': 'Cárdigan ligero',
  'item_cotton_tee': 'Camiseta de algodón',
  'item_relaxed_trousers': 'Pantalones relajados',
  'item_white_sneakers': 'Zapatillas blancas',
  'item_tailored_overshirt': 'Sobrecamisa a medida',
  'item_clean_neutral_top': 'Top neutro limpio',
  'item_straight_trousers': 'Pantalones rectos',
  'item_minimal_loafers': 'Mocasines minimalistas',
  'item_chunky_sneakers': 'Zapatillas gruesas',
  'item_black_tee': 'Camiseta negra',
  'item_soft_blouse': 'Blusa suave',
  'item_straight_jeans': 'Vaqueros rectos',
  'item_tailored_shorts': 'Pantalones cortos de vestir',
  'item_leather_loafers': 'Mocasines de cuero',
  'item_minimal_trainers': 'Entrenadores minimalistas',
  'occasion_everyday': 'Todos los días',
  'event_type_other': 'Otro',
  'item_statement_layer': 'Capa de impacto',
  'item_contrast_top': 'Top de contraste',
  'item_dark_denim': 'Vaqueros oscuros',
  'cat_shoes': 'Zapatos',
  'cat_footwear': 'Calzado',
  'cat_anchor': 'Ancla',
  'cat_clothing': 'Ropa',
  'unknown_item': 'Artículo desconocido',
  'todays_log_section': 'Registro de hoy',
  'nothing_logged_today': 'Nada registrado todavía hoy',
  'quick_log_prompt': 'Usa el botón de registro rápido para guardar el atuendo de hoy y construir tu historial de estilo.',
  'swap_item_title': 'Cambiar {item}',
  'choose_different_piece': 'Elige una pieza diferente para esta idea de atuendo',
  'quick_log_options': 'Opciones de Registro Rápido',
  'quick_log_take_photo_title': 'Tomar Foto',
  'quick_log_take_photo_subtitle': 'Captura tu atuendo ahora',
  'quick_log_previous_title': 'Registrar Atuendo Anterior',
  'quick_log_previous_subtitle': 'Agregar atuendo de más temprano hoy',
  'quick_log_repeat_title': 'Repetir Último Atuendo',
  'quick_log_repeat_subtitle': 'Registra tu atuendo más reciente de nuevo',
  'quick_log_save_displayed_title': 'Guardar Atuendo Mostrado',
  'quick_log_save_displayed_subtitle': 'Registrar el atuendo mostrado arriba',
  'total_outfits': 'Total de Atuendos',
  'unique_items': 'Artículos Únicos',
  'favorite_occasion': 'Ocasión Favorita',
  'notes': 'Notas',
  'no_outfit_displayed_error': 'No hay atuendo mostrado para guardar',
  'no_valid_wardrobe_items_error': 'No hay artículos de guardarropa válidos en el atuendo mostrado',
  'slot_anchor': 'pieza ancla',
  'slot_top': 'parte superior',
  'slot_bottom': 'parte inferior',
  'slot_shoes': 'calzado',
  'slot_item': 'artículo',
  'fallback_suggestion_desc': 'Una idea de atuendo cotidiano versátil construida alrededor de una pieza ancla fácil.',
  'work_suggestion_desc': 'Un atuendo pulido listo para el trabajo que mantiene la estructura sin sentirse demasiado rígido.',
  'dinner_suggestion_desc': 'Un look de noche ligeramente elevado que se siente intencional pero aún usable.',
  'travel_suggestion_desc': 'Un atuendo de viaje práctico que tiene en cuenta el movimiento y las capas.',
  'event_suggestion_desc': 'Una combinación más lista para la ocasión diseñada para lucir nítida y bien arreglada.',
  'rain_suggestion_desc': 'Un atuendo práctico consciente del clima que se mantiene cómodo en condiciones húmedas.',
  'sun_suggestion_desc': 'Una idea de atuendo más ligerea que funciona bien para un día más brillante y un movimiento fácil.',
  'polished_suggestion_desc': 'Una idea de atuendo limpia y pulida que afina el look general sin exagerar.',
  'bold_suggestion_desc': 'Una combinación más expresiva que mantiene la silueta simple mientras deja que una pieza destaque.',
  'surprise_suggestion_desc': 'Una combinación más fresca diseñada para ayudarte a usar algo un poco menos esperado hoy.',
  'outfit_image_label': 'Imagen del atuendo',
  'repeat_outfit_tooltip': 'Repetir atuendo hoy',
  'edit_outfit_tooltip': 'Editar atuendo',
  'delete_outfit_tooltip': 'Eliminar atuendo',
  'outfits_label': 'Atuendos',
  'items_label': 'Artículos',
  'top_label': 'Top',
  'style_title': 'Estilo',
  'ask_your_coach': 'Pregunta a tu coach',
  'add_event': 'Agregar evento',
  'delete_event': 'Eliminar evento',
  'remove_event_question': '¿Eliminar este evento?',
  'style_coach': 'Coach de Estilo',
  'or_pick_a_topic': 'O elige un tema',
  'event_name': 'Nombre del evento',
  'hint_wedding': 'ej. Boda de Sarah',
  'date_label': 'Fecha',
  'dress_code_optional': 'Código de vestimenta (opcional)',
  'editEvent': 'Editar evento',
  'noDressCode': 'Sin código de vestimenta',
  'finish': 'Finalizar',
  'style_quiz': 'Cuestionario de estilo',
  'profile_classic': 'Elegancia clásica',
  'profile_bold': 'Atrevido y a la moda',
  'profile_active': 'Activo y deportivo',
  'profile_minimalist': 'Minimalista',
  'monthly_budget': 'Presupuesto mensual',
  'add_to_wishlist': 'Agregar a la lista de deseos',
  'update_price': 'Actualizar precio',
  'mark_as_purchased': 'Marcar como comprado',
  'remove_from_wishlist': 'Eliminar de la lista de deseos',
  'delete_purchase': 'Eliminar compra',
  'bought_it': '¡Comprado!',
  'confirm_purchase': 'Confirmar',
  'how_much_did_you_pay': '¿Cuánto pagaste por',
  'added_to_wardrobe_log': 'añadido a tu registro de guardarropa',
  'your_personal_collection': 'Tu colección personal, lista para estilizar en cualquier lugar.',
  'updated_everywhere': 'Actualizado en todas partes',
  'item_updated': 'Artículo actualizado',
  'unsaved_changes': 'Tienes cambios sin guardar. ¿Estás seguro de que quieres salir?',
  'discard': 'Descartar',
  'edit_item': 'Editar artículo',
  'changes': 'Cambios',
  'noItemsInCategory': 'No hay artículos en esta categoría todavía.',
  'addItemToWardrobe': 'Añadir un artículo',

  // Category names
  'tops': 'Tops',
  'bottoms': 'Pantalones',
  'shoes': 'Zapatos',
  'outerwear': 'Abrigos',
  'accessories': 'Accesorios',
  'dresses': 'Vestidos',
  'activewear': 'Ropa deportiva',

  // Missing keys added during localization audit
  'check_back_soon': 'Vuelve pronto para nuevos desafíos de estilo',
  'no_insights_yet': 'Aún no hay estadísticas',
  'add_items_for_insights': 'Agrega prendas a tu guardarropa para ver tus estadísticas de estilo',
  'outfits_logged': 'Ropa registrada',
  'top_category': 'Categoría principal',
  'top_occasion': 'Ocasión principal',
  'q_style_adventures': '¿Qué tan aventurero eres con el estilo?',
  'q_style_adv_works': 'Me quedo con lo que sé que funciona',
  'q_style_adv_small': 'Me gustan los cambios pequeños',
  'q_style_adv_often': 'Disfruto experimentando a menudo',
  'q_style_adv_depends': 'Depende de la ocasión',
  'profile_style': 'Estilo',
  'today': 'Hoy',
  'tomorrow': 'Mañana',
  'days': 'días',
  'overall_rating': 'Calificación general',
  'how_did_you_feel': '¿Cómo te sentiste con este outfit?',
  'detailed_ratings': 'Calificaciones detalladas',
  'comfort': 'Comodidad',
  'style': 'Estilo',
  'versatility': 'Versatilidad',
  'occasion': 'Ocasión',
  'would_wear_again': '¿Lo volverías a usar?',
  'help_us_learn': 'Ayúdanos a aprender tus preferencias',
  'save_rating': 'Guardar calificación',
  'rate_your_outfit': 'Califica tu atuendo',
  'rated_outfit': 'Atuendo calificado',
  'skip_photo': 'Omitir foto',
  'failed_to_capture_photo': 'Error al capturar. Por favor intenta de nuevo.',
  'save_error': 'Error al guardar',
  'final_price': 'Precio final',
  'current_price': 'Precio actual',
  'filter_by_category': 'Filtrar por categoría',
  'custom_date_range': 'Rango de fechas personalizado',

  // Quiz — questions 1, 2, 3 & 5
  'q_feel_like_yourself': '¿Qué atuendos te hacen sentir más tú mismo?',
  'q_feel_relaxed': 'Relajado y sin esfuerzo',
  'q_feel_polished': 'Pulido y atemporal',
  'q_feel_creative': 'Creativo y expresivo',
  'q_feel_practical': 'Práctico y deportivo',
  'q_colors_dominate': '¿Qué colores dominan tu guardarropa hoy?',
  'q_colors_neutrals': 'Principalmente neutros',
  'q_colors_earth': 'Tonos tierra y cálidos',
  'q_colors_bold': 'Colores vivos y contraste',
  'q_colors_soft': 'Tonos suaves y claros',
  'q_help_most': '¿Con qué quieres más ayuda ahora mismo?',
  'q_help_together': 'Verme más arreglado',
  'q_help_variety': 'Crear más variedad de atuendos',
  'q_help_shopping': 'Comprar de forma más intencional',
  'q_help_confident': 'Sentirme más seguro con lo que llevo',
  'q_matters_most': 'Al elegir ropa, ¿qué es lo más importante para ti?',
  'q_matters_comfort': 'Comodidad',
  'q_matters_elegance': 'Elegancia',
  'q_matters_originality': 'Originalidad',
  'q_matters_versatility': 'Versatilidad',

  'stylistIncludesFavorite': 'Incluye tu favorito %s',
  'stylistPerfectTimeToWear': 'El momento perfecto para llevar tu %s',
  'stylistLightBreathable': 'Ligero y transpirable para %s°C',
  'stylistWarmCozy': 'Abrigado y cómodo para %s°C',
  'stylistProfessional': 'Profesional y elegante para el trabajo',
  'stylistComfortable': 'Cómodo y relajado para el día a día',
  'stylistAiCurated': 'Combinación seleccionada por IA según tu armario',
  'stylistLayerOuterwear': 'Superpón tu ropa exterior para adaptarte a la temperatura',
  'stylistAddBelt': 'Añade un cinturón para definir la cintura',
  'stylistConsiderAccessories': 'Considera añadir un reloj o joyería sencilla',
  'stylistEnsureShoes': 'Asegúrate de que los zapatos estén limpios y los accesorios sean discretos',
  'stylistExperimentAccessories': 'Siéntete libre de experimentar con accesorios llamativos',
  'stylistWearConfidence': 'Llévalo con confianza y hazlo tuyo',

  // CHALLENGES
  'challenge_weekly_label': 'Desafío semanal',
  'challenge_accept': 'Aceptar el desafío',
  'challenge_log_progress': 'Registrar atuendo',
  'challenge_tap_to_log': 'Toca para registrar progreso',
  'challenge_complete_inline': '✅ ¡Desafío completado!',
  'challenge_complete_title': '¡Desafío completado!',
  'challenge_next_week': 'Nuevo desafío llega la próxima semana.',
  'challenge_insight_title': 'Insight de Estilo Desbloqueado',
  'challenge_insight_card_title': 'Tu Insight de Estilo',
  'challenge_insight_cta': '¡Genial!',
  'challenge_progress_label': 'Progreso',
  'challenge_anchor_chosen': 'Tu pieza ancla',
  'challenge_anchor_pick_title': 'Elige tu pieza ancla',
  'challenge_anchor_pick_subtitle': 'Esta es la pieza alrededor de la cual crearás 3 atuendos.',
  'challenge_suggested_for_you': 'Sugerido para ti',
  'challenge_stylist_tip': 'Consejo de estilista',
  'challenge_how_it_works': 'Cómo funciona',
  'challenge_no_wardrobe': 'No se encontraron artículos en el guardarropa. Agrega artículos primero.',

  // Additional strings
  'maximum_photos_allowed': 'Número máximo de fotos',
  'failed_to_select_photo': 'Error al seleccionar la foto',
  'ai_detected': 'Detectado por IA',
  'share_achievement': 'Compartir logro',
  'search_achievements': 'Buscar logros',
  'add_first_item': 'Agrega tu primer artículo',
  'could_not_generate_export': 'No se pudo generar la exportación',
  'export_error': 'Error de exportación',
  'take_a_photo': 'Tomar una foto',
  'failed_to_save_preferences': 'No se pudieron guardar las preferencias',
  'please_provide_rating': 'Por favor proporciona una calificación',
  'rating_saved_successfully': 'Calificación guardada con éxito',
  'failed_to_save_rating': 'Error al guardar la calificación',
  'saving_your_rating': 'Guardando tu calificación',
  'purchases_restored': 'Compras restauradas',
  'key_learnings': 'Aprendizajes clave',
  'module_locked': 'Módulo bloqueado',
  'about_learning_paths': 'Acerca de las rutas de aprendizaje',
  'how_it_works': 'Cómo funciona:',
  'new_ai_insights_generated': '¡Nuevos conocimientos de IA generados con éxito!',
  'send_message': 'Enviar mensaje',
  'feedback_sent': 'Gracias - tu retroalimentación ha sido enviada',
  'could_not_send_feedback': 'No se pudo enviar la retroalimentación',
  'change_photo': 'Cambiar foto',
  'profile_photo_updated': 'Foto de perfil actualizada',
  'could_not_upload_photo': 'No se pudo subir la foto. Verifica los detalles en la consola de depuración.',
  'profile_updated_successfully': 'Perfil actualizado con éxito',
  'could_not_update_profile': 'No se pudo actualizar el perfil',
  'wear_this': 'Usa esto',
  'log_first_outfit': 'Registra tu primer conjunto',
  'challenge_accepted': '¡Desafío aceptado! ¡Buena suerte!',
  'no_challenges_found': 'No se encontraron desafíos',
  'password_updated': 'Contraseña actualizada con éxito',
  'could_not_update_password': 'No se pudo actualizar la contraseña',
  'update_password_btn': 'Actualizar contraseña',
  'morning_ai_suggestions': 'Sugerencias de IA de la mañana',
  'daily_outfit_ideas': 'Ideas de conjuntos diarios cada mañana',
  'events': 'Eventos',
  'tip_of_the_week': 'Consejo de la semana',
  'personalized_coaching': 'Coaching personalizado',
  'complete_quiz_for_coaching': 'Completa tu cuestionario para un mejor coaching',
  'coach_is_thinking': 'Tu coach está pensando...',
  'coach_is_preparing_tip': 'Tu coach está preparando un consejo para ti...',
  'discover_your_style': 'Descubre tu estilo',
  'retake_quiz': 'Repetir',
  'take_quiz_to_personalise': 'Resuelve el cuestionario para personalizar tus sugerencias de IA',
  'quick_questions': 'Preguntas rápidas',
  'get_help_styling_pieces': 'Obtén ayuda para combinar las prendas que tienes',
  'event_coaching': 'Coaching para eventos',
  'suggestions_for': 'Sugerencias para {title}',
  'add_event_to_unlock': 'Agrega un evento para desbloquear esto',
  'coach_limit_reached': 'Límite de coach alcanzado',
  'premium_coach_limit_msg': 'Has usado todas tus 50 sesiones de coaching este mes. Tu cuota se reiniciará el próximo mes.',
  'free_coach_limit_msg': 'El plan Esencial incluye 1 sesión de coaching por semana. Actualiza a Signature para 50 sesiones al mes.',
  'ask_your_coach_btn': 'Pregunta a tu coach',
  'type_question_or_pick_topic': 'Escribe tu propia pregunta o elige un tema.',
  'coach_hint_text': 'ej. ¿Cómo me veo más seguro?',
  'topic_outfit_ideas': '👔 Ideas de atuendos',
  'topic_shopping_advice': '🛍 Consejos de compra',
  'topic_my_wardrobe': '👗 Mi guardarropa',
  'topic_for_an_event': '📅 Para un evento',
  'topic_more_variety': '🔄 Más variedad',
  'topic_style_upgrade': '✨ Mejora de estilo',
  'q_outfit_ideas': 'Dame ideas de atuendos basadas en mi guardarropa y perfil de estilo.',
  'q_shopping_advice': '¿Qué prenda debería comprar a continuación para completar más atuendos en mi guardarropa?',
  'q_my_wardrobe': 'Dame una evaluación honesta de mi guardarropa basada en mis datos.',
  'q_for_an_event': '¿Cómo debería vestirme para una ocasión especial basada en mi estilo?',
  'q_more_variety': '¿Cómo puedo crear más variedad de atuendos con lo que ya tengo?',
  'q_style_upgrade': '¿Qué es lo único que puedo cambiar para elevar mi estilo diario?',
  // Challenge type titles
  'challenge_type_anchor_title': 'Pieza Ancla',
  'challenge_type_anchor_description': 'Elige una pieza clave de tu armario y crea 3 outfits diferentes alrededor de ella durante la semana.',
  'challenge_type_capsule_title': 'Desafío Cápusula',
  'challenge_type_capsule_description': 'Selecciona 7 piezas y crea 5 outfits diferentes usando solo esas prendas.',
  'challenge_type_color_title': 'Historia de Color',
  'challenge_type_color_description': 'Crea outfits usando una paleta de colores coherente - prueba tonos azul marino, camel o aceituna.',
  'challenge_type_rediscover_title': 'Redescubre',
  'challenge_type_rediscover_description': 'Encuentra una prenda sin usar en tu armario y styléala de una manera nueva.',
};
