/// English translations for the Everywear app
const Map<String, String> appLocalizationsEn = {
  // App info
  'app_name': 'Everywear',
  'app_tagline': 'Understand Your Style',

  // Common UI
  'continue': 'Continue',
  'cancel': 'Cancel',
  'save': 'Save',
  'delete': 'Delete',
  'edit': 'Edit',
  'settings': 'Settings',
  'profile': 'Profile',
  'logout': 'Logout',
  'back': 'Back',
  'next': 'Next',
  'done': 'Done',
  'loading': 'Loading...',
  'error': 'Error',
  'success': 'Success',
  'ok': 'OK',
  'yes': 'Yes',
  'no': 'No',
  'search': 'Search',
  'filter': 'Filter',
  'sort': 'Sort',

  // Auth
  'welcome_back': 'Welcome Back',
  'create_account': 'Create Account',
  'email': 'Email',
  'password': 'Password',
  'full_name': 'Full Name',
  'sign_in': 'Sign In',
  'sign_up': 'Sign Up',
  'continue_with_google': 'Continue with Google',
  'continue_with_email': 'Continue with Email',
  'already_have_account': 'Already have an account?',
  'dont_have_account': "Don't have an account?",
  'forgot_password': 'Forgot Password?',
  'or': 'OR',
  'sign_in_subtitle': 'Sign in to continue your style journey',
  'sign_up_subtitle': 'Sign up to start tracking your wardrobe',
  'terms_agreement':
      'By continuing, you agree to our Terms of Service and Privacy Policy',
  'email_required': 'Email is required',
  'password_required': 'Password is required',
  'name_required': 'Name is required',
  'invalid_email': 'Enter a valid email',
  'password_too_short': 'Password must be at least 6 characters',

  // Settings
  'settings_and_profile': 'Settings & Profile',
  'account_settings': 'Account Settings',
  'app_preferences': 'App Preferences',
  'privacy_settings': 'Privacy Settings',
  'data_management': 'Data Management',
  'subscription': 'Subscription',
  'help_and_support': 'Help & Support',
  'language': 'Language',
  'select_language': 'Select Language',
  'theme': 'Theme',
  'notifications': 'Notifications',
  'change_password': 'Change Password',
  'update_password': 'Update your password',
  'two_factor_auth': 'Two-Factor Authentication',
  'email_preferences': 'Email Preferences',
  'manage_email_notifications': 'Manage email notifications',
  'enabled': 'Enabled',
  'disabled': 'Disabled',
  'data_sharing': 'Data Sharing',
  'share_usage_data': 'Share usage data for improvements',
  'analytics': 'Analytics',
  'help_improve_app': 'Help improve the app',
  'profile_visibility': 'Profile Visibility',
  'manage_profile_visibility': 'Manage who can see your profile',
  'export_data': 'Export Data',
  'download_wardrobe_data': 'Download your wardrobe data',
  'backup_settings': 'Backup Settings',
  'automatic_cloud_backup': 'Automatic cloud backup',
  'delete_account': 'Delete Account',
  'permanently_delete_account': 'Permanently delete your account',
  'current_plan': 'Current Plan',
  'billing_history': 'Billing History',
  'view_past_invoices': 'View past invoices',
  'upgrade_plan': 'Upgrade Plan',
  'unlock_more_features': 'Unlock more features',
  'help_center': 'Help Center',
  'faqs_and_guides': 'FAQs and guides',
  'send_feedback': 'Send Feedback',
  'share_your_thoughts': 'Share your thoughts',
  'about': 'About',
  'version': 'Version 1.0.0',
  'ai_model_management': 'AI Model Management',
  'manage_local_ai': 'Manage local AI engine',
  'manage_notifications': 'Manage notification preferences',
  'light_mode': 'Light Mode',
  'dark_mode': 'Dark Mode',
  'auto_system': 'Auto (System)',

  // Wardrobe
  'wardrobe': 'Wardrobe',
  'add_item': 'Add Item',
  'my_wardrobe': 'My Wardrobe',
  'outfit': 'Outfit',
  'outfits': 'Outfits',
  'daily_log': 'Daily Log',
  'insights': 'Insights',

  // Language names
  'english': 'English',
  'french': 'French',
  'spanish': 'Spanish',

  // Logout confirmation
  'logout_confirmation': 'Are you sure you want to logout?',
  'delete_account_confirmation':
      'Are you sure you want to permanently delete your account? This action cannot be undone.',

  // Export options
  'export_data_format': 'Export Data Format',
  'pdf_report': 'PDF Report',
  'comprehensive_wardrobe_report': 'Comprehensive wardrobe report',
  'csv_spreadsheet': 'CSV Spreadsheet',
  'raw_data_analysis': 'Raw data for analysis',
  'exporting_data': 'Exporting data as',

  // About app
  'about_everywear':
      'Everywear helps you make mindful wardrobe decisions through analytics and insights.',
  'close': 'Close',

  // AI & Smart Suggestions
  'ai_styling_assistant': 'AI Styling Assistant',
  'powered_by_ai': 'Powered by AI',
  'dismiss': 'Dismiss',
  'smart_suggestions_title': 'Smart Suggestions',
  'refresh_suggestions': 'Refresh suggestions',
  'analyzing_wardrobe': 'AI is analyzing your wardrobe...',
  'ai_banner_text': '{count} AI-powered suggestions based on your wardrobe',
  'filter_by_occasion': 'Filter by occasion',
  'outfit_added_to_log': 'Outfit added to today\'s log',
  'saved_for_later': 'Saved for later',
  'removed_from_saved': 'Removed from saved',
  'suggestion_dismissed': 'Suggestion dismissed - we\'ll learn from this',
  'undo': 'Undo',
  'items_in_this_outfit': 'Items in this outfit',
  'last_worn_label': 'Last worn',
  'styling_tips': 'Styling Tips',

  // Camera
  'camera_flip_error': 'Failed to flip camera. Please try again.',
  'camera_capture_error': 'Failed to capture photo. Please try again.',

  // Filters
  'filter_all': 'All',
  'filter_work': 'Work',
  'filter_casual': 'Casual',
  'filter_special': 'Special',

  // Capture Flow
  'log_outfit': 'Log Outfit',
  'capture_outfit': 'Capture Outfit',
  'select_from_wardrobe': 'Select from Wardrobe',
  'confirm_outfit': 'Confirm Outfit',
  'camera_permission_required': 'Camera permission is required to capture outfits',
  'camera_init_error': 'Failed to initialize camera. Please try again.',
  'getting_ai_suggestions': 'Getting AI suggestions...',
  'get_ai_tips': 'Get AI Tips',
  'gallery_pick_error': 'Failed to pick image from gallery',
  'how_to_log_outfit': 'How would you like to log your outfit?',
  'capture_method_subtitle': 'Choose your preferred method to quickly capture today\'s look',
  'take_photo': 'Take Photo',
  'take_photo_subtitle': 'Capture your outfit with camera',
  'build_from_wardrobe': 'Build from Wardrobe',
  'build_from_wardrobe_subtitle': 'Select items from your wardrobe',
  'wear_this_today': 'Wear This Today',
  'save_for_later_btn': 'Save for Later',
  'retake': 'Retake',
  'rate_outfit_error': 'Please rate your outfit before saving',
  'outfit_preview': 'Outfit Preview',
  'no_image_captured': 'No image captured',
  'selected_items_count': 'Selected Items ({count})',
  'outfit_name_optional': 'Outfit Name (Optional)',
  'outfit_name_hint': 'e.g., Casual Friday, Date Night',
  'feel_in_outfit_question': 'How did you feel in this outfit?',
  'rating_not_great': 'Didn\'t feel great',
  'rating_ok': 'OK',
  'rating_loved_it': 'Loved it',
  'save_outfit': 'Save Outfit',
  'select_at_least_one_item': 'Please select at least one item',
  'search_wardrobe_hint': 'Search wardrobe items...',
  'no_items_found': 'No items found',
  'continue_with_item_singular': 'Continue with {count} item',
  'continue_with_items_plural': 'Continue with {count} items',
  'cost_per_wear': 'Cost Per Wear',
  'per_wear': '/wear',

  // Dynamic AI messages
  'ai_bubble_message_initial':
      '👋 Hi! I\'ve analyzed your wardrobe and found {count} perfect outfit combinations for you today! Each suggestion is personalized based on your style preferences, weather conditions, and past favorites.',
  'ai_bubble_message_found':
      '🎯 I found {count} AI-powered outfits with a {confidence}% match to your style! Tap any suggestion to see detailed styling tips and complete the look. Want to try something new? I\'ve also included combinations you haven\'t worn yet!',
};
