/// French translations for the Everywear app
const Map<String, String> appLocalizationsFr = {
  // App info
  'app_name': 'Everywear',
  'app_tagline': 'Comprendre Votre Style',

  // Common UI
  'continue': 'Continuer',
  'cancel': 'Annuler',
  'save': 'Enregistrer',
  'delete': 'Supprimer',
  'edit': 'Modifier',
  'settings': 'Paramètres',
  'profile': 'Profil',
  'logout': 'Déconnexion',
  'back': 'Retour',
  'next': 'Suivant',
  'done': 'Terminé',
  'loading': 'Chargement...',
  'error': 'Erreur',
  'success': 'Succès',
  'ok': 'OK',
  'yes': 'Oui',
  'no': 'Non',
  'search': 'Rechercher',
  'filter': 'Filtrer',
  'sort': 'Trier',

  // Auth
  'welcome_back': 'Bon Retour',
  'create_account': 'Créer un Compte',
  'email': 'Email',
  'password': 'Mot de passe',
  'full_name': 'Nom complet',
  'sign_in': 'Se Connecter',
  'sign_up': "S'inscrire",
  'continue_with_google': 'Continuer avec Google',
  'continue_with_email': 'Continuer avec Email',
  'already_have_account': 'Vous avez déjà un compte?',
  'dont_have_account': "Vous n'avez pas de compte?",
  'forgot_password': 'Mot de passe oublié?',
  'or': 'OU',
  'sign_in_subtitle': 'Connectez-vous pour continuer votre parcours style',
  'sign_up_subtitle': 'Inscrivez-vous pour suivre votre Dressing',
  'terms_agreement':
      "En continuant, vous acceptez nos Conditions d'utilisation et notre Politique de confidentialité",
  'email_required': "L'email est requis",
  'password_required': 'Le mot de passe est requis',
  'name_required': 'Le nom est requis',
  'invalid_email': 'Entrez un email valide',
  'password_too_short': 'Le mot de passe doit contenir au moins 6 caractères',

  // Settings
  'settings_and_profile': 'Paramètres et Profil',
  'account_settings': 'Paramètres du compte',
  'app_preferences': "Préférences de l'application",
  'privacy_settings': 'Paramètres de confidentialité',
  'data_management': 'Gestion des données',
  'subscription': 'Abonnement',
  'help_and_support': 'Aide et Support',
  'language': 'Langue',
  'select_language': 'Sélectionner la langue',
  'theme': 'Thème',
  'notifications': 'Notifications',
  'change_password': 'Changer le mot de passe',
  'update_password': 'Mettez à jour votre mot de passe',
  'two_factor_auth': 'Authentification à deux facteurs',
  'email_preferences': 'Préférences email',
  'manage_email_notifications': 'Gérer les notifications par email',
  'enabled': 'Activé',
  'disabled': 'Désactivé',
  'data_sharing': 'Partage de données',
  'share_usage_data': "Partager les données d'utilisation pour améliorer",
  'analytics': 'Analytique',
  'help_improve_app': "Aider à améliorer l'application",
  'profile_visibility': 'Visibilité du profil',
  'manage_profile_visibility': 'Gérer qui peut voir votre profil',
  'export_data': 'Exporter les données',
  'download_wardrobe_data': 'Télécharger vos données de Dressing',
  'backup_settings': 'Paramètres de sauvegarde',
  'automatic_cloud_backup': 'Sauvegarde cloud automatique',
  'delete_account': 'Supprimer le compte',
  'permanently_delete_account': 'Supprimer définitivement votre compte',
  'current_plan': 'Plan actuel',
  'billing_history': 'Historique de facturation',
  'view_past_invoices': 'Voir les factures passées',
  'upgrade_plan': 'Améliorer le plan',
  'unlock_more_features': 'Débloquer plus de fonctionnalités',
  'help_center': "Centre d'aide",
  'faqs_and_guides': 'FAQ et guides',
  'send_feedback': 'Envoyer des commentaires',
  'share_your_thoughts': 'Partagez vos pensées',
  'privacy_policy': 'Politique de Confidentialité',
  'view_privacy_policy': 'Voir notre politique de confidentialité',
  'terms_of_service': "Conditions d'utilisation",
  'view_terms_of_service': "Voir nos conditions d'utilisation",
  'about': 'À propos',
  'version': 'Version 1.0.0',
  'ai_model_management': 'Gestion du modèle IA',
  'manage_local_ai': 'Gérer le moteur IA local',
  'manage_notifications': 'Gérer les préférences de notification',
  'light_mode': 'Mode Clair',
  'dark_mode': 'Mode Sombre',
  'auto_system': 'Auto (Système)',

  // Wardrobe
  'wardrobe': 'Dressing',
  'add_item': 'Ajouter un article',
  'my_wardrobe': 'Mon Dressing',
  'outfit': 'Tenue',
  'outfits': 'Tenues',
  'daily_log': 'Journal quotidien',
  'insights': 'Aperçus',
  'your_style_profile': 'Votre Profil de Style',

  // Language names
  'english': 'Anglais',
  'french': 'Français',
  'spanish': 'Espagnol',

  // Logout confirmation
  'logout_confirmation': 'Êtes-vous sûr de vouloir vous déconnecter?',
  'delete_account_confirmation':
      'Êtes-vous sûr de vouloir supprimer définitivement votre compte? Cette action ne peut pas être annulée.',

  // Export options
  'export_data_format': "Format d'export de données",
  'pdf_report': 'Rapport PDF',
  'comprehensive_wardrobe_report': 'Rapport complet du Dressing',
  'csv_spreadsheet': 'Tableur CSV',
  'raw_data_analysis': "Données brutes pour l'analyse",
  'exporting_data': 'Export des données en',

  // About app
  'about_everywear':
      'Everywear vous aide à prendre des décisions éclairées concernant votre Dressing grâce aux analyses et aux aperçus.',
  'close': 'Fermer',

  // AI & Smart Suggestions
  'ai_styling_assistant': 'Assistant de Style IA',
  'powered_by_ai': 'Propulsé par l\'IA',
  'dismiss': 'Ignorer',
  'smart_suggestions_title': 'Suggestions Intelligentes',
  'refresh_suggestions': 'Actualiser les suggestions',
  'analyzing_wardrobe': 'L\'IA analyse votre Dressing...',
  'ai_banner_text': '{count} suggestions propulsées par l\'IA basées sur votre Dressing',
  'filter_by_occasion': 'Filtrer par occasion',
  'outfit_added_to_log': 'Tenue ajoutée au journal d\'aujourd\'hui',
  'saved_for_later': 'Enregistré pour plus tard',
  'removed_from_saved': 'Retiré des enregistrements',
  'suggestion_dismissed': 'Suggestion ignorée - nous apprendrons de cela',
  'undo': 'Annuler',
  'items_in_this_outfit': 'Articles dans cette tenue',
  'last_worn_label': 'Dernière fois porté',
  'styling_tips': 'Conseils de Style',

  // Camera
  'camera_flip_error': 'Échec du basculement de la caméra. Veuillez réessayer.',
  'camera_capture_error': 'Échec de la capture de la photo. Veuillez réessayer.',

  // Filters
  'filter_all': 'Tout',
  'filter_work': 'Travail',
  'filter_casual': 'Décontracté',
  'filter_special': 'Spécial',

  // Capture Flow
  'log_outfit': 'Enregistrer la tenue',
  'capture_outfit': 'Capturer la Tenue',
  'select_from_wardrobe': 'Sélectionner dans le Dressing',
  'confirm_outfit': 'Confirmer la Tenue',
  'camera_permission_required': 'L\'autorisation de la caméra est requise pour capturer des tenues',
  'camera_init_error': 'Échec de l\'initialisation de la caméra. Veuillez réessayer.',
  'getting_ai_suggestions': 'Obtention de suggestions IA...',
  'get_ai_tips': 'Obtenir des Conseils IA',
  'gallery_pick_error': 'Échec de la sélection de l\'image dans la galerie',
  'how_to_log_outfit': 'Comment souhaitez-vous enregistrer votre tenue ?',
  'capture_method_subtitle': 'Choisissez votre méthode préférée pour capturer rapidement votre look du jour',
  'take_photo': 'Prendre une Photo',
  'take_photo_subtitle': 'Capturez votre tenue avec la caméra',
  'build_from_wardrobe': 'Construire à partir du Dressing',
  'build_from_wardrobe_subtitle': 'Sélectionnez des articles dans votre Dressing',
  'wear_this_today': 'Porter aujourd\'hui',
  'save_for_later_btn': 'Enregistrer pour plus tard',
  'retake': 'Recommencer',
  'rate_outfit_error': 'Veuillez évaluer votre tenue avant de l\'enregistrer',
  'outfit_preview': 'Aperçu de la Tenue',
  'outfit_logged_success': 'Tenue enregistrée avec succès !',
  'optional_notes_hint': 'Ajoutez des notes sur cette tenue...',
  'no_image_captured': 'Aucune image capturée',
  'selected_items_count': 'Articles Sélectionnés ({count})',
  'outfit_name_optional': 'Nom de la Tenue (Optionnel)',
  'outfit_name_hint': 'ex: Vendredi Décontracté, Soirée en amoureux',
  'feel_in_outfit_question': 'Comment vous êtes-vous senti dans cette tenue ?',
  'rating_not_great': 'Pas super',
  'rating_ok': 'Correct',
  'rating_loved_it': 'J\'ai adoré',
  'save_outfit': 'Enregistrer la tenue',
  'select_at_least_one_item': 'Veuillez sélectionner au moins un article',
  'search_wardrobe_hint': 'Rechercher des articles...',
  'no_items_found': 'Aucun article trouvé',
  'continue_with_item_singular': 'Continuer avec {count} article',
  'continue_with_items_plural': 'Continuer avec {count} articles',
  'cost_per_wear': 'Coût par usage',
  'per_wear': '/usage',

  // Progress Dashborad
  'my_progress': 'Ma Progression',
  'challenge_center': 'Centre de Défis',
  'challenge_center_subtitle': 'Parcourez et rejoignez de nouveaux défis de style.',
  'active_challenges': 'Défis en Cours',
  'your_statistics': 'Vos Statistiques',
  'view_all': 'Voir Tout',
  'day_streak': 'jours consécutifs',
  'progress_hero_title': 'Votre progression prend de l\'élan',
  'progress_hero_no_logs': 'Commencez à enregistrer des tenues pour suivre votre parcours.',
  'progress_hero_start': 'Enregistrez votre première tenue pour commencer.',
  'progress_hero_default': 'Continuez à construire votre historique de style.',
  'outfits_logged_so_far': 'tenues enregistrées',
  'challenges_active': 'défis actifs.',
  'motivation_start': 'Commencez votre série aujourd\'hui — enregistrez votre première tenue.',
  'motivation_building': 'Bon début — continuez !',
  'motivation_going': 'Vous construisez de bonnes habitudes de style.',
  'motivation_strong': 'Série impressionnante — vous êtes en pleine forme !',
  'no_active_challenges': 'Aucun défi actif en ce moment',
  'no_active_challenges_hint': 'Visitez le Centre de Défis pour rejoindre un objectif.',
  'browse_challenges': 'Voir les Défis',
  'wardrobe_items': 'Articles Dressing',
  'total_spent': 'Total Dépensé',
  'wardrobe_utilization': 'Articles Portés',
  'purchases_this_month': 'Achats ce Mois',

    // ── HELP CENTER ──────────────────────────────────────────────────────────────
  'help_center_hero_title': 'Bienvenue au Centre d\'aide Everywear',
  'help_center_hero_subtitle': 'Un guide calme sur le fonctionnement de l\'application, à quoi sert chaque espace, et comment tirer le meilleur parti de votre parcours vestimentaire.',
  'help_center_studio_intro': 'Everywear est conçu comme un studio calme pour votre dressing. Cet espace vous aide à comprendre comment l\'application fonctionne, comment développer votre style, et comment profiter au mieux de vos vêtements.',
  'help_center_philosophy_title': 'Notre Philosophie',
  'help_center_philosophy_heading': 'Everywear est conçu comme un espace vestimentaire personnel et calme.',
  'help_center_philosophy_body': 'L\'objectif n\'est pas de vous pousser à acheter plus ou à vous habiller d\'une certaine façon. L\'objectif est de vous aider à voir votre dressing plus clairement, à l\'utiliser plus intentionnellement, et à construire un style qui vous ressemble.',
  'help_center_how_it_works_title': 'Comment fonctionne Everywear',
  'help_center_step1_title': 'Ajoutez votre dressing',
  'help_center_step1_desc': 'Commencez par quelques pièces que vous portez souvent. Vous n\'avez pas besoin de tout ajouter d\'un coup.',
  'help_center_step2_title': 'Enregistrez vos tenues',
  'help_center_step2_desc': 'Suivez ce que vous portez vraiment. Cela aide l\'application à comprendre vos habitudes et à améliorer vos suggestions.',
  'help_center_step3_title': 'Explorez vos suggestions quotidiennes',
  'help_center_step3_desc': 'Utilisez la page Aujourd\'hui pour obtenir des idées de tenues basées sur votre humeur, vos plans et le contexte de votre dressing.',
  'help_center_step4_title': 'Développez votre style avec le coaching',
  'help_center_step4_desc': 'Utilisez la page Style pour découvrir des défis, répondre à des quiz, et obtenir des conseils plus réfléchis au fil du temps.',
  'help_center_pro_tip': 'Astuce : Plus vous enregistrez de tenues, plus vos suggestions quotidiennes et vos insights deviennent personnels.',
  'help_center_pages_title': 'À quoi sert chaque page',
  'help_center_page_today_title': 'Aujourd\'hui',
  'help_center_page_today_desc': 'Votre espace quotidien pour les idées de tenues, les enregistrements rapides et les conseils du matin.',
  'help_center_page_wardrobe_title': 'Dressing',
  'help_center_page_wardrobe_desc': 'Votre collection personnelle de vêtements, organisée et prête à styliser.',
  'help_center_page_style_title': 'Style',
  'help_center_page_style_desc': 'Votre espace de coaching pour les quiz, les défis, les événements et la croissance personnelle.',
  'help_center_page_purchases_title': 'Achats',
  'help_center_page_purchases_desc': 'Suivez vos dépenses vestimentaires, votre liste de souhaits et la valeur à long terme de vos achats.',
  'help_center_page_profile_title': 'Profil',
  'help_center_page_profile_desc': 'Consultez vos insights, réussites, progression, abonnement et paramètres.',
  'help_center_membership_title': 'Abonnement',
  'help_center_essential_title': 'Essentiel',
  'help_center_essential_desc': 'Une expérience principale raffinée avec gestion du dressing, utilisation quotidienne et conseils IA sélectionnés.',
  'help_center_signature_title': 'Signature',
  'help_center_signature_desc': 'Une expérience plus approfondie avec plus de suggestions, plus de coaching, plus de possibilités de tenues et un parcours premium plus fluide.',
  'help_center_faq_title': 'Questions Fréquentes',
  'help_center_need_help_title': 'Besoin d\'aide supplémentaire ?',
  'help_center_need_help_body1': 'Si quelque chose ne fonctionne pas comme prévu, ou si vous souhaitez partager vos commentaires, veuillez utiliser l\'option de retour dans les Paramètres.',
  'help_center_need_help_body2': 'Everywear est conçu pour évoluer de manière réfléchie, et vos retours aident à façonner ce processus.',
  
  // FAQ Questions & Answers
  'faq_q1': 'Qu\'est-ce que Everywear ?',
  'faq_a1': 'Everywear est votre studio vestimentaire personnel. Il vous aide à organiser vos vêtements, obtenir des idées de tenues quotidiennes, suivre vos habitudes de style et prendre des décisions d\'achat plus réfléchies.',
  'faq_q2': 'Comment devrais-je commencer à utiliser l\'application ?',
  'faq_a2': 'Commencez par ajouter quelques pièces clés de votre dressing, puis enregistrez vos tenues au fur et à mesure. Plus vous utilisez l\'application, plus vos suggestions, insights et coaching deviennent personnels et précis.',
  'faq_q3': 'À quoi sert la page Aujourd\'hui ?',
  'faq_a3': 'La page Aujourd\'hui est votre espace de stylisme quotidien. Elle vous donne une idée de tenue basée sur votre dressing, votre humeur sélectionnée, vos plans et des détails contextuels comme la météo ou les événements à venir.',
  'faq_q4': 'À quoi sert la page Style ?',
  'faq_a4': 'La page Style est votre espace de coaching. Elle est conçue pour la réflexion, les défis, les quiz, la croissance de style et des conseils plus personnels au-delà de la suggestion quotidienne.',
  'faq_q5': 'Que sont les Insights de Style ?',
  'faq_a5': 'Les Insights de Style montrent des schémas dans votre utilisation du dressing — comme vos catégories les plus portées, l\'historique des tenues, l\'utilisation du dressing et la valeur au fil du temps. Ils vous aident à comprendre votre style plus clairement.',
  'faq_q6': 'Quelle est la différence entre Essentiel et Signature ?',
  'faq_a6': 'Essentiel vous donne accès à l\'expérience principale d\'Everywear. Signature débloque plus de suggestions, plus de coaching, plus d\'options de tenues et une expérience premium plus fluide avec moins de limitations.',
  'faq_q7': 'L\'application supprimera-t-elle mon dressing si j\'annule Signature ?',
  'faq_a7': 'Non. Les données de votre dressing restent liées à votre compte. Si vous revenez à Essentiel, vous conservez vos données enregistrées, mais certaines fonctionnalités premium et limites d\'utilisation peuvent ne plus être disponibles.',
  'faq_q8': 'Comment fonctionnent le suivi des achats et de la liste de souhaits ?',
  'faq_a8': 'La page Achats vous aide à enregistrer ce qui entre dans votre dressing, surveiller les dépenses par catégorie, suivre le coût par usage et sauvegarder des articles dans une liste de souhaits avant de les acheter.',
  'faq_q9': 'Everywear vend-il mes données personnelles ?',
  'faq_a9': 'Non. Les données de votre dressing et de votre compte sont utilisées pour alimenter votre expérience dans l\'application. Les paramètres d\'analyse vous permettent de contrôler si les données d\'utilisation anonymes aident à améliorer l\'application.',
  'faq_q10': 'Comment puis-je obtenir de meilleures suggestions ?',
  'faq_a10': 'Ajoutez plus d\'articles à votre dressing, complétez votre quiz de style, enregistrez régulièrement vos tenues et utilisez les options d\'occasion et d\'ambiance. Cela donne à l\'application plus de contexte pour produire des suggestions plus personnelles.',

  // Dynamic AI messages
  'ai_bubble_message_initial':
      '👋 Salut ! J\'ai analysé votre Dressing et trouvé {count} combinaisons de tenues parfaites pour vous aujourd\'hui ! Chaque suggestion est personnalisée en fonction de vos préférences de style, des conditions météorologiques et de vos favoris passés.',
  'ai_bubble_message_found':
      '🎯 J\'ai trouvé {count} tenues propulsées par l\'IA avec une correspondance de {confidence}% avec votre style ! Appuyez sur n\'importe quelle suggestion pour voir des conseils de style détaillés et compléter le look. Envie d\'essayer quelque chose de nouveau ? J\'ai aussi inclus des combinaisons que vous n\'avez pas encore portées !',
  
  // New Wardrobe & Item Management
  'retry': 'Réessayer',
  'items': 'articles',
  'selected_items': 'articles sélectionnés',
  'items_limit_reached': 'Limite d\'articles atteinte',
  'live_sync': 'En direct',
  'wardrobe_search_hint': 'Rechercher par nom ou marque',
  'loading_wardrobe': 'Chargement du Dressing...',
  'failed_to_load_wardrobe': 'Échec du chargement de la Dressing',
  'delete_item': 'Supprimer l\'article',
  'delete_items': 'Supprimer les articles',
  'delete_item_confirmation': 'Êtes-vous sûr de vouloir supprimer cet article de votre Dressing ?',
  'item_deleted_success': 'Article supprimé avec succès',
  'item_delete_error': 'Échec de la suppression de l\'article',
  'items_deleted_success': 'Articles supprimés avec succès',
  'items_delete_error': 'Échec de la suppression des articles',
  'item_added_to_wardrobe': 'ajouté au Dressing',
  'item_save_error': 'Échec de l\'enregistrement de l\'article. Veuillez réessayer.',

  // Daily Log
  'good_morning': 'Bonjour',
  'good_afternoon': 'Bon après-midi',
  'good_evening': 'Bonsoir',
  'log_outfit_btn': 'Enregistrer',
  'repeat_outfit': 'Répéter la tenue',
  'repeat_outfit_question': 'Enregistrer cette tenue à nouveau pour aujourd\'hui ?',
  'outfit_repeated': 'Tenue répétée pour aujourd\'hui !',
  'edit_outfit': 'Modifier la tenue',
  'delete_outfit': 'Supprimer la tenue',
  'delete_outfit_confirmation': 'Êtes-vous sûr de vouloir supprimer cette tenue ?',
  'outfit_deleted': 'Tenue supprimée',
  'outfit_updated': 'Tenue mise à jour !',
  'this_month': 'Ce mois',
  'rating': 'Note : ',
  'weather_fallback_label': 'Le style, à votre façon',
  'daily_log_welcome_subtitle': 'Un espace calme pour choisir ce qui vous convient aujourd\'hui — guidé par votre Dressing, vos plans et votre humeur.',
  'set_todays_direction': 'Définir la direction du jour',
  'set_direction_subtitle': 'Choisissez l\'occasion et l\'ambiance que vous souhaitez. Votre suggestion s\'adaptera en fonction.',
  'dressing_for': 'S\'habiller pour',
  'todays_vibe': 'L\'ambiance du jour',
  'occasion_work': 'Travail',
  'occasion_casual': 'Décontracté',
  'occasion_dinner': 'Dîner',
  'occasion_event': 'Événement',
  'occasion_travel': 'Voyage',
  'mood_casual': 'Décontracté',
  'mood_polished': 'Soigné',
  'mood_comfort': 'Confort',
  'mood_bold': 'Audacieux',
  'mood_surprise': 'Surprise',
  'weather_tip_rain': 'Apportez une couche imperméable aujourd\'hui',
  'weather_tip_snow': 'Superposez les couches et gardez la tenue chaude',
  'weather_tip_sun': 'Parfait pour des couches légères',
  'weather_tip_cloud': 'Une veste légère conviendrait bien',
  'weather_tip_wind': 'Une couche ajustée aidera lors d\'une journée venteuse',
  'weather_tip_default': 'Habillez-vous pour votre journée à venir',
  'todays_style_idea': 'Idée de style du jour',
  'simple_daily_suggestion': 'Une suggestion de tenue quotidienne simple.',
  'anchor_piece_tap_to_swap': 'Pièce maîtresse · appuyez pour échanger',
  'tap_to_swap': 'Appuyez pour échanger',
  'refresh': 'Actualiser',
  'unknown': 'Inconnu',
  'outfit_label': 'Tenue',
  'style_tip': 'Conseil Style',
  'style_tip_no_logs': 'Commencez à enregistrer vos tenues régulièrement pour débloquer plus de modèles de style personnel et des conseils quotidiens plus intelligents.',
  'style_tip_few_logs': 'Vous êtes encore en train de construire votre historique de tenues. Quelques enregistrements supplémentaires rendront vos suggestions plus personnelles et plus variées.',
  'style_tip_bold': 'Puisque vous souhaitez un look plus audacieux aujourd\'hui, gardez une pièce remarquable et laissez le reste de la tenue rester plus équilibré.',
  'style_tip_comfort': 'Le confort fonctionne mieux lorsque la tenue semble toujours intentionnelle. Essayez de garder la base douce et la couche extérieure plus structurée.',
  'style_tip_favorite_occasion': 'Votre occasion la plus fréquente ce mois-ci est {occasion}. Garder une version fiable de ce look prête à l\'emploi peut faire gagner du temps lors des journées chargées.',
  'upcoming_event': 'Événement à venir',
  'in_days_left': 'Dans {days} jours',
  'dress_code_format': 'Code vestimentaire : {dressCode}',
  'item_denim_jacket': 'Veste en jean',
  'item_white_tee': 'T-shirt blanc',
  'item_black_jeans': 'Jean noir',
  'item_sneakers': 'Baskets',
  'item_navy_blazer': 'Blazer bleu marine',
  'item_white_shirt': 'Chemise blanche',
  'item_tailored_trousers': 'Pantalon ajusté',
  'item_leather_shoes': 'Chaussures en cuir',
  'item_statement_jacket': 'Veste originale',
  'item_silk_top': 'Top en soie',
  'item_dark_trousers': 'Pantalon sombre',
  'item_low_heels': 'Talons bas',
  'item_chelsea_boots': 'Bottines Chelsea',
  'item_light_overshirt': 'Surchemise légère',
  'item_breathable_tee': 'T-shirt respirant',
  'item_relaxed_pants': 'Pantalon décontracté',
  'item_comfort_sneakers': 'Baskets confortables',
  'item_structured_blazer': 'Blazer structuré',
  'item_refined_top': 'Haut raffiné',
  'item_tailored_bottoms': 'Bas ajustés',
  'item_dress_shoes': 'Chaussures de ville',
  'item_waterproof_jacket': 'Veste imperméable',
  'item_soft_tee': 'T-shirt doux',
  'item_dark_jeans': 'Jean foncé',
  'item_weatherproof_sneakers': 'Baskets tout temps',
  'item_light_cardigan': 'Gilet léger',
  'item_cotton_tee': 'T-shirt en coton',
  'item_relaxed_trousers': 'Pantalon ample',
  'item_white_sneakers': 'Baskets blanches',
  'item_tailored_overshirt': 'Surchemise ajustée',
  'item_clean_neutral_top': 'Haut neutre épuré',
  'item_straight_trousers': 'Pantalon droit',
  'item_minimal_loafers': 'Mocassins minimalistes',
  'item_chunky_sneakers': 'Baskets compensées',
  'item_black_tee': 'T-shirt noir',
  'item_soft_blouse': 'Chemisier doux',
  'item_straight_jeans': 'Jean droit',
  'item_tailored_shorts': 'Short habillé',
  'item_leather_loafers': 'Mocassins en cuir',
  'item_minimal_trainers': 'Baskets minimalistes',
  'occasion_everyday': 'Tous les jours',
  'event_type_other': 'Autre',
  'item_statement_layer': 'Pièce forte',
  'item_contrast_top': 'Haut contrasté',
  'item_dark_denim': 'Denim foncé',
  'item_bold_sneakers': 'Baskets audacieuses',
  'item_underused_jacket': 'Veste peu portée',
  'item_neutral_base_top': 'Haut basique neutre',
  'item_wide_leg_pants': 'Pantalon large',
  'cat_outerwear': 'Manteaux',
  'cat_top': 'Haut',
  'cat_bottom': 'Bas',
  'cat_shoes': 'Chaussures',
  'cat_footwear': 'Chaussures',
  'cat_anchor': 'Base',
  'cat_clothing': 'Vêtements',
  'unknown_item': 'Article inconnu',
  'todays_log_section': 'Journal d\'aujourd\'hui',
  'nothing_logged_today': 'Rien n\'a encore été enregistré aujourd\'hui',
  'quick_log_prompt': 'Utilisez le bouton d\'enregistrement rapide pour sauvegarder la tenue d\'aujourd\'hui et construire votre historique de style.',
  'swap_item_title': 'Échanger {item}',
  'choose_different_piece': 'Choisissez une pièce différente pour cette idée de tenue',
  'quick_log_options': 'Options d\'Enregistrement Rapide',
  'quick_log_take_photo_title': 'Prendre une Photo',
  'quick_log_take_photo_subtitle': 'Capturez votre tenue maintenant',
  'quick_log_previous_title': 'Enregistrer la Tenue Précédente',
  'quick_log_previous_subtitle': 'Ajouter une tenue de plus tôt aujourd\'hui',
  'quick_log_repeat_title': 'Répéter la Dernière Tenue',
  'quick_log_repeat_subtitle': 'Enregistrez à nouveau votre tenue la plus récente',
  'quick_log_save_displayed_title': 'Sauvegarder la Tenue Affichée',
  'quick_log_save_displayed_subtitle': 'Enregistrer la tenue affichée ci-dessus',
  'total_outfits': 'Total des Tenues',
  'unique_items': 'Articles Uniques',
  'favorite_occasion': 'Occasion Favorite',
  'notes': 'Notes',
  'no_outfit_displayed_error': 'Aucune tenue affichée à sauvegarder',
  'no_valid_wardrobe_items_error': 'Aucun article du Dressing valide dans la tenue affichée',
  'slot_anchor': 'pièce maîtresse',
  'slot_top': 'haut',
  'slot_bottom': 'bas',
  'slot_shoes': 'chaussures',
  'slot_item': 'article',
  'fallback_suggestion_desc': 'Une idée de tenue quotidienne polyvalente construite autour d\'une pièce maîtresse facile.',
  'work_suggestion_desc': 'Une tenue de travail soignée qui reste structurée sans être trop rigide.',
  'dinner_suggestion_desc': 'Un look de soirée légèrement habillé qui semble intentionnel tout en restant confortable.',
  'travel_suggestion_desc': 'Une tenue de voyage pratique pensée pour le mouvement et la superposition.',
  'event_suggestion_desc': 'Une combinaison plus habillée conçue pour une allure élégante et soignée.',
  'rain_suggestion_desc': 'Une tenue pratique adaptée à la météo qui reste confortable par temps humide.',
  'sun_suggestion_desc': 'Une idée de tenue plus légère idéale pour une journée ensoleillée et une liberté de mouvement.',
  'polished_suggestion_desc': 'Une idée de tenue propre et soignée qui affine l\'allure générale sans en faire trop.',
  'bold_suggestion_desc': 'Une combinaison plus expressive qui garde une silhouette simple tout en laissant une pièce se démarquer.',
  'surprise_suggestion_desc': 'Une combinaison plus fraîche conçue pour vous aider à porter quelque chose d\'un peu moins attendu aujourd\'hui.',
  'outfit_image_label': 'Image de la tenue',
  'repeat_outfit_tooltip': 'Répéter la tenue aujourd\'hui',
  'edit_outfit_tooltip': 'Modifier la tenue',
  'delete_outfit_tooltip': 'Supprimer la tenue',
  'outfits_label': 'Tenues',
  'items_label': 'Articles',
  'top_label': 'Top',
  'style_title': 'Style',
  'ask_your_coach': 'Demander à votre coach',
  'add_event': 'Ajouter un événement',
  'delete_event': 'Supprimer l\'événement',
  'remove_event_question': 'Supprimer cet événement ?',
  'style_coach': 'Coach Style',
  'or_pick_a_topic': 'Ou choisissez un sujet',
  'event_name': 'Nom de l\'événement',
  'hint_wedding': 'ex: Mariage de Sarah',
  'date_label': 'Date',
  'dress_code_optional': 'Code vestimentaire (optionnel)',
  'finish': 'Terminer',
  'style_quiz': 'Style Quiz',
  'profile_classic': 'Élégance classique',
  'profile_bold': 'Audacieux & Tendance',
  'profile_active': 'Actif & Sportif',
  'profile_minimalist': 'Minimaliste',
  'monthly_budget': 'Budget mensuel',
  'add_to_wishlist': 'Ajouter à la liste de souhaits',
  'update_price': 'Mettre à jour le prix',
  'mark_as_purchased': 'Marquer comme acheté',
  'remove_from_wishlist': 'Retirer de la liste de souhaits',
  'delete_purchase': 'Supprimer l\'achat',
  'bought_it': 'Acheté !',
  'confirm_purchase': 'Confirmer',
  'how_much_did_you_pay': 'Combien avez-vous payé pour',
  'added_to_wardrobe_log': 'ajouté à votre journal de Dressing',
  'your_personal_collection': 'Votre collection personnelle, prête à styliser partout.',
  'updated_everywhere': 'Mis à jour partout',
  'item_updated': 'Article mis à jour',
  'unsaved_changes': 'Vous avez des modifications non enregistrées. Êtes-vous sûr de vouloir quitter ?',
  'discard': 'Abandonner',
  'edit_item': 'Modifier l\'article',
  'changes': 'Modifications',

  // Category names
  'tops': 'Hauts',
  'bottoms': 'Bas',
  'shoes': 'Chaussures',
  'outerwear': 'Manteaux',
  'accessories': 'Accessoires',
  'dresses': 'Robes',
  'activewear': 'Sportswear',

  // Missing keys added during localization audit
  'challenges': 'Défis',
  'no_upcoming_events': 'Aucun événement à venir',
  'add_event_for_suggestions': 'Ajoutez un événement pour obtenir des suggestions',
  'no_challenges_available': 'Aucun défi disponible',
  'check_back_soon': 'Revenez bientôt pour de nouveaux défis de style',
  'no_insights_yet': 'Pas encore de statistiques',
  'add_items_for_insights': 'Ajoutez des vêtements à votre Dressing pour voir vos statistiques de style',
  'outfits_logged': 'Tenues enregistrées',
  'top_category': 'Catégorie principale',
  'top_occasion': 'Occasion principale',
  'q_style_adventures': 'À quel point êtes-vous aventureux avec le style ?',
  'q_style_adv_works': 'Je reste sur ce que je sais fonctionner',
  'q_style_adv_small': 'J\'aime les petits changements',
  'q_style_adv_often': 'J\'aime expérimenter souvent',
  'q_style_adv_depends': 'Cela dépend de l\'occasion',
  'profile_style': 'Style',
  'today': 'Aujourd\'hui',
  'tomorrow': 'Demain',
  'days': 'jours',
  'overall_rating': 'Note globale',
  'how_did_you_feel': 'Comment vous êtes-vous senti dans cette tenue?',
  'detailed_ratings': 'Notes détaillées',
  'comfort': 'Confort',
  'style': 'Style',
  'versatility': 'Polyvalence',
  'occasion': 'Occasion',
  'would_wear_again': 'À porter à nouveau?',
  'help_us_learn': 'Aidez-nous à apprendre vos préférences',
  'save_rating': 'Enregistrer la note',
  'skip_photo': 'Ignorer la photo',
  'failed_to_capture_photo': 'Échec de la capture. Veuillez réessayer.',
  'save_error': 'Erreur de sauvegarde',
  'final_price': 'Prix final',
  'current_price': 'Prix actuel',
  'filter_by_category': 'Filtrer par catégorie',
  'custom_date_range': 'Plage de dates personnalisée',

  // Quiz — questions 1, 2, 3 & 5
  'q_feel_like_yourself': 'Quelles tenues vous font vous sentir le plus vous-même ?',
  'q_feel_relaxed': 'Décontracté et naturel',
  'q_feel_polished': 'Soigné et intemporel',
  'q_feel_creative': 'Créatif et expressif',
  'q_feel_practical': 'Pratique et sportif',
  'q_colors_dominate': 'Quelles couleurs dominent votre dressing aujourd\'hui ?',
  'q_colors_neutrals': 'Principalement des neutres',
  'q_colors_earth': 'Tons terreux et nuances chaudes',
  'q_colors_bold': 'Couleurs vives et contrastes',
  'q_colors_soft': 'Tons doux et nuances claires',
  'q_help_most': 'Dans quoi souhaitez-vous le plus d\'aide en ce moment ?',
  'q_help_together': 'Avoir l\'air plus soigné',
  'q_help_variety': 'Créer plus de variété de tenues',
  'q_help_shopping': 'Acheter de manière plus réfléchie',
  'q_help_confident': 'Me sentir plus confiant dans ce que je porte',
  'q_matters_most': 'Lorsque vous choisissez des vêtements, qu\'est-ce qui compte le plus pour vous ?',
  'q_matters_comfort': 'Confort',
  'q_matters_elegance': 'Élégance',
  'q_matters_originality': 'Originalité',
  'q_matters_versatility': 'Polyvalence',

  // ── CHALLENGES ──────────────────────────────────────────────────────────────
  'challenge_weekly_label': 'Défi de la semaine',
  'challenge_accept': 'Accepter le défi',
  'challenge_log_progress': 'Enregistrer une tenue',
  'challenge_tap_to_log': 'Appuyez pour enregistrer',
  'challenge_complete_inline': '✅ Défi terminé !',
  'challenge_complete_title': 'Défi accompli !',
  'challenge_next_week': 'Un nouveau défi arrive la semaine prochaine.',
  'challenge_insight_title': 'Insight Style Débloqué',
  'challenge_insight_card_title': 'Votre Insight Style',
  'challenge_insight_cta': 'Super !',
  'challenge_progress_label': 'Progression',
  'challenge_anchor_chosen': 'Votre pièce maîtresse',
  'challenge_anchor_pick_title': 'Choisissez votre pièce maîtresse',
  'challenge_anchor_pick_subtitle': 'C\'est la pièce autour de laquelle vous créerez 3 tenues.',
  'challenge_suggested_for_you': 'Suggéré pour vous',
  'challenge_stylist_tip': 'Conseil de styliste',
  'challenge_how_it_works': 'Comment ça marche',
  'challenge_no_wardrobe': 'Aucun article dans le Dressing. Ajoutez des articles d\'abord.',

  // Additional strings
  'maximum_photos_allowed': 'Nombre maximum de photos',
  'failed_to_select_photo': 'Échec de la sélection de la photo',
  'ai_detected': 'Détecté par IA',
  'share_achievement': 'Partager la réalisation',
  'search_achievements': 'Rechercher des réalisations',
  'add_first_item': 'Ajouter votre premier article',
  'could_not_generate_export': 'Impossible de générer l\'export',
  'export_error': 'Erreur d\'export',
  'take_a_photo': 'Prendre une photo',
  'failed_to_save_preferences': 'Impossible de sauvegarder les préférences',
  'please_provide_rating': 'Veuillez fournir une note',
  'rating_saved_successfully': 'Note enregistrée avec succès',
  'failed_to_save_rating': 'Échec de l\'enregistrement de la note',
  'saving_your_rating': 'Enregistrement de votre note',
  'welcome_to_signature': 'Bienvenue dans Signature',
  'purchases_restored': 'Achats restaurés',
  'key_learnings': 'Points clés',
  'module_locked': 'Module verrouillé',
  'about_learning_paths': 'À propos des parcours d\'apprentissage',
  'how_it_works': 'Comment ça marche:',
  'new_ai_insights_generated': 'Nouveaux insights IA générés avec succès!',
  'send_message': 'Envoyer un message',
  'feedback_sent': 'Merci - votre feedback a été envoyé',
  'could_not_send_feedback': 'Impossible d\'envoyer le feedback',
  'change_photo': 'Changer la photo',
  'profile_photo_updated': 'Photo de profil mise à jour',
  'could_not_upload_photo': 'Impossible de télécharger la photo. Vérifiez les détails dans la console de débogage.',
  'profile_updated_successfully': 'Profil mis à jour avec succès',
  'could_not_update_profile': 'Impossible de mettre à jour le profil',
  'wear_this': 'Porter ceci',
  'log_first_outfit': 'Enregistrer votre première tenue',
  'challenge_accepted': 'Défi accepté! Bonne chance!',
  'no_challenges_found': 'Aucun défi trouvé',
  'password_updated': 'Mot de passe mis à jour avec succès',
  'could_not_update_password': 'Impossible de mettre à jour le mot de passe',
  'update_password_btn': 'Mettre à jour le mot de passe',
  'morning_ai_suggestions': 'Suggestions IA du matin',
  'daily_outfit_ideas': 'Idées de tenue quotidiennes chaque matin',
  'events': 'Événements',
  'tip_of_the_week': 'Conseil de la semaine',
  'personalized_coaching': 'Coaching personnalisé',
  'complete_quiz_for_coaching': 'Complétez votre quiz pour un meilleur coaching',
  'coach_is_thinking': 'Votre coach réfléchit...',
  'coach_is_preparing_tip': 'Votre coach prépare un conseil pour vous...',
  'discover_your_style': 'Découvrez votre style',
  'retake_quiz': 'Refaire',
  'take_quiz_to_personalise': 'Faites le quiz pour personnaliser vos suggestions IA',
  'quick_questions': 'Questions rapides',
  'get_help_styling_pieces': 'Obtenez de l\'aide pour styliser les pièces que vous possédez',
  'event_coaching': 'Coaching pour événements',
  'suggestions_for': 'Suggestions pour {title}',
  'add_event_to_unlock': 'Ajoutez un événement pour débloquer ceci',
  'coach_limit_reached': 'Limite du coach atteinte',
  'premium_coach_limit_msg': 'Vous avez utilisé toutes vos 50 sessions de coaching ce mois-ci. Votre quota sera réinitialisé le mois prochain.',
  'free_coach_limit_msg': 'Le plan Essentiel comprend 1 session de coaching par semaine. Passez à Signature pour 50 sessions par mois.',
  'ask_your_coach_btn': 'Demandez à votre coach',
  'type_question_or_pick_topic': 'Tapez votre propre question ou choisissez un sujet.',
  'coach_hint_text': 'ex: Comment avoir l\'air plus confiant ?',
  'topic_outfit_ideas': '👔 Idées de tenues',
  'topic_shopping_advice': '🛍 Conseils d\'achat',
  'topic_my_wardrobe': '👗 Mon Dressing',
  'topic_for_an_event': '📅 Pour un événement',
  'topic_more_variety': '🔄 Plus de variété',
  'topic_style_upgrade': '✨ Amélioration de style',
  'q_outfit_ideas': 'Donnez-moi des idées de tenues basées sur mon Dressing et mon profil de style.',
  'q_shopping_advice': 'Quelle pièce devrais-je acheter ensuite pour compléter plus de tenues dans mon Dressing ?',
  'q_my_wardrobe': 'Donnez-moi une évaluation honnête de mon Dressing basée sur mes données.',
  'q_for_an_event': 'Comment devrais-je m\'habiller pour une occasion spéciale basée sur mon style ?',
  'q_more_variety': 'Comment puis-je créer plus de variété de tenues avec ce que je possède déjà ?',
  'q_style_upgrade': 'Quelle est la chose que je peux changer pour élever mon style quotidien ?',
  // Challenge type titles
  'challenge_type_anchor_title': 'Pièce d\'Ancrage',
  'challenge_type_anchor_description': 'Choisissez une pièce clé de votre dressing et créez 3 tenues différentes autour d\'elle pendant la semaine.',
  'challenge_type_capsule_title': 'Défi Capsule',
  'challenge_type_capsule_description': 'Sélectionnez 7 pièces et créez 5 tenues différentes en utilisant uniquement ces vêtements.',
  'challenge_type_color_title': 'Histoire de Couleurs',
  'challenge_type_color_description': 'Créez des tenues en utilisant une palette de couleurs cohérente - essayez les tons marine, camel ou olive.',
  'challenge_type_rediscover_title': 'Redécouverte',
  'challenge_type_rediscover_description': 'Trouvez un vêtement non porté dans votre dressing et stylisez-le d\'une nouvelle manière.',
};
